### PR TITLE
JBrowse sync with 1.15.X

### PR DESCRIPTION
**Pull request by nathandunn**
replaces #1870

### CODE REVIEW

**Comment by deepakunni3** [comment]
Things found while testing the UI:

1. default chevron styling clashes with track styling
2. On a click-drag-drop operation of an exon, the exon ghost is off by several bases. But after the drop operation, the exon ends up at the right place within UcA
3. Get Sequence/Get GFF3/Show History - CSS styling issue
4. Confirm Dialog on Change annotation type operation doesn't go away on clicking 'Yes'. Have to click on X or Cancel.
5. Cannot change color scheme
6. Alt+Click shortcut on an annotation doesn't bring up the Information Editor
7. Set longest ORF/Set read through stop codon operation doesn't work - error on console: `jquery.js:253 Uncaught Error: cannot call methods on resizable prior to initialization; attempted to call method 'destroy'`
8. Undo/Redo operation doesn't work  - error on console: `jquery.js:253 Uncaught Error: cannot call methods on resizable prior to initialization; attempted to call method 'destroy'`
9. Refreshing the browser forgets the location of current view
10. Duplicate operation fails - error on console: `jquery.js:253 Uncaught Error: cannot call methods on resizable prior to initialization; attempted to call method 'destroy'`

**Comment by nathandunn** [comment]
thanks @deepakunni3  not sure if some of these can be solved with jQuery updates or not.   A lot of the CSS stuff should be fixable.   There are also some weird interactions with the amel.css we provide, but I fear we're going to find a few more of those. 

I'll let you know when there is another version (probably next week).   Thanks

**Comment by deepakunni3** [comment]
@nathandunn `amel.css`? Could you provide a link to that CSS, for reference? 
Yes, there might be some tweaking required to existing track styling. If this is the way moving forward then we should have a documentation on how to update CSS in light of this PR.

**Comment by nathandunn** [comment]
Well, just the honeybee data might have changed.  Everything else should be unaffected. 

If its what we distributed before, just look in the honeybee directory and you’ll see it in there.  If not, then the error is on my end.

**Comment by deepakunni3** [comment]
ah, okay. So its data directory specific 👍

**Comment by nathandunn** [comment]
Right.   Its just it provides the overrides.

**Comment by nathandunn** [comment]
Closing in favor of #1925

**Pull request closed without merging**
