### PR TITLE
Add security filter to address organism controller issues

### PR DESCRIPTION
**Pull request by cmdcolin**
This pull request is aimed at addressing some of the numerous issues that we have had with security. The paths for security were fragmented and so I tried to make all API calls go through the grails SecurityFilter. This Securityfilter is enabled only for the OrganismController for the time being, but it effectively performs authentication for the users.

Using the SecurityFilter also takes away a lot of the excessive code regarding permissions by automatically performing these functions
See #665

To test, you can try curling various APIs like addOrganism, deleteOrganism, findAllOrganisms, etc.

On master branch, this actually succeeds:

    curl -H "Content-Type: application/json" -X POST -d '{"username":"colin.diesh@gmail.com","directory":"/opt/apollo/pyu_data","organism":"PYU2"}' http://localhost:8080/apollo/organism/deleteOrganism

No good as this is clearly passwordless

With the authentication filter, this is easily blocked, and you can test this similarly to verify

### CODE REVIEW

**Comment by cmdcolin** [comment]
You can also see that the code changes are fairly minimal in scope, but could certainly be expanded, but in this case it addresses #665

**Comment by nathandunn** [comment]
K . . I'll take a look on Monday . . there are numerous side-effects that I want to retest and do more analysis on.  I know that everything in AnnotationEditorController should secure using "hasPermissions . . . " (I think it even gets checked twice . . again in RequestHandlingService) . . maybe the way you established the pattern its a bit more blanketed, though, which would be good.

**Comment by cmdcolin** [comment]
The security filter is only applied to OrganismController here, but I imagine it could be applied to other controllers to simplify their logic

**Comment by cmdcolin** [comment]
But ya, thanks, np

**Comment by nathandunn** [comment]
less code :+1:    hopefully we can extend it . .. see it on Monday

**Comment by nathandunn** [comment]
@cmdcolin   This looks good.  I tested the UI and a script for adding organisms and both seemed to work well.     

Another way to do this (possibly as we extend more) are here . . where you put at as an interceptor on each controller . . . not sure which model will be better long-term as shiro is more centralized and spring security is more distributed:

https://grails.github.io/grails-doc/3.0.x/ref/Controllers/beforeInterceptor.html

Should be able to do something similar for user and group if they suffer from the same issues.

**Pull request merged**
