### PR TITLE
Consolidate exports in IOServiceController

### PR DESCRIPTION
**Pull request by cmdcolin**
Regarding discussion from #467, the code from SequenceController and IOServiceController have been consolidated for gff3 and fasta exports. It still uses uuid and the annotator panel exports as well as the in-browser "Save track data" functions.

A technical note:

The behavior of prepending the string "Annotations-" to almost everything from AnnotTrack is removed in this pull request. The reasoning in the past was that this "prefix" could be custmized to support multiple organisms, but now our method for handling multiple organisms completely different

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   Thanks for doing this.  Will take a look at this in a little bit.

**Comment by nathandunn** [comment]
@cmdcolin  Are the gzip changes in here (or did you say gff3?).

**Comment by nathandunn** [comment]
@cmdcolin   I think that this still needs some work.  Not sure if its worth doing unless you add the gzip component.   I would rather see the optimizations first, though. 

I also had issues exporting FASTA on the Sequence Panel (claimed there were no annotations).  

1) when I export from the Ref Sequence panel:

```
operation: write
operation: write
action: handleOperation
exportSequence: false
exportSequence: false
controller: IOService
tracks: Annotations-Group1.1
tracks: Annotations-Group1.1
format: gzip
format: gzip
adapter: Only GFF3
adapter: Only GFF3
output: file
output: file
type: GFF3
type: GFF3
Named parameter [sequenceNames] value may not be null. Stacktrace follows:
Message: Named parameter [sequenceNames] value may not be null
    Line | Method
->>   54 | write            in org.bbop.apollo.IOServiceController
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    198 | doFilter         in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . in grails.plugin.cache.web.filter.AbstractFilter
|     30 | handleOperation  in org.bbop.apollo.IOServiceController
|    198 | doFilter . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter         in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain . . in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call             in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall . . . . . in org.apache.shiro.subject.support.SubjectCallable
|     83 | call             in     ''
|    383 | execute . . . .  in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter . . . . in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1145 | runWorker        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run              in java.lang.Thread
2015-07-09 14:53:20,302 [http-bio-8080-exec-4] WARN  apollo.IOServiceController  - There are no annotations to be exported in this list of sequences [{"id":18,"start":0,"name":"Group1.1","length":1382403,"end":1382403}]
| Error 2015-07-09 14:53:20,315 [http-bio-8080-exec-4] ERROR spi.SqlExceptionHelper  - ERROR: syntax error at or near ")"
  Position: 900
| Error 2015-07-09 14:53:20,331 [http-bio-8080-exec-4] ERROR errors.GrailsExceptionResolver  - PSQLException occurred when processing request: [POST] /apollo/IOService/write - parameters:
data: {"type":"GFF3", "sequenceType":"genomic", "exportAllSequences":"false", "exportGff3Fasta":"false", "output":"json", "sequences":[{"id":18, "name":"Group1.1", "start":0, "end":1382403, "length":1382403}]}
ERROR: syntax error at or near ")"
  Position: 900. Stacktrace follows:
Message: ERROR: syntax error at or near ")"
  Position: 900
    Line | Method
->> 2161 | receiveErrorResponse in org.postgresql.core.v3.QueryExecutorImpl
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1890 | processResults       in     ''
|    255 | execute . . . . . .  in     ''
|    559 | execute              in org.postgresql.jdbc2.AbstractJdbc2Statement
|    417 | executeWithFlags . . in     ''
|    302 | executeQuery         in     ''
|     74 | write . . . . . . .  in org.bbop.apollo.IOServiceController
|    198 | doFilter             in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain         in org.apache.shiro.web.servlet.AbstractShiroFilter
```

2) when exporting a fasta sequence I get this:

```
| Error 2015-07-09 14:57:12,649 [http-bio-8080-exec-11] ERROR apollo.JbrowseController  - Could not get data directory: /opt/apollo/honeybee/data//tracks.conf
| Error 2015-07-09 14:57:36,739 [http-bio-8080-exec-9] ERROR errors.GrailsExceptionResolver  - NullPointerException occurred when processing request: [GET] /apollo/IOService - parameters:
operation: write
operation: write
seqType: peptide
seqType: peptide
action: handleOperation
sequences: Group1.1
sequences: Group1.1
controller: IOService
format: gzip
format: gzip
adapter: peptide
adapter: peptide
output: file
output: file
type: FASTA
type: FASTA
Cannot invoke method length() on null object. Stacktrace follows:
Message: Cannot invoke method length() on null object
    Line | Method
->>  121 | writeFeature     in org.bbop.apollo.FastaHandlerService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    113 | writeFeatures    in     ''
|    100 | writeFeatures .  in     ''
|     98 | write            in org.bbop.apollo.IOServiceController
|    198 | doFilter . . . . in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter         in grails.plugin.cache.web.filter.AbstractFilter
```

**Comment by nathandunn** [comment]
The gzip bug is #252.   Again, all of this code works in the master branch right now, so this is lower priority.

**Comment by cmdcolin** [comment]
I pushed the gzip change but you are right that this needs some touchups. Will let you know

**Comment by nathandunn** [comment]
K.  Thanks.  

Nathan

**Comment by cmdcolin** [comment]
@nathandunn  bugs should be fixed now.

**Comment by nathandunn** [comment]
K .. Will merge on Tuesday.  Make sure to assign it to me with the rc2 milestone and mark it as review / working on. 

Nathan

**Comment by cmdcolin** [comment]
Is it ok can I just merge it now? It seems fine and then I can mark the other bugs as ready to be tested on tuesday?

**Comment by nathandunn** [comment]
Could you have Deepak review and/or merge it.  Much of it is his code anyway.  Would do it myself but am out today.  Just good practice to review refractors.  Thanks.

Nathan

**Comment by cmdcolin** [comment]
Deepak and I did a code review and we determined it was ready. In the process, we fixed up the FASTA inclusion in GFF3 exports, checking permissions on IOServiceController, and fixing the get_gff3 command line script to use those permissions

**Comment by nathandunn** [comment]
@cmdcolin  @deepakunni3   Good timing . ..  was just testing and noticed the gff3 + FASTA track wasn't working.  I'll get this tested and in sometime today (hopefully sooner than later).    Thanks for doing this.  Easier to refactor now then later.

**Comment by nathandunn** [comment]
Testing 
- [ ] tracks:
  - [ ] GFF3
  - [ ] GFF + FASTA
  - [ ] FASTA (all)
- [ ] feature:
   - [ ] get_sequence (all)
   - [ ] get_gff3
- [ ] Ref Sequence:
   - [ ] GFF3 
   - [ ] GFF3 + FASTA 
   - [ ] FASTA All

**Comment by nathandunn** [comment]
@deepakunni3  @cmdcolin   The sequence panel worked, but wasn't gzipped . . I fixed that and another minor thing.

**Comment by cmdcolin** [comment]
Looks good to me.

**Comment by nathandunn** [comment]
Test that the following exports still work with Gzip support:
- [ ] tracks:
  - [ ] GFF3
  - [ ] GFF + FASTA
  - [ ] FASTA (all)
- [ ] feature:
   - [ ] get_sequence (all)
   - [ ] get_gff3
- [ ] Ref Sequence:
   - [ ] GFF3 
   - [ ] GFF3 + FASTA 
   - [ ] FASTA All

**Pull request merged**
