### PR TITLE
added the login for non-annotator pages

### LINKED ISSUE #809: when logged out on a non-annotator page (e.g., reports page) should go to an appropriate login page
The default for this in grails will go back to the page you are trying to login to once you are successful

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes #809. 

there is a better fix using the natural shiro api's, but SecurityFilter kind of messes that up a bit.  Anyway, what is here is good enough and provides the login. 

Nathan

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  or @cmdcolin   can you have a look at this on Monday?

**Comment by cmdcolin** [comment]
The login button appears to redirect to /apollo/annotator

Would be good if it stayed on the page that you logged in from

**Comment by nathandunn** [comment]
By default accessControl does this.  I removed the special case for Organism, but then that had other problems.  For now this should be sufficient.  I'm hoping to replace the security model anyway.

**Comment by cmdcolin** [comment]
Sorry to be disagreeable but why is this the case? You mentioned even on the other issues

"The default for this in grails will go back to the page you are trying to login to once you are successful"

**Comment by nathandunn** [comment]
Actually, its worse than that, the current implementation ignores the rememberMe token and the redirect.   The current implementation fixes that barely and will still work with migration.   Anything outside of the OrganismController automatically bypasses security at the Shiro level.  This is just a minor UI improvement (going to login vs unauthorized).

**Comment by cmdcolin** [comment]
The SecurityFilter on organism controller I felt was a start toward more automatic authentication at the API level. Are you saying that the OrganismController is causing issues or that the other controllers are causing the issues?

**Comment by nathandunn** [comment]
Right, was getting this error:  

```
No such property: permissions for class: org.bbop.apollo.User. Stacktrace follows:
Message: No such property: permissions for class: org.bbop.apollo.User
    Line | Method
->>   74 | isPermitted         in org.bbop.apollo.DbRealm
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    237 | isPermitted         in org.apache.shiro.grails.RealmWrapper
|     59 | isPermitted . . . . in org.apache.shiro.grails.RealmAdapter
|    223 | isPermitted         in org.apache.shiro.authz.ModularRealmAuthorizer
|    113 | isPermitted . . . . in org.apache.shiro.mgt.AuthorizingSecurityManager
|    158 | isPermitted         in org.apache.shiro.subject.support.DelegatingSubject
|    470 | accessControlMethod in ShiroGrailsPlugin
```

**Pull request merged**
