### PR TITLE
Fix ioservice error

### PR DESCRIPTION
**Pull request by nathandunn**
@deepakunni3   I think I'd over-looked a case.  This is also for #1027. 

screen shot 2016-05-13 at 11 55 09 am

Can you confirm that this works without breaking anything?   I went through a few tests and it still seems to work.

### CODE REVIEW

**Comment by deepakunni3** [comment]
`handleInput()` must be added to `updateFeature` and `updateFeatureLocation`, in `AnnotatorController`, to be able to handle client token. 

If not, changing exon coordinates from 'Coding' tab of side panel fails.

**Comment by nathandunn** [comment]
@deepakunni3   Thanks.  I'll make that change as well and push when its ready.

**Comment by nathandunn** [comment]
I think I fixed that, but having issues with loadLink which are new . . grr . . and the preferences seem to be saving weird.

**Comment by nathandunn** [comment]
Turns out I had a badly behaving browser.

**Pull request merged**
