### PR TITLE
Fix white background on select box. See #870

### PR DESCRIPTION
**Pull request by cmdcolin**
I found that the OS added a default background-color: white when the select box was selected, and since text color was white, it created the effect seen in #870 

This PR just adds the background-color: gray when element is focused

### CODE REVIEW

**Comment by nathandunn** [comment]
Had to merge manually, but looked good.

**Comment by cmdcolin** [comment]
Doesn't look like it's on master branch yet :)

If you want i can make this branch up to date for easier merging ?

**Comment by nathandunn** [comment]
I thought I merged it and put it upstream.  I was going to test it since it seemed weird.  I will see wha't up.  One minute.

**Comment by nathandunn** [comment]
Weird . . I thought I could push it upstream from the branch I used to merge . . guess not.  There now.

**Comment by cmdcolin** [comment]
Cool. Let me know if there are issues with it!

**Pull request merged**
