### PR TITLE
fix_annotations

### LINKED ISSUE #752: features not being returned on annotation panel
I think that the error is in the queries around line 294 in AnnotatorController.    I *think8 what needs to happen is that  bookmark.sequenceList needs to be turned into a set of sequences at around line 310.

### PR DESCRIPTION
**Pull request by nathandunn**
Fixed #752

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  Review and let me know if it works when you have a moment.

**Comment by nathandunn** [comment]
@deepakunni3   I think that this accidentally got merged by me as I'd merged it into a local branch. 

Anyway, you can see my fix.

**Comment by deepakunni3** [comment]
@nathandunn I went through the code and it looks good. :+1:

**Comment by nathandunn** [comment]
Thanks!

**Pull request merged**
