### PR TITLE
Fix for issue 1475 - NAL test

### PR DESCRIPTION
**Pull request by deepakunni3**
Discussion from #1475

### CODE REVIEW

**Comment by nathandunn** [comment]
FYI @poelchau @childers    Not sure if this is the right approach, but we thought it might fix one of your use-cases.  We'll discuss this this week.

**Comment by nathandunn** [comment]
FYI @mpoelchau @childers    Not sure if this is the right approach, but we thought it might fix #1475.  We'll discuss this this week.

**Comment by deepakunni3** [comment]
@nathandunn This PR has yet to include the fix for the issue. The commit I made was just a start. 
I'll assign it to you when its ready for review.

**Comment by deepakunni3** [comment]
@nathandunn This is ready for review, testing and further discussion.

**Comment by nathandunn** [comment]
Code looks good.

**Comment by mpoelchau** [comment]
Just tested - it doesn't seem to work for our situation. The mRNA name in the input gff3 is Cathepsin C-like peptidase 1; it is C534F5982220A80890CE029E3F48D663-00001 in the output.  

Here's the command I used:

perl add_transcripts_from_gff3_to_annotations.pl -o 'Frankliniella occidentalis' -l success.log -L error.log -i fraocc_annotations_cleaned.gff -u i5k@ars.usda.gov -p LALALA -U https://apollo-dev.nal.usda.gov/apollo -X --use_name_for_feature

**Input gff:**
Scaffold3930    WebApollo       gene    15210   16373   .       -       .       ID=C534F5982220A80890CE029E3F48D663;Name=C534F5982220A80890CE029E3F48D663;date_last_modified=2014-10-10;date_creation=2014-10-10
Scaffold3930    WebApollo       mRNA    15210   16373   .       -       .       ID=98536D6705A1CA6F4A6E67B98F02E37F;Name=Cathepsin C-like peptidase 1;Parent=C534F5982220A80890CE029E3F48D663;Note=N-end missing%2C end of scafforld;symbol=CatC1;date_creation=2014-10-10;replace=FoccTmpM016916-RA;date_last_modified=2014-11-21
Scaffold3930    WebApollo       exon    15210   15407   .       -       .       ID=1D0FC5A8FB4A2916DE492AF1EA802873;Name=1D0FC5A8FB4A2916DE492AF1EA802873;Parent=98536D6705A1CA6F4A6E67B98F02E37F;date_last_modified=2014-10-10;date_creation=2014-10-10
Scaffold3930    WebApollo       exon    15746   15909   .       -       .       ID=EA0AD77C94051A827DAFE331A9CD0E9E;Name=EA0AD77C94051A827DAFE331A9CD0E9E;Parent=98536D6705A1CA6F4A6E67B98F02E37F;date_last_modified=2014-10-10;date_creation=2014-10-10
Scaffold3930    WebApollo       exon    16004   16373   .       -       .       ID=BADEAA221242FDBDEBFF731A3F39FA5B;Name=BADEAA221242FDBDEBFF731A3F39FA5B;Parent=98536D6705A1CA6F4A6E67B98F02E37F;date_last_modified=2014-10-10;date_creation=2014-10-10
Scaffold3930    WebApollo       CDS     16004   16373   .       -       0       ID=DE9BE3B90FFA0CDFD662D96235F23D7F;Name=DE9BE3B90FFA0CDFD662D96235F23D7F;Parent=98536D6705A1CA6F4A6E67B98F02E37F;Note=Manually set translation start;date_creation=2014-10-10;date_last_modified=2014-10-10
Scaffold3930    WebApollo       CDS     15746   15909   .       -       2       ID=DE9BE3B90FFA0CDFD662D96235F23D7F;Name=DE9BE3B90FFA0CDFD662D96235F23D7F;Parent=98536D6705A1CA6F4A6E67B98F02E37F;Note=Manually set translation start;date_creation=2014-10-10;date_last_modified=2014-10-10
Scaffold3930    WebApollo       CDS     15225   15407   .       -       0       ID=DE9BE3B90FFA0CDFD662D96235F23D7F;Name=DE9BE3B90FFA0CDFD662D96235F23D7F;Parent=98536D6705A1CA6F4A6E67B98F02E37F;Note=Manually set translation start;date_creation=2014-10-10;date_last_modified=2014-10-10


**Output gff from Apollo2:**
Scaffold3930	.	gene	15210	16373	.	-	.	owner=i5k@ars.usda.gov;ID=75530f3d-b0ca-479a-8733-40883324244f;date_last_modified=2017-02-09;Name=C534F5982220A80890CE029E3F48D663;date_creation=2017-02-09
Scaffold3930	.	mRNA	15210	16373	.	-	.	owner=i5k@ars.usda.gov;symbol=CatC1;Parent=75530f3d-b0ca-479a-8733-40883324244f;Note=N-end missing%2C end of scafforld;replace=FoccTmpM016916-RA;ID=6dfff8e9-667d-46eb-909c-a739b22a9256;date_last_modified=2017-02-09;Name=C534F5982220A80890CE029E3F48D663-00001;date_creation=2017-02-09
Scaffold3930	.	exon	16004	16373	.	-	.	Parent=6dfff8e9-667d-46eb-909c-a739b22a9256;ID=4368fb7a-100b-4a4d-a702-65de4be6b312;Name=BADEAA221242FDBDEBFF731A3F39FA5B
Scaffold3930	.	exon	15210	15407	.	-	.	Parent=6dfff8e9-667d-46eb-909c-a739b22a9256;ID=8fb15ab6-17aa-4dba-b39f-ae4d2b0a935a;Name=1D0FC5A8FB4A2916DE492AF1EA802873
Scaffold3930	.	exon	15746	15909	.	-	.	Parent=6dfff8e9-667d-46eb-909c-a739b22a9256;ID=20f9d9b1-2a6a-478a-823f-fdbeac9b26dd;Name=EA0AD77C94051A827DAFE331A9CD0E9E
Scaffold3930	.	CDS	16004	16373	.	-	0	Parent=6dfff8e9-667d-46eb-909c-a739b22a9256;ID=d7ac5702-7ab6-4209-a9c8-ba5c384ce6dd;Name=DE9BE3B90FFA0CDFD662D96235F23D7F
Scaffold3930	.	CDS	15746	15909	.	-	2	Parent=6dfff8e9-667d-46eb-909c-a739b22a9256;ID=d7ac5702-7ab6-4209-a9c8-ba5c384ce6dd;Name=DE9BE3B90FFA0CDFD662D96235F23D7F
Scaffold3930	.	CDS	15225	15407	.	-	0	Parent=6dfff8e9-667d-46eb-909c-a739b22a9256;ID=d7ac5702-7ab6-4209-a9c8-ba5c384ce6dd;Name=DE9BE3B90FFA0CDFD662D96235F23D7F

**Comment by nathandunn** [comment]
@mpoelchau  This worked off of master with your input and this output using this command (did you remember the (```-X```?):

./add_transcripts_from_gff3_to_annotations.pl -U http://localhost:8080/apollo -u username -p password -i input.gff  --organism some_bug -X 

```
##gff-version 3
##sequence-region Scaffold3930 1 126053
Scaffold3930	.	gene	15210	16373	.	-	.	owner=admin@demo.com;ID=1ac66fb5-0a2a-4ee4-98c7-76debce04cb3;date_last_modified=2017-02-09;Name=Cathepsin;date_creation=2017-02-09
Scaffold3930	.	mRNA	15210	16373	.	-	.	owner=admin@demo.com;Parent=1ac66fb5-0a2a-4ee4-98c7-76debce04cb3;ID=e51d4b65-b1b4-484f-9c62-30bec64c612b;date_last_modified=2017-02-09;Name=Cathepsin-00001;date_creation=2017-02-09
Scaffold3930	.	CDS	16004	16373	.	-	0	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=f155e984-3586-4888-aeb7-abc186f1e5ae;Name=DE9BE3B90FFA0CDFD662D96235F23D7F
Scaffold3930	.	CDS	15746	15909	.	-	2	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=f155e984-3586-4888-aeb7-abc186f1e5ae;Name=DE9BE3B90FFA0CDFD662D96235F23D7F
Scaffold3930	.	CDS	15210	15407	.	-	0	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=f155e984-3586-4888-aeb7-abc186f1e5ae;Name=DE9BE3B90FFA0CDFD662D96235F23D7F
Scaffold3930	.	exon	15210	15407	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=6a942216-fbb7-4769-a1a6-4f85e41f15a6;Name=1D0FC5A8FB4A2916DE492AF1EA802873
Scaffold3930	.	non_canonical_five_prime_splice_site	15744	15744	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_five_prime_splice_site-15743;Name=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_five_prime_splice_site-15743
Scaffold3930	.	exon	16004	16373	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=18a305a0-b18d-4825-b71b-98a0b65c0031;Name=BADEAA221242FDBDEBFF731A3F39FA5B
Scaffold3930	.	non_canonical_three_prime_splice_site	15910	15910	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_three_prime_splice_site-15909;Name=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_three_prime_splice_site-15909
Scaffold3930	.	non_canonical_five_prime_splice_site	16002	16002	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_five_prime_splice_site-16001;Name=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_five_prime_splice_site-16001
Scaffold3930	.	exon	15746	15909	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=faa385da-f5af-4389-82f3-aff1d9ef2e3a;Name=EA0AD77C94051A827DAFE331A9CD0E9E
Scaffold3930	.	non_canonical_three_prime_splice_site	15408	15408	.	-	.	Parent=e51d4b65-b1b4-484f-9c62-30bec64c612b;ID=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_three_prime_splice_site-15407;Name=e51d4b65-b1b4-484f-9c62-30bec64c612b-non_canonical_three_prime_splice_site-15407
###
```

**Comment by nathandunn** [comment]
@mpoelchau   Sorry, @deepakunni3 caught this.  I meant ```-a```.  ```-X``` (upper-case) is for stopping it from recalculating the CDS.    I updated my comment to reflect this.

    ./add_transcripts_from_gff3_to_annotations.pl -U http://localhost:8080/apollo -u admin@demo.com -p demo -i test.gff3  -o Honeybee -X -a

**Pull request merged**
