### PR TITLE
should fix #1643 when merged, upgrading library

### LINKED ISSUE #1643: Users with view but not write don't get notification that they cnnot create annotations
* Search [mailing list](http://gmod.827538.n3.nabble.com/Apollo-f815553.html) or email list ```apollo@lists.lbl.gov``` if a general setup question. 

* Provide what you were doing and what you expected to see.  Screenshots, directory, config files are a plus if relevant.
 ```text
I am testing user permission use cases.  This test was for a user with view but not write.  
As expected, the user could see but not create annotations. The interface allows click to highlight 
and right click to create (and the option to drag to the User-Created Annotations panel).  Since the 
options are visible and not greyed out, the impression is that the user should be able to perform 
the action.  

My expectation is that if a user has view but not write, they should be able to see the User-Created 
Annotations track, but options to create annotations, either through clicking and dragging or right 
clicking should not be available. 
```
* Provide the javascript console log output generated from the action. 
```text
 No errors present in console or in the Apollo interface
```
* Provide the server log output generated from the action (typically ```catalina.out```).
 ```shell
2017-06-13 11:37:35,022 [clientInboundChannel-3] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
java.lang.reflect.InvocationTargetException
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5$_closure6.doCall(AnnotationEditorController.groovy:1145)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4$_closure5.doCall(AnnotationEditorController.groovy:1144)
	at org.bbop.apollo.AnnotationEditorController$__do_annotationEditor_closure4.doCall(AnnotationEditorController.groovy:1140)
	at groovyx.gpars.group.PGroup$3.call(PGroup.java:289)
	at groovyx.gpars.group.PGroup$4.run(PGroup.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.bbop.apollo.AnnotationException: You have insufficient permissions [read < write] to perform this operation
	at org.bbop.apollo.PermissionService.$tt__checkPermissions(PermissionService.groovy:340)
	at org.bbop.apollo.RequestHandlingService.$tt__addTranscript(RequestHandlingService.groovy:624)
	... 8 more
```

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1643

### CODE REVIEW

**Comment by nathandunn** [comment]
- [ ] add unit test for cleaning:

```
"{\"track\":\"chrI\",\"features\":[{\"location\":{\"fmin\":62840,\"fmax\":65405,\"strand\":1},\"type\":{\"cv\":{\"name\":\"sequence\"},\"name\":\"mRNA\"},\"name\":\"YAL041W\",\"children\":[{\"location\":{\"fmin\":62840,\"fmax\":65405,\"strand\":1},\"type\":{\"cv\":{\"name\":\"sequence\"},\"name\":\"exon\"}}]}],\"operation\":\"add_transcript\",\"clientToken\":\"9137872062024864552562677444\"}"
```

Produces error: 

```
keys printed: 
2017-06-15 14:18:15,862 [clientInboundChannel-4] ERROR springwebsocket.GrailsSimpAnnotationMethodMessageHandler  - Unhandled exception
org.codehaus.groovy.grails.web.json.JSONException: JSONObject["operation"] not found.
	at org.bbop.apollo.AnnotationEditorController._do_annotationEditor(AnnotationEditorController.groovy:1127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
FYI @deepakunni3  I think you were getting this error for some of the projection stuff.  

- should not have start quotes or end quotes

**Comment by deepakunni3** [comment]
@nathandunn I also have a fix for it on the client side: https://github.com/deepakunni3/Apollo/commit/561c29d424a3a858b10766bceb79c3938e59bac2

This avoids start quotes and end quotes to begin with.

**Comment by nathandunn** [comment]
@deepakunni3  Nice.  Much cleaner as well. 

Yeah, upgrading the websocket library fixes portions of this one bug, but slightly changes the way things are sent.   Should be interesting, but hopefully not too interesting.

**Comment by nathandunn** [comment]
@deepakunni3  / @childers   Can you review this and let me know if it fixes it (or if you don't encounter any other issues with it). 

Thanks.

**Comment by nathandunn** [comment]
It needs to be tested as "deployed" and in development mode, as it seems to want to report errors differently.

**Comment by deepakunni3** [comment]
@nathandunn Can confirm that errors propagate to the client in both dev mode as well as deployed mode.

**Comment by nathandunn** [comment]
FYI @childers   this fixes #1643.

**Pull request merged**
