### PR TITLE
Revert "Optimize GFF3 exports"

### PR DESCRIPTION
**Pull request by nathandunn**
Reverts GMOD/Apollo#830

Crap . . exporting ALL I get:

```
| Error 2016-01-29 11:50:52,899 [http-bio-8080-exec-8] ERROR errors.GrailsExceptionResolver  - QueryException occurred when processing request: [POST] /apollo/sequence/getSequences/ - parameters:
sort: count
asc: true
start: 0
name: 
length: 20
could not resolve property: count of: org.bbop.apollo.Sequence. Stacktrace follows:
Message: could not resolve property: count of: org.bbop.apollo.Sequence
    Line | Method
->>  102 | doCall            in org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    178 | $tt__getSequences in org.bbop.apollo.SequenceController
|    198 | doFilter . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter          in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain . .  in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call              in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall . . . . .  in org.apache.shiro.subject.support.SubjectCallable
|     83 | call              in     ''
|    383 | execute . . . . . in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal  in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter . . . .  in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1145 | runWorker         in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run               in java.lang.Thread
2016-01-29 11:50:59,669 [http-bio-8080-exec-5] WARN  apollo.JbrowseController  - File not found: /opt/apollo/honeybee/data//tracks.conf
| Error java.lang.NullPointerException: Cannot get property 'uniqueName' on null object
| Error 	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57)
| Error 	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:168)
| Error 	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
| Error 	at org.bbop.apollo.Gff3HandlerService._do_extractAttributes(Gff3HandlerService.groovy:298)
| Error 	at org.bbop.apollo.Gff3HandlerService.this$2$_do_extractAttributes(Gff3HandlerService.groovy)
| Error 	at sun.reflect.GeneratedMethodAccessor891.invoke(Unknown Source)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
| Error 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invok
```

### CODE REVIEW

**Comment by cmdcolin** [comment]
That count thing is #814 which still has tests failing. I don't think that error is unrelated to optimize...

**Comment by nathandunn** [comment]
I'll take another look.

**Comment by nathandunn** [comment]
The second error is what you get when you export a pseudogene (about the uniqueName)

**Comment by nathandunn** [comment]
@cmdcolin  The second error is what you get when you export a pseudogene (about the uniqueName)

```
2016-01-29 11:50:59,669 [http-bio-8080-exec-5] WARN  apollo.JbrowseController  - File not found: /opt/apollo/honeybee/data//tracks.conf
| Error java.lang.NullPointerException: Cannot get property 'uniqueName' on null object
| Error     at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57)
| Error     at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:168)
| Error     at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
| Error     at org.bbop.apollo.Gff3HandlerService._do_extractAttributes(Gff3HandlerService.groovy:298)
| Error     at org.bbop.apollo.Gff3HandlerService.this$2$_do_extractAttributes(Gff3HandlerService.groovy)
| Error     at sun.reflect.GeneratedMethodAccessor891.invoke(Unknown Source)
```

Just re-issue a new pull request.  Sorry for pre-merging it.

**Pull request merged**
