### PR TITLE
fixes #881 - use correct is statement

### LINKED ISSUE #881: Weird bug renders UI temporarily inoperable
I don't have a way to reproduce this (yet), I've seen it once or twice and the only times I've seen it I've been in such a rush to get it working for said user that I can't spend enough time investigating. I've finally captured some of a stack trace for this:

```
webapollo2_1 | org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [findAnnotationsForSequence] of con
troller [org.bbop.apollo.AnnotatorController]  caused exception: Runtime error executing action
webapollo2_1 |  at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
webapollo2_1 |  at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
webapollo2_1 |  at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
webapollo2_1 |  at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
webapollo2_1 |  at java.lang.Thread.run(Thread.java:745)
webapollo2_1 | Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
webapollo2_1 |  ... 12 more
webapollo2_1 | Caused by: java.lang.reflect.InvocationTargetException
webapollo2_1 |  ... 12 more
webapollo2_1 | Caused by: java.lang.StackOverflowError
webapollo2_1 |  at java.lang.Exception.<init>(Exception.java:54)
webapollo2_1 |  at java.lang.RuntimeException.<init>(RuntimeException.java:51)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 | 2016-02-15 20:40:31,254 [http-bio-8080-exec-423] ERROR errors.GrailsExceptionResolver  - StackOverflowError occurred when processing request: [GET] /apollo/annotator/findAnnotationsForSequence/
webapollo2_1 | Stacktrace follows:
webapollo2_1 | org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [findAnnotationsForSequence] of controller [org.bbop.apollo.AnnotatorController]  caused exception: Runtime error executing action
webapollo2_1 |  at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
webapollo2_1 |  at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
webapollo2_1 |  at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
webapollo2_1 |  at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
webapollo2_1 |  at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
webapollo2_1 |  at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
webapollo2_1 |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
webapollo2_1 |  at java.lang.Thread.run(Thread.java:745)
webapollo2_1 | Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
webapollo2_1 |  ... 12 more
webapollo2_1 | Caused by: java.lang.reflect.InvocationTargetException
webapollo2_1 |  ... 12 more
webapollo2_1 | Caused by: java.lang.StackOverflowError
webapollo2_1 |  at java.lang.Exception.<init>(Exception.java:54)
webapollo2_1 |  at java.lang.RuntimeException.<init>(RuntimeException.java:51)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
webapollo2_1 |  at org.bbop.apollo.DBXref.equals(DBXref.groovy:24)
```

What happens is the URL 

```
https://fqdn/apollo/annotator/findAnnotationsForSequence/?sequenceName=&request=1&offset=0&max=20&annotationName=&type=&user=&order=asc&sort=length
```

is accessed and it generates an HTML response. The UI comes back with a double issuance of this error, and a grey-out pane over the top most error, resulting in having to delete the grey-out to actually click OK, after which the UI works *perfectly* again, and future requests to that URL behave normally. It's ... confounding.

error

For clarification, I'm not requesting anyone "fix" this bug given that I can't even reproduce it, just documenting for the future.

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes #881  . . . bad equality is a mine-field waiting to be explored.  

@cmdcolin   Can you take a quick look at this to double-check.   Surprised that this is the only way we've see this show up.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Hmm. I guess this is a groovy specific where the equals function got triggered recursively there

Could we just use http://docs.groovy-lang.org/latest/html/gapi/groovy/transform/EqualsAndHashCode.html in most cases?

**Comment by nathandunn** [comment]
You can use that in many cases, but most of the classes we use fairly specific fields, which this does support.   In this case I just fixed two lines of it, which didn't need to look at the fields. 

I'll create another issue to do it with the annotations in 2.0.3 as we have time, since it will be quite a bit more involved.

**Comment by cmdcolin** [comment]
Ok. I just think using the built in equals and hash is probably better for most cases.

At least one weird thing that remains here is that grails-app/domain/org/bbop/apollo/OrganismProperty.groovy checks for whether "other" is an Organism. Should be OrganismProperty most likely.

**Comment by cmdcolin** [comment]
>I'll create another issue to do it with the annotations in 2.0.3 as we have time, since it will be quite a bit more involved.

sounds good :)

**Comment by nathandunn** [comment]
Yeah, that was an inherited line, which is why its important to get that other fix in.

**Pull request merged**
