### PR TITLE
fixed for the BAM canvas

### LINKED ISSUE #1868: BAM support
Hia,

I was trying out the new master (with the new JBrowse) and when clicking on "create new annotation" -> "gene" on a BAM feature

I get: 
Error Performing Operation
Cannot get property 'name' on null object

converting into other types works.

but the feature technically has a name:
image

tracklist bit:
```
      {
         "key" : "Full transcript RNASeq data",
         "label" : "isoseq_all",
         "storeClass" : "JBrowse/Store/SeqFeature/BAM",
         "type" : "JBrowse/View/Track/Alignments2",
         "urlTemplate" : "bam/TTRE_all_isoseq.bam",
        "default_biotype" : "gene"
      },
```

error log:
```
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.FeatureService  - CV Term not known match for CV sequence
2018-03-07 11:36:28,712 [Actor Thread 9] WARN  apollo.FeatureService  - Feature type not set for [cv:[name:sequence], name:match]
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - CAUGHT ERROR through websocket call: java.lang.reflect.InvocationTargetException
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - THROWING PARENT ERROR instead through reflection: java.lang.NullPointerException: Cannot get property 'name' on null object
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - exception java.lang.NullPointerException: Cannot get property 'name' on null object
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - exception message Cannot get property 'name' on null object
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - username admin@local.host
2018-03-07 11:36:28,712 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - error destination message: /topic/AnnotationNotification/user/admin@local.host
``` 
console log:
```
selection selection
AnnotTrack.js:1152 process: 1
AnnotTrack.js:5981 connected and sending notifications
AnnotTrack.js:5983 sent notification message
AnnotTrack.js:5981 connected and sending notifications
AnnotTrack.js:5983 sent notification message
```

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1868

### CODE REVIEW

**Comment by nathandunn** [comment]
Basically, when it doesn't recognize the biotype it assumes mRNA.

**Comment by nathandunn** [comment]
@epaule this is ready to test.

**Comment by epaule** [comment]
Can't get the JBrowse to work properly on your branch. Will give a shout later when it works.

**Comment by epaule** [comment]
looking good :+1:

**Comment by nathandunn** [comment]
So it ultimately worked or do I need to fix something? 

Nathan

**Comment by epaule** [comment]
did ultimately work. and put in the gene structures properly from the BAM tracks.

**Pull request merged**
