### PR TITLE
Fix session logout code

### PR DESCRIPTION
**Pull request by nathandunn**
This handles the error @monicacecilia  found in #493 and also handles loadGroups and loadUsers without a username (like when logged out) with a 401 instead of a 500.  

@deepakunni3  Can you look at this when you have some time.   You should confirm that when you log out of one screen, that it logs out of ALL of them.

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn Bug still persists. 

If I have Apollo open on two tabs, logging out in one tab doesn't trigger a logout in the other tab.

**Comment by nathandunn** [comment]
Okay.  I didn't test tabs, just separate browser windows.  I'd see if I can't get it to work for tabs as well. 

- [ ] get functionality to work with tabs

**Comment by deepakunni3** [comment]
Tested in separate browser windows.
Logging out from one window doesn't trigger a logout from the other window.

Browsers tested: Google Chrome, Safari

**Comment by monicacecilia** [comment]
Ha, it did yesterday when I tried separate browsers....

**Comment by nathandunn** [comment]
@deepakunni3  I tested the following:

Given:
- login on safari
- login on chrome with two windows (both cache disabled)

When:
- I logout on safari

then: 
- safari logs out and both chrome windows log out . . with notification

when: 
- I log back in to all windows
- I logout of a chrome window

then:
- safari logs out with notification, and one chrome provides notification, and one does not.  

Sometimes we get additional alerts, but not too often.   More importantly EVERY window is logged out.

**Comment by nathandunn** [comment]
@deepakunni3  Ready to review (make sure to clean your browse network caches).    This also updates the 2.0.4 to point to the latest, as well.

**Comment by nathandunn** [comment]
@deepakunni3  just realized what time it was there.  I'm going to go ahead and merge this for RC3.

**Comment by monicacecilia** [comment]
👍

**Pull request merged**
