### PR TITLE
added terminator

### LINKED ISSUE #1954: add a terminator
this might be in the TAMU-CPT / erasche codebase

- [ ] add a annotation type from existing source 
- [ ] needs a feature type `--|` or `|--` on the reverse strand

screen shot 2018-11-02 at 1 06 09 pm

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1954 

- [x] get the Terminator details to show up
- [x] remove arrows from terminator
- [x] test: 
     - [x] filtering
     - [x] edits

### CODE REVIEW

**Comment by erasche** [comment]
Yeah was definitely in mine. Also fixes https://github.com/GMOD/Apollo/issues/207 which celebrates 3,5 years of life! Nice to see that finally closed

**Comment by nathandunn** [comment]
from https://github.com/TAMU-CPT/Apollo/commit/0854ff5877830d4d3336c3bc54199b2114a3b635

**Comment by nathandunn** [comment]
@MoffMade this is ready for review

**Comment by nathandunn** [comment]
merging

**Pull request merged**
