### PR TITLE
should handle the specific case brought up in #1214

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes case that handles #1214

### CODE REVIEW

**Comment by nathandunn** [comment]
FYI @childers

**Comment by childers** [comment]
Thanks! I've made a patch and applied it to my modded 2.0.4 branch.
I'll rebuild and see how it looks.

**Comment by childers** [comment]
I get 404 errors when I tried this.  It worked great until I tried to login.

The base URL (when I remove the addStore and addTrack information) does work.

**Comment by nathandunn** [comment]
Regenerated the conditions via emails from @childers :

Works perfectly without the additional tracks:

Step 1 (logged out in full-screen JBrowse): 
http://localhost:8080/apollo/Honeybee/jbrowse/index.html?loc=Group1.1%3A1006232..1199168&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&highlight=
Step 2 (hit login  button):
http://localhost:8080/apollo/3299120051255866588318147700/jbrowse/index.html?loc=Group1.1%3A1006232..1199168&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&highlight=

When adding the additional tracks:
Step 1 (logged out in full-screen JBrowse) (adding everything after addStores): 
http://localhost:8080/apollo/Honeybee/jbrowse/index.html?loc=Group1.1%3A1006232..1199168&tracks=DNA%2CAnnotations%2COfficial%20Gene%20Set%20v3.2&addStores=%7B%22url%22%3A%7B%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemplate%22%3A%22https%3A%2F%2Fgmod-dev.nal.usda.gov%2Fwebapp%2Fmedia%2Fblast%2Ftask%2Fae196338e7044b37a87c07536e9ce6ea%2FTCALIF_genome_v1.0_new_ids.fasta.gff%22%7D%7D&addTracks=%5B%7B%22label%22%3A%22BLAST%2B%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%22store%22%3A%22url%22%2C%22style%22%3A%7B%22renderClassName%22%3A%22gray-center-10pct%22%2C%22subfeatureClasses%22%3A%7B%22match_part%22%3A%22blast-match_part%22%7D%7D%7D%5D&highlight=

Step 2 (hit login) - . . . dropps the "/apollo" line ":
http://localhost:8080/10589737611300445807/jbrowse/index.html?addTracks=[{%22label%22:%22BLAST+%20Results%22,%22category%22:%220.%20Reference%20Assembly%22,%22type%22:%22WebApollo/View/Track/DraggableBLASTFeatures%22,%22store%22:%22url%22,%22style%22:{%22renderClassName%22:%22gray-center-10pct%22,%22subfeatureClasses%22:{%22match_part%22:%22blast-match_part%22}}}]&addStores={%22url%22:{%22type%22:%22JBrowse/Store/SeqFeature/GFF3%22,%22urlTemplate%22:%22https://gmod-dev.nal.usda.gov/webapp/media/blast/task/ae196338e7044b37a87c07536e9ce6ea/TCALIF_genome_v1.0_new_ids.fasta.gff%22}}&loc=Group1.1:1006232..1199168&tracks=DNA,Annotations,Official%20Gene%20Set%20v3.2&highlight=


The problem seems to be in the JBrowse controller:

                redirect(uri:  "/${clientToken}/jbrowse/index.html?${paramList.join('&')}")

which seems to get confused.

**Comment by nathandunn** [comment]
@childers  I **think** I fixed it with https://github.com/GMOD/Apollo/pull/1216/commits/14299e7727e539e2102e168704e7e473696b0bd9  

It was a weird one.  Please retest when you have a moment.

**Comment by childers** [comment]
When do I not find weird issues?  I'm rebuilding it now, and testing... It looks like it is trying to work, as the organism and scaffold are now correct in the panel-view. The other sections are blank, including the browser and tracks panels. I can't be sure about the annotation panel since there were no annotations and the other panels seem to be rendering ok.


```shell
Broken pipe. Stacktrace follows:
java.io.IOException: Broken pipe
        at org.bbop.apollo.JbrowseController.passthrough(JbrowseController.groovy:517)
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2016-09-15 17:45:13,017 [http-nio-8080-exec-14] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [GET] /apollo/Cimex%20lectularius/jbrowse/plugins/WebApollo/img/loading.gif
getOutputStream() has already been called for this response. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: getOutputStream() has already been called for this response
        at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
        at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: getOutputStream() has already been called for this response
        at java.io.FilterWriter.flush(FilterWriter.java:100)
        ... 12 more
2016-09-15 17:45:59,542 [http-nio-8080-exec-21] WARN  apollo.PreferenceService  - Multiple preferences found: 388
```

**Comment by nathandunn** [comment]
Usually that just means that something is being reset.  

The track panel is blank because the browser is blank.   I’m curious if you are seeing any errors in the console or 404’s in the network tab.  

Nathan

**Pull request merged**
