### PR TITLE
Add annotation count to the refseq panel

### PR DESCRIPTION
**Pull request by cmdcolin**
Here is an example of adding annotation counts to the refseq panel

Address #803 

This doesn't have sorting on the annotation column yet, but I just wanted to put this pull request in place for review

screenshot-localhost 8080 2016-01-21 15-03-21 png resize

### CODE REVIEW

**Comment by nathandunn** [comment]
Can you share this with @deepakunni3 on this?  I'd initially assigned #814 to him.   Overall it is the right direction, but you should get the counts out with a single join query after you return them instead of iterating, which is very expensive if you have a lot of features.  

Sorting by annotation counts is not necessary, though at some point a filter might make sense.

**Comment by nathandunn** [comment]
Note that this is one of those that can slip if need be.

**Comment by cmdcolin** [comment]
I changed it to a sql "count" with a group by statement so I think it should be faster. To get the sequences with count of 0 i had to do a separate query and merge them but that isn't expensive.

**Comment by nathandunn** [comment]
This worked well for Honeybee (nice sorting) .. I'm getting this error though for other organisms:

```
ks.conf
2016-01-29 11:35:35,220 [http-bio-8080-exec-10] WARN  apollo.JbrowseController  - File not found: /opt/apollo/Verticillium_dahliaejr/names/root.json
| Error 2016-01-29 11:35:35,475 [http-bio-8080-exec-10] ERROR errors.GrailsExceptionResolver  - IndexOutOfBoundsException occurred when processing request: [POST] /apollo/sequence/getSequences/ - parameters:
sort: count
asc: false
start: 0
name: 
length: 20
toIndex = 21. Stacktrace follows:
Message: toIndex = 21
    Line | Method
->>  962 | subListRangeCheck in java.util.ArrayList
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    954 | subList           in     ''
|    195 | $tt__getSequences in org.bbop.apollo.SequenceController
|    198 | doFilter          in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . .  in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain      in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call . . . . . .  in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall            in org.apache.shiro.subject.support.SubjectCallable

```

**Comment by cmdcolin** [comment]
This was mixed up with some unrelated changes but I did a reset so that it only includes relevant changes now.

**Comment by nathandunn** [comment]
I think you might have over-trimmed:

screen shot 2016-01-29 at 3 00 57 pm

**Comment by cmdcolin** [comment]
No annotation count column? Might have been similar to the gff one. I am re-adding that now

**Comment by cmdcolin** [comment]
Should be re-added ea1ba28

**Comment by nathandunn** [comment]
Looks good.   I haven't checked it on richly annotated data yet, but I don't think it will be a problem.

**Pull request merged**
