### PR TITLE
Jbrowse plugin git methods and test fixes

### PR DESCRIPTION
**Pull request by luke-c-sargent**
This PR is an effort at fixing the issues with bowerless git plugin acquisition; notable changes:

apollo:
the function `check_rest_api` has been slightly modified to address a testing issue; the prior conditional checked for the existence of a json file that is already included in the repo; however, the rest-api-docs do not get generated on the first run of `apollo test`. changing the check to the `target` directory ensures this runs initially -- though it might be prudent to remove the check altogether and just compile the rest-api-docs to avoid the whole issue. 
also, the command `$grails_executable rest-api-doc` raised an error that asks the user to select the package they want to install, which in actuality is 'doc' -- hence the change to `$grails_executable doc`

build.gradle:
an extra variable, defaultGitMethod, has been added and set to "shell." this variable controls whether git is run via NPM (requiring any git packages acquired to have a package.json file in the base directory) or via command. an extra nicety of the command approach is that it uses https in lieu of ssh, so no key configuration is required. should the user wish to use npm, they can set the defaultGitMethod variable by including it in their apollo-config 'plugins' section.
to accomplish the command git method, an existing (presumably in progress) commented out function was uncommented-out, and modified slightly (to run ` tasks.installJBrowseScript.execute()` which resolved some errors).

add_features_from_gff3_to_annotations.pl & add_transcripts_from_gff3_to_annotations.pl:
changed the path these scripts look for dependencies in 

relevant issue: #1752

### CODE REVIEW

**Comment by nathandunn** [comment]
Also fixes #1756

**Comment by deepakunni3** [comment]
@luke-c-sargent The defaultGitMethod option will be very useful 👍  

But I am still running into the `ENOPACKAGEJSON` thrown by npm for a plugin that doesn't have a `package.json`:

Here is the config of the plugin where it fails:
```
       FeatureSequence {
           // repository doesn't have package.json
           git = "https://github.com/tsaari88/FeatureSequence.git"
           branch = "master"
           defaultGitMethod = "shell"
       }   
```

Did I miss something while testing?

**Comment by luke-c-sargent** [comment]
defaultGitMethod is for 'global' scope -- so you can [set the default in build.gradle](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L39), and let users specify the method themselves with gitMethod in the plugin. In apollo.config plugin specification, the term is gitMethod (following my observed trend of camel case naming) so you'd want to use
```
       FeatureSequence {
           // repository doesn't have package.json
           git = "https://github.com/tsaari88/FeatureSequence.git"
           branch = "master"
           gitMethod = "shell"
       }
```
though in the PR i submitted the defaultGitMethod is set to "shell" in the `ext` variable group, and so you should be able to omit the method if you just want shell:
```
       FeatureSequence {
           // repository doesn't have package.json
           git = "https://github.com/tsaari88/FeatureSequence.git"
           branch = "master"
       }
```
[this line](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L199):
```
def gitMethod = plugin.value.gitMethod ? plugin.value.gitMethod : defaultGitMethod
```
should check the supplied value, find none, and populate the defaultGitMethod 'shell,' so unless default method is set to NPM, i am not entirely sure why this is cropping up, and will test it. there should be some print statements that say what method it is using and so on, so if you run into the problem again i'd be curious to see what all that says.

rough logic synopsis:
[if plugin tag is git](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L179):
  - [check if plugin already exists](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L181)
  - if so, 
      - do whatever logic existed before if the plugin already exists.
  - [if not](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L196),
      - [check if gitMethod has been supplied; if not, use defaultGitMethod](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L199)
      - send this method to [a general cloneRepo function](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L250) that determines how to execute the method based on a switch statement
```

**Comment by deepakunni3** [comment]
Ah okay. So its `gitMethod`. Got it.

Here is the logs that I see: https://gist.github.com/deepakunni3/e4cb35e5070803957b15170fdd835363 followed by the `ENOPACKAGEJSON` error.

**Comment by luke-c-sargent** [comment]
hmm i don't see any output from 
```
println "Cloning ${url} via ${method}"
```
everything seems to go straight to npm, which shouldn't happen in the PR without the above executing -- repository cloning requests [get routed through cloneRepo](https://github.com/luke-c-sargent/Apollo/blob/6270d05b9cf96b6c7040a2fd10f43f7512af99a0/build.gradle#L250) before going to implementation-specific functions

**Comment by deepakunni3** [comment]
@luke-c-sargent I did a fresh clone of your Apollo repository and now it works 👍 
Sorry about that. Not sure what was going on.

@nathandunn Did you want to take a look at this as well?

**Pull request merged**
