### PR TITLE
#815 - removing schema fixes for mysql migration #794

### PR DESCRIPTION
**Pull request by nathandunn**
Fix for #794  . . . was not updating mysql databases correctly.

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   Can you review / test this when you have a moment?  Thanks.

**Comment by nathandunn** [comment]
i tested it on both MySQL and PostgreSQL.

**Comment by nathandunn** [comment]
Testing procedure: go from 2.0.0 to this branch and see that the schema had been updated (on MySQL).

**Comment by cmdcolin** [comment]
Good catch on the "schemaName: public" . If it works on mysql and postgres now... then that sounds good

**Pull request merged**
