### PR TITLE
sped up features by not creating full JSON

### PR DESCRIPTION
**Pull request by nathandunn**
this will handle #1147  . . . went from 1.5 seconds for a large set of exons to 47 ms

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3   Can you take a look at this when you have a chance?  Thanks.

**Comment by deepakunni3** [comment]
@nathandunn Tested with a transcript with many exons and information editor loaded up without delay.

**Comment by nathandunn** [comment]
Thanks.  That is good to here. 

Did it load the Notes as an attribute or did it do it correctly?   If so, we can close it (but please send me your test script / data either here or off-line).   It could be that we simply need to improve the doc to indicate how sample GFF3 might need to be annotated for that function.

**Comment by nathandunn** [comment]
@deepakunni3   I thought you were commenting on another issue.  Please ignore my previous comment.   Thanks for testing.

**Comment by deepakunni3** [comment]
@nathandunn yes, I was confused. I guess you were referring to issue 1146.

**Comment by nathandunn** [comment]
Yeah, that was the one I was thinking of . .  sorry about that.

**Comment by deepakunni3** [comment]
no worries :)

**Pull request merged**
