### PR TITLE
Fix full screen 1195

### PR DESCRIPTION
**Pull request by nathandunn**
Handles #1195.   

@deepakunni3  Can you review this when you have a moment.  Thanks.

### CODE REVIEW

**Comment by nathandunn** [comment]
I should mention that this does a few things WRT to #1195:

- fixes tracklist viewing inconsistency
- fixes problem going back and forth between full-screen view and annotator view as the client_token was duplicated (same problem as above actually) because loadLink was preserving otherwise good parameters
- fixes problem with going from a public genome to a private genome with different permissions
- fixes a lot of duplicate preferences being created, both explicitly, but also by minimizing unnecessary calls (obviously much more to do here) in GroupPanel and UserPanel
- moved printlns to log.X calls

**Comment by deepakunni3** [comment]
@nathandunn Ran into this error immediately after login:

screen shot 2016-08-08 at 4 38 15 pm

Its because at line 57,
````
log.warn "Organism ${organism.commonName} is not viewable by this user so viewing ${availableOrganisms.first().commonName} instead."
````

`organism.commonName` is trying to access a null organism.

**Comment by nathandunn** [comment]
Doh . . K . . I’ll get that fixed.

**Comment by nathandunn** [comment]
@deepakunni3  I submitted a fix.  I'll try to keep testing as well.

**Comment by deepakunni3** [comment]
Upon login as a user, if I select 'Show JBrowse Track Selector' from the Annotator Panel then the track selector shows up on the left hand side. Then if I deselect 'Show JBrowse Track Selector', go to 'Fullscreen view' and come back to 'Annotator Panel', everything loads perfectly.

If I again select 'Show JBrowse Track Selector' from Annotator Panel, the track selector doesn't show up anymore.

**Comment by nathandunn** [comment]
@deepakunni3  Okay.  I'll take a look.

**Comment by nathandunn** [comment]
@deepakunni3  This should be fixed now.  I tested in a few different scenarios and it seems to work.

**Comment by deepakunni3** [comment]
Tested following:
* tracklist viewing consistency
* going back and forth between full-screen view and annotator view
* going from a public genome to a private genome with different permissions

Looks good 👍

**Pull request merged**
