### PR TITLE
Update user object to support non-email usernames

### PR DESCRIPTION
**Pull request by nathandunn**
FYI @childers  and @deepakunni3  to review.

### CODE REVIEW

**Comment by nathandunn** [comment]
Related to #939 . . . adding email to username.

**Comment by deepakunni3** [comment]
Just tested this PR.

While adding a user (the first admin user or any subsequently created user, via the User Panel), email is still mandatory.
In the user panel, after adding a user with a username different from the email, the panel still shows the user email value in the username text box.
In the Annotator report page, users are referred to by user email. (this is probably related to the one mentioned above where user email replaces username).

**Comment by nathandunn** [comment]
- [ ] also need to retest register user (just uses email right now, maybe good enough)

**Comment by nathandunn** [comment]
I think we are going with plan B on this.  Removing the constraint and issuing warnings instead.

**Pull request closed without merging**
