### PR TITLE
java 8 upgrade - do not merge

### LINKED ISSUE #1311: upgrade to Java 8
not sure when this will happen, but wanted to have this in here either way. 

This looks to be stable with better Java 8 and JsInterop support: http://www.luigibifulco.it/blog/en/blog/gwt-2-8-0-jsinterop

I think the additional things to wait for are support from gwtboostrap3 (which apparently builds okay with it with minor modifications), maven integration with gradle (which already wraps ant) and time.   Not high priority.

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes #1311

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  I'm going to say that this is ready.   No rush on testing.   Not sure what the integration test issues are, but I feel confident that they are issues with travis and not the code having run the same tests myself.

**Comment by deepakunni3** [comment]
@nathandunn Sure, I'll test it out as well.

**Comment by deepakunni3** [comment]
It looks like the build is timing out on Travis. Perhaps clear cache might help?

**Comment by nathandunn** [comment]
Tried it multiple times.  No luck.  We'll need a better long term solution somehow. 

Nathan

**Comment by nathandunn** [comment]
I'll take a further look at these travis commands and see:

https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

My guess is that there is not enough memory being allocated for the build (which is why it becomes so slow). 

Something like this ```before_install: echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=512m'" > ~/.mavenrc``` except for use JAVA_OPTS or GRAILS_OPTS should work. 


http://stackoverflow.com/questions/23322984/how-to-fix-maven-permgen-out-of-memory-error-on-travis-ci/33327697#33327697

Also, changing to the sudo: required (or better yet 'trusty') mode might give us more memory:

https://docs.travis-ci.com/user/ci-environment/

**Comment by deepakunni3** [comment]
@nathandunn Would it make sense to add a task to check if the current Java is JDK8? 

Right now the build errors with the following output:
```

BUILD SUCCESSFUL

Total time: 1 mins 21.124 secs

| Compiling 7 source files
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] Invalid commandline usage for javac.
  [groovyc] javac: invalid source release: 1.8
  [groovyc] Usage: javac <options> <source files>
  [groovyc] use -help for a list of possible options
  [groovyc] 
  [groovyc] 
| Compiling 7 source files.
| Error Compilation error: startup failed:
Invalid commandline usage for javac.
javac: invalid source release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options


1 error
```

**Comment by nathandunn** [comment]
Good point.  I'll work on this and let you know. 

Nathan

**Comment by deepakunni3** [comment]
Tested a local run, deploy and release.
Didn't run into any issues.

**Comment by nathandunn** [comment]
- [ ] check for javac 8 
- [ ] update instance-type settings 
- [ ] update memory settings 
- [ ] update "time" settings?

**Comment by nathandunn** [comment]
- [ ] run [locally to test](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)

**Comment by nathandunn** [comment]
Creating another PR for this.

**Pull request closed without merging**
