### PR TITLE
Fix for 1156

### PR DESCRIPTION
**Pull request by nathandunn**
This will handle #1156. 

@childers Can you review this one?

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn Can confirm that after browsing in public mode, triggering a login via 'Show Annotator Panel' ends up with the same region being displayed post successful login.

Waiting on @childers for feedback.

**Comment by nathandunn** [comment]
@childers it's in main line so you can let me know if it works for the blast stuff next week.

**Comment by childers** [comment]
@deepakunni3 @nathandunn 
It was able to go from JBrowse mode to the apollo mode and keep the track (yay!) but it went to a different scaffold than what was being viewed before logging in.  This is not vanilla master, but your fix_longer_links branch pulling merging master into it.  Is that branch folded into master already?

**Comment by childers** [comment]
I've continued to test this and on three other occasions, switching to the new interface via the 'Show Annotator Panel' displayed a different scaffold two times.

This shouldn't be caching, as I built it as apollo-2.0.4-SNAPSHOT.war, and BLAST is pointing to this new Apollo instance.

**Comment by childers** [comment]
Looking at the dev console, I think it is passing the right information, but I'm not sure why it isn't directing the browser to load the proper scaffold. The HSP is on scaffold_173, and going form the BLAST output to Jbrowse/Apollo-classic mode works fine. When I click the button it displays scaffold_1022. Check out the image for more information.

apollo2 0 4-incorrect_redirect

**Comment by nathandunn** [comment]
@childers  Yes. 

> This is not vanilla master, but your fix_longer_links branch pulling merging master into it. Is that branch folded into master already?

**Pull request merged**
