### PR TITLE
Fix documentation related to installation #1317

### PR DESCRIPTION
**Pull request by nathandunn**
Addresses issues in #1317.

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  When you have time can you take a look at this to make sure the text is appropriate?  The link is the readme is only broken because the image does not exist in master yet.

**Comment by nathandunn** [comment]
I also updated the gwt libraries to 2.8.0 (nothing seemed to break).

**Comment by nathandunn** [comment]
Actually I'm getting this silly error on AWS.  I'm going to take another look:

```
:copyApolloPlugin

FAILURE: Build failed with an exception.

* What went wrong:
java.io.IOException: Permission denied
> Permission denied

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

**Comment by nathandunn** [comment]
Fails before it copies over the stuff from jbrowse-download to web-app/jbrowse

But if I run the original script (./gradlew installJBrowse) it is just fine, but it chokes on another dependency.  

Very weird.  

Now it always seems to fail when executing this was:

```
task copyApolloPlugin(dependsOn:installJBrowse,type:Copy){
    println "Copying apollo plugin"
    from("client/apollo")
    into("jbrowse-download/plugins/WebApollo")
}
```

The directory doesn’t exist, so we could remove and add it as well, but it doesn’t really matter for execution of this script.

**Comment by nathandunn** [comment]
@deepakunni3  It is now ready to review.  I confirmed that the install works on Ubuntu 16 LTS from a de novo install.

**Comment by deepakunni3** [comment]
@nathandunn Looks good. 

Also checked that the GWT update doesn't break anything.

**Pull request merged**
