### PR TITLE
Fixes bug where Apollo client interprets 5'UTR and 3'UTR features as exons

### LINKED ISSUE #1308: Apollo client interprets 5'UTR and 3'UTR features as exons
Example:
````
Group1.10	amel_OGSv3.2	gene	588730	594164	0.999995	+	.	ID=GB40820
Group1.10	amel_OGSv3.2	mRNA	588730	594164	0.999995	+	.	ID=GB40820-RA;Parent=GB40820
Group1.10	amel_OGSv3.2	CDS	588730	588910	.	+	0	Parent=GB40820-RA
Group1.10	amel_OGSv3.2	CDS	592527	592678	.	+	2	Parent=GB40820-RA
Group1.10	amel_OGSv3.2	three_prime_UTR	592679	592731	0.999995	+	.	Parent=GB40820-RA
Group1.10	amel_OGSv3.2	three_prime_UTR	593508	594164	0.999995	+	.	Parent=GB40820-RA
Group1.10	amel_OGSv3.2	exon	588730	588910	0.999995	+	.	Parent=GB40820-RA
Group1.10	amel_OGSv3.2	exon	592527	592731	0.999995	+	.	Parent=GB40820-RA
Group1.10	amel_OGSv3.2	exon	593508	594164	0.999995	+	.	Parent=GB40820-RA
````

The transcript GB40820-RA has two 3'UTRs. 

When you drag-drop a transcript to the Annotations track, Apollo client interprets `three_prime_UTR` as `exon` while preparing the JSONObject. 

This affects the way the server interprets the incoming JSONObject while adding a transcript.

JSONObject sent to the server:
````
{
  "operation": "add_transcript",
  "username": "deepak.unni3@gmail.com",
  "features": [
    {
      "location": {
        "fmin": 588729,
        "strand": 1,
        "fmax": 594164
      },
      "name": "GB40820-RA",
      "children": [
        {
          "location": {
            "fmin": 592678,
            "strand": 1,
            "fmax": 592731
          },
          "type": {
            "name": "exon",
            "cv": {
              "name": "sequence"
            }
          }
        },
        {
          "location": {
            "fmin": 593507,
            "strand": 1,
            "fmax": 594164
          },
          "type": {
            "name": "exon",
            "cv": {
              "name": "sequence"
            }
          }
        },
        {
          "location": {
            "fmin": 588729,
            "strand": 1,
            "fmax": 588910
          },
          "type": {
            "name": "exon",
            "cv": {
              "name": "sequence"
            }
          }
        },
        {
          "location": {
            "fmin": 592526,
            "strand": 1,
            "fmax": 592731
          },
          "type": {
            "name": "exon",
            "cv": {
              "name": "sequence"
            }
          }
        },
        {
          "location": {
            "fmin": 593507,
            "strand": 1,
            "fmax": 594164
          },
          "type": {
            "name": "exon",
            "cv": {
              "name": "sequence"
            }
          }
        },
        {
          "location": {
            "fmin": 588729,
            "strand": 1,
            "fmax": 592678
          },
          "type": {
            "name": "CDS",
            "cv": {
              "name": "sequence"
            }
          }
        }
      ],
      "type": {
        "name": "mRNA",
        "cv": {
          "name": "sequence"
        }
      }
    }
  ],
  "track": "Group1.10",
  "clientToken": "3989174224901116671559624297"
}
````

There are 5 exons as child features to the transcript when in reality it should be three exons and two 3'UTRs.

### PR DESCRIPTION
**Pull request by deepakunni3**
Fixes #1308 

The issue was in `JSONUtils.createApolloFeature()` where all UTRs were explicitly being converted to exons.

### CODE REVIEW

**Comment by nathandunn** [comment]
Bizarre.  The code is RIGHT there added explicitly for this use-case.   Looks good.

**Comment by deepakunni3** [comment]
Yes, it was commented out at some point (Definitely before 2014).

**Comment by nathandunn** [comment]
I was actually added as commented out.  Weird huh. 

Nathan

**Comment by deepakunni3** [comment]
Yeah, but was a *very* quick fix :)

**Pull request merged**
