### PR TITLE
Restore 'Pin to top' and 'Delete track' ability for all HTMLFeatures

### LINKED ISSUE #1632: Pin to top option should also be enabled for DraggableHTMLFeatures tracks
We have lost the ability to 'Pin to top' some tracks from the evidence panel. If the track type is DraggableHTMLFeatures, the option is no longer available. However, the option is still available for CanvasFeatures. 
These are the available options in the menu right now: 
screen shot 2017-06-01 at 11 28 13 am

@deepakunni3 thinks the menu rendering code for DraggableHTMLFeatures is suspect.

### PR DESCRIPTION
**Pull request by deepakunni3**
Fixes #1632.

### CODE REVIEW

**Comment by monicacecilia** [comment]
Thanks @deepakunni3!
Tested and works?

**Comment by nathandunn** [comment]
@monicacecilia  I'm testing it now.  I'll merge it in.  Do you want me to put it up on staging if so?

**Comment by nathandunn** [comment]
@deepakunni3    Looks great.

**Comment by monicacecilia** [comment]
Awesomeness. That was fast! Thank you!

**Pull request merged**
