### PR TITLE
Select/unselect all tracks within a category

### LINKED ISSUE #1724: Add select-all / unselect-all to TrackPanel
It's the same as bhofmei/jbplugin-hierarchicalcheckbox#3, because it is related to both repos.

When I tested on `JBrowse 1.12.3`, it works with this [hierarchical check box plugin](https://github.com/bhofmei/jbplugin-hierarchicalcheckbox) , but when I used the `Apollo 2.0.6` (also with `JBrowse 1.12.3` and it's automatically downloaded by `Apollo`. Plugin installation is by specifying setting in `apollo-config.groovy`), it didn't work (no checkboxes show up).

I simply uncomment the line `console.log("plugin HierarchicalCheckboxPlugin constructor")`; in `main.js` of `hierarchical check box plugin` and it shows in console, so the plugin seems to be loaded, but for some reason it didn't work.

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
This PR aims at adding functionality of selection of all tracks within a category. However, style sheet is not ready now.

fixes #1724

### CODE REVIEW

**Comment by nathandunn** [comment]
Fixes #1724

**Comment by hsiaoyi0504** [comment]
Sorry, I don't notice that you have already starting works on it.....
I update the css, but current checkbox for a category still need to further adjust the position.

**Comment by nathandunn** [comment]
Looks good and worked good.  It looked like you were adding the component twice, so I removed one and there were some other minor fixes.  A little bid of padding was added as well. 

Thanks!

**Comment by hsiaoyi0504** [comment]
Thanks a lot for helping us this !

**Pull request merged**
