### PR TITLE
Variant Annotation

### PR DESCRIPTION
**Pull request by deepakunni3**
@nathandunn This PR is ready for test and review

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  I think there is a single failing integration test related to variants:

https://travis-ci.org/GMOD/Apollo/jobs/386466866#L1272

```
|Running 16 integration tests... 92 of 92
|Running 16 integration tests... 93 of 93
Failure:  |
Add a variant of type SNV(org.bbop.apollo.RequestHandlingServiceIntegrationSpec)
 |
java.lang.NullPointerException: Cannot get property 'bases' on null object
	at org.bbop.apollo.RequestHandlingServiceIntegrationSpec.Add a variant of type SNV(RequestHandlingServiceIntegrationSpec.groovy:4449)
|Running 16 integration tests... 94 of 94
|Running 16 integration tests... 95 of 95
```

**Comment by nathandunn** [comment]
unsure if merging master broke it or not.

**Comment by deepakunni3** [comment]
Yes, I saw that on travis too. But I can't reproduce it locally.

Are you having the same issues locally?

**Comment by nathandunn** [comment]
I haven’t run it locally.  I can take a look at it when I run it. 

Hopefully today.  

Nathan

**Comment by nathandunn** [comment]
@deepakunni3 I'm still getting these errors locally (and a chado error, probably my own doing, though)

```
a round-trip of GFF3 export and import

Executed in 0.292 seconds.

Error parsing JSON

org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error parsing JSON
	at grails.converters.JSON.parse(JSON.java:278)
	at org.bbop.apollo.RequestHandlingServiceIntegrationSpec.a round-trip of GFF3 export and import(RequestHandlingServiceIntegrationSpec.groovy:3708)
Caused by: org.codehaus.groovy.grails.web.json.JSONException: Missing value. at character 0 of 
	at grails.converters.JSON.parse(JSON.java:269)
a round-trip with all feature types

Executed in 1.163 seconds.

Error parsing JSON

org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error parsing JSON
	at grails.converters.JSON.parse(JSON.java:278)
	at org.bbop.apollo.RequestHandlingServiceIntegrationSpec.a round-trip with all feature types(RequestHandlingServiceIntegrationSpec.groovy:3816)
Caused by: org.codehaus.groovy.grails.web.json.JSONException: Missing value. at character 0 of 
	at grails.converters.JSON.parse(JSON.java:269)
```

and

```

Add a variant of type SNV

Executed in 0.037 seconds.

Cannot get property 'bases' on null object

java.lang.NullPointerException: Cannot get property 'bases' on null object
	at org.bbop.apollo.RequestHandlingServiceIntegrationSpec.Add a variant of type SNV(RequestHandlingServiceIntegrationSpec.groovy:4449)
```

**Comment by nathandunn** [comment]
Here is the chado test:

```
Failure:  test CHADO export and re-export(org.bbop.apollo.ChadoHandlerServiceIntegrationSpec)
|  Condition not satisfied:

org.gmod.chado.Feature.findByUniquename(gene1UniqueName) == null
                       |                |                |
                       |                |                false
                       |                123e2403-c00a-4594-be22-bbe114fec917
                       org.gmod.chado.Feature : 79

	at org.bbop.apollo.ChadoHandlerServiceIntegrationSpec.test CHADO export and re-export(ChadoHandlerServiceIntegrationSpec.groovy:348)
| Running 16 integration tests... 18 of 18
```

**Comment by nathandunn** [comment]
Mostly works.  Some minor bugs:
- I created a deletion and an SNV.  It doesn't reflect the Variant Info or Allele info in the in the annotator panel when I add them directly, but it shows up in the popup editor.    For the variant info, maybe its because its not reserved?  Again, I added from the panel with the same result.  We can remove those panels 

- With the allele info, I don't seem to be able to add them at all. 

- Last piece (and it could just be my current tracks, so you might be seeing differently).   If I reload a screen it seems to go back to the start and even "Go to annotation" doesn't seem to work, until I start scrolling.  Again, could just be my tracks.

- We should allow right-click to add for canvas variants (testing with Volvox).

- delete in the panel doesn't seem to reflect within the panel right away.

Tested export, dbxref, phenotype, etc. and it all seemed to work great.





- can it won't "go to annotation"

It

**Comment by nathandunn** [comment]
So, probably / possibly . . . 

- Remove variant info and allele info panels? 
- Add create variant from canvas VCF?

**Comment by deepakunni3** [comment]
@nathandunn I couldn't reproduce the issues with the Variant Info and Allele Info Panels. Not sure why. Lets catch up sometime next week and see whats going on.

Other than that, I have implemented the WebApolloCanvasVariants track.

**Comment by nathandunn** [comment]
Okay.  We’ll reconnect on Monday.  I’ll try retesting before we talk.

**Comment by nathandunn** [comment]
> I created a deletion and an SNV. It doesn't reflect the Variant Info or Allele info in the in the annotator panel when I add them directly, but it shows up in the popup editor. For the variant info, maybe its because its not reserved? Again, I added from the panel with the same result. We can remove those panels.

This is fixed in #3 .  It doesn't update right away (manual annotation to the annotator panel), but I think that might be okay, at least for now. 

> With the allele info, I don't seem to be able to add them at all.

This is fixed.

> Last piece (and it could just be my current tracks, so you might be seeing differently). If I reload a screen it seems to go back to the start and even "Go to annotation" doesn't seem to work, until I start scrolling. Again, could just be my tracks.

This is weird.    It completely forgets the zoom level.  Not sure if I',m just doing something thing silly.

Also, you have to scroll for "Go To Annotation" to work properly.

> We should allow right-click to add for canvas variants (testing with Volvox).

You fixed this.

> delete in the panel doesn't seem to reflect within the panel right away.

Fixed by #3

**Comment by deepakunni3** [comment]
@nathandunn Fixed the issue with the update on the Annotator Panel.

The bug with the 'Go to Annotation' happens but it is not consistently reproducible.
Not sure what is causing it.

**Comment by nathandunn** [comment]
@deepakunni3   I retested against JBrowse 1.12.5 and this branch.  Retesting with master.  I'd be willing to bet that this is a side-effect of JBrowse.  Ill retest against master, but I expect the same outcome.    

I'm going to test against 1.12.2 next and move forward from there.  My guess is that something got fixed between releases, that broke something else, but this will be interesting to see.

**Comment by deepakunni3** [comment]
@nathandunn I feel like this is one of those emotional moments where the PR finally meets its destiny 😉

**Comment by nathandunn** [comment]
@deepakunni3  As it should!

**Pull request merged**
