### PR TITLE
fix 1555 refseq should go to other sequences

### LINKED ISSUE #1555: projection: evidence lookup fails to navigate
this used to work (navigate), but seems to fail now

- [x] navigates to the location properly
- [x] should lookup sequence location as well (chrX:fmin..fmax)
- [x] update name for new assemblage in both JBrowse and Side-panel windows
  - [x] fix bug where doing reverse complement fails (see below)

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes #1555.

### CODE REVIEW

**Comment by nathandunn** [comment]
handling most by handle nav, but productin this error: 


```
AnnotTrack.js:445 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Client.connectCallback (AnnotTrack.js:445)
    at SockJS.onmessage (spring-websocket.js:2669)
    at SockJS.REventTarget.dispatchEvent (spring-websocket.js:84)
    at SockJS._dispatchMessage (spring-websocket.js:1025)
    at SockJS._didMessage (spring-websocket.js:1083)
    at WebSocket.that.ws.onmessage (spring-websocket.js:1215)
```

which is from here: 

```
    var assemblage = JSON.parse(apolloMainPanel.getCurrentAssemblage());
                    var user = JSON.parse(apolloMainPanel.getCurrentUser());
                    assemblage.sequenceList.forEach(function (obj) {
                        client.subscribe("/topic/AnnotationNotification/" + organism.id + "/" + obj.name, dojo.hitch(track, 'annotationNotification'));
                    });
                    //client.subscribe("/topic/AnnotationNotification/" + organism.id + "/" + sequence.id, dojo.hitch(track, 'annotationNotification'));
                    client.subscribe("/topic/AnnotationNotification/user/" + user.email, dojo.hitch(track, 'annotationNotification'));
```

**Comment by nathandunn** [comment]
@deepakunni3  This is also ready for review.

**Comment by nathandunn** [comment]
Fixes #1678

**Comment by deepakunni3** [comment]
If I use the text box and navigate to a different region on the same scaffold (Group.1.1) it works.
If I try to navigate to a different scaffold, say Group1.10:1..100, then it ignores the scaffold name and moves my view to the coordinates specified on the same scaffold that I am viewing currently, i.e. Group1.1.

**Comment by deepakunni3** [comment]
The autocomplete feature in the textbox shows scaffolds that don't exist in the original genome:
screen shot 2017-07-13 at 12 53 04 pm

`Group1.1.013.1` is not a scaffold from the original genome fastsa.

**Comment by nathandunn** [comment]
- [ ]  navigating to different scaffold using the location fails Group1.10:1..100 ends up navigating to the same scaffold

@deepakunni3  WRT to the weird naming, that is just what the name store has and I believe its part of JBrowse (and 2.0.6 / 2.0.7) so I don't think its a bug WRT to 2.1.0.

**Comment by nathandunn** [comment]
I'll fix the scaffold navigation bug

**Comment by nathandunn** [comment]
Note, I tested and couldn't reproduce the internal navigation error.

**Comment by nathandunn** [comment]
Failing with this: 

```
annotator-0.js:28689 Uncaught TypeError: Cannot read property 'isNumber' of null
    at handleNavigationEvent (annotator-0.js:28689)
    at apply_0 (annotator-0.js:1901)
    at entry0 (annotator-0.js:1939)
    at annotator-0.js:1924
    at main.js:852
    at Evented.<anonymous> (lang.js:375)
    at Evented.dispatcher [as on/jbrowse/v1/n/navigate] (aspect.js:101)
    at Function.on.emit (on.js:309)
    at Function.on.emit (on.js:350)
    at Evented.emit (Evented.js:32)
    at Object.publish (topic.js:25)
    at Object.publish (Browser.js:1876)
    at Object.onCoarseMove (Browser.js:2872)
    at Object.advice (aspect.js:114)
    at Object.dispatcher [as onCoarseMove] (aspect.js:94)
    at Object.<anonymous> (lang.js:373)
    at Object.dispatcher [as onCoarseMove] (aspect.js:101)
    at Object.showCoarse (GenomeView.js:1259)
    at Object.centerAtBase (GenomeView.js:1199)
    at Object.setLocation (GenomeView.js:1164)
    at Object.execute (GenomeView.js:926)
    at Object.rubberExecute (GenomeView.js:975)
    at HTMLBodyElement.<anonymous> (lang.js:373)
```

**Comment by nathandunn** [comment]
When searching for name, now getting this error: 

```
Browser.js:1980 TypeError: Cannot read property 'isString_2_g$' of null TypeError: Cannot read property 'isString_2_g$' of null
    at handleNavigationEvent_0_g$ (annotator-0.js:106401:60)
    at apply_0_g$ (annotator-0.js:11523:28)
    at entry0_0_g$ (annotator-0.js:11593:14)
    at annotator-0.js:11559:14
    at http://localhost:8080/apollo/13667239226027935921853084717/jbrowse/plugins/WebApollo/js/main.js:852:35
    at Evented.<anonymous> (http://localhost:8080/apollo/13667239226027935921853084717/jbrowse/src/dojo/_base/lang.js:375:55)
    at Evented.dispatcher [as on/jbrowse/v1/n/navigate] (http://localhost:8080/apollo/13667239226027935921853084717/jbrowse/src/dojo/aspect.js:101:39)
    at Function.on.emit (http://localhost:8080/apollo/13667239226027935921853084717/jbrowse/src/dojo/on.js:309:37)
    at Function.on.emit (http://localhost:8080/apollo/13667239226027935921853084717/jbrowse/src/dojo/on.js:350:29)
```

**Comment by nathandunn** [comment]
- [ ] when searching in the reverse complement it should deliver results in the reverse complement 
- [ ] error when looking up evidence in some cases
- [ ] actually compling (vs. devmode gives the number error)

**Comment by nathandunn** [comment]
The problem with the name lookup is that the code to do the lookup and navigation is actually in Browser.js in navigatieToLocation.   I can update this code to handle it there (if JSON and with "reverse" in the track name), or I can bring the search up, which could be very messy.

**Comment by nathandunn** [comment]
@deepakunni3  This should be working now.  You'll need to repull the branch: projection_v2_server though.

**Comment by deepakunni3** [comment]
@nathandunn Can confirm that I can navigate to other locations on the genome via the coordinate search box 👍

**Comment by nathandunn** [comment]
@deepakunni3  Is it ready to roll, or still testing?

**Comment by deepakunni3** [comment]
@nathandunn Yes, its ready to merge.

**Pull request merged**
