### PR TITLE
fix #1395 added a little navicon that will eventually show the button note - not ready to merge

### LINKED ISSUE #1395: Problem when browsing to multiple tabs when logged in
I currently see a navigation issue in master.

1. I go BLAST-Jbrowse,
2. Log in,
3. Click to enable native tracks
4. Click to close panel
5. Make great annotations
6. Close and go to my next BLAST hit.
7. Click to go to the browser and it is apollo1 style (mostly) there is the modern organism selector, but no chevron to enable the Apollo2 right-side panel.

Here is the URL:
https://myserver.orgnet/apollo/9181426326681843991119596663/jbrowse/index.html?loc=Scaffold66%3A414756..1116791&addTracks=%5B%7B%22label%22%3A%22BLAST%20%20Results%22%2C%22category%22%3A%220.%20Reference%20Assembly%22%2C%22type%22%3A%22WebApollo%2FView%2FTrack%2FDraggableBLASTFeatures%22%2C%22store%22%3A%22url%22%2C%22style%22%3A%7B%22renderClassName%22%3A%22gray-center-10pct%22%2C%22subfeatureClasses%22%3A%7B%22match_part%22%3A%22blast-match_part%22%7D%7D%7D%5D&addStores%3D%7B%22url%22%3A%7B%22type%22%3A%22JBrowse%2FStore%2FSeqFeature%2FGFF3%22%2C%22urlTemplate%22%3A%22https%3A%2F%2Fmyotherserver.orgnet%2Fwebapp%2Fmedia%2Fblast%2Ftask%2F1bfc16f0ffe549619bce4fd12cdf2484%2FAgla_Btl03082013.genome_new_ids.fa.gff%22%7D%7D=&tracks=DNA%2CAnnotations%2CBLAST%20%20Results&highlight=
 
Version: 2.0.6-SNAPSHOT
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_112

apollo2 0 6-logged-in-no-apollo2-features

### PR DESCRIPTION
**Pull request by nathandunn**
this will fix #1395.

### CODE REVIEW

**Comment by nathandunn** [comment]
Moved button to the bar below the chevron, but unsure if I should keep the old one.  

screen shot 2016-12-23 at 9 37 15 am

**Comment by nathandunn** [comment]
@childers  / @mpoelchau I think this will work for the #1395 case, but I'm unsure if the UI is correct.   I can merge issues with #1397 but I think some other weird stuff is going on.

**Comment by childers** [comment]
I think #1395 and #1397 are probably different issues, and this should resolve #1395, but I'm not sure how this would fix #1397.  Will this help to force a refresh of the tracks list, or trigger a rebuild based on what's in the native track list?

**Comment by nathandunn** [comment]
It won't help #1397 at all.   I would say test this.  The only thing I am unsure about is removing the button "JBrowse native track selector" from the Track Panel, but maybe having them both is okay, but my sense is that it is kind of cluttery where it is.  

If there is a [better icon](http://fontawesome.io/icons/) let me know.

**Comment by childers** [comment]
( = I like looking through their icons.

**Pull request merged**
