### PR TITLE
Extending GFF3 export functionality to support features on an assemblage

### PR DESCRIPTION
**Pull request by deepakunni3**
Extending methods in `Gff3HandlerService` to export GFF3 from projected JSON features.

### CODE REVIEW

**Comment by nathandunn** [comment]
Test worked manually and the regression tests.

**Comment by deepakunni3** [comment]
no! :(

**Comment by deepakunni3** [comment]
I wasn't done. There were few TODOs in there that I had to address.

**Comment by nathandunn** [comment]
oh shoot, I can revert.

**Comment by deepakunni3** [comment]
Yes, that would be better than making another PR with the new stuffs.

**Pull request merged**
