### PR TITLE
Fix import script to handle sequence alterations and read_through_stop_codons

### LINKED ISSUE #1514: import script should import sequence alterations and read_through_stop_codons
```add_transcripts_from_gff3_to_annotations.pl``` should:

- [ ] have an option to import Sequence Alterations from GFF's. 
- [ ] have an option to capture read_through_stop_codons

FYI @deepakunni3  @monicacecilia  @mpoelchau

### PR DESCRIPTION
**Pull request by deepakunni3**
Fixes #1514

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn Ready for review.

The test `RequestHandlingServiceIntegrationSpec::"a round-trip with all feature types"()` fails due to some inconsistencies in the way feature relationships are handled. This is not reproducible in the live instance, so perhaps has something to do with the way Grails is handling the transactions while running tests.

**Comment by nathandunn** [comment]
So this is what happens when it does work, since it does a depth-first search (I was wrong about only deleting the grand-parent stuff):

```
Deleting of type: Gene with name: GB40701-RA
Deleting of type: MRNA with name: GB40701-RA-00001
Deleting of type: CDS with name: bc49fbaf-4c5f-4887-bb88-c8edfb66182d
adding relationships to remove CDS bc49fbaf-4c5f-4887-bb88-c8edfb66182d -  stop_codon_read_through bc49fbaf-4c5f-4887-bb88-c8edfb66182d-stop_codon_read_through
removing: stop_codon_read_through  bc49fbaf-4c5f-4887-bb88-c8edfb66182d-stop_codon_read_through
removing relationshp: null 
saving parent feature as not pruned: CDS
```

When it doesn't work (in the test), it never adds the stop_codon_read_through relationship.  My *guess* is that it is because we run the sequence alteration code that re-calculates the CDS somehow, or the relationship was never set properly in the first place.    Will continue to dig in.

**Comment by nathandunn** [comment]
I confirmed that if you request the stop codon read-through after you do a sequence alteration insertion you get this:

         requestHandlingService.addSequenceAlteration(JSON.parse(addInsertionString) as JSONObject)
        scrt = cdsService.getStopCodonReadThrough(cds).first()
        assert scrt!=null

getStopCodonReadThrough(cds) returns an empty list (and fails).

**Comment by nathandunn** [comment]
CDS cds = transcriptService.getCDS(mrna)
        println "CDS A: ${cds.uniqueName} ${cds.parentFeatureRelationships.size()}"
        // uniqueId   1 

        requestHandlingService.addSequenceAlteration(JSON.parse(addInsertionString) as JSONObject)

        println "CDS B: ${cds.uniqueName} ${cds.parentFeatureRelationships.size()}"
        // uniqueId   0  !!

So adding sequence alteration seems to remove the stop codon readthrough. 

Instead of inserting a sequence alteration I do the default behavior:

             featureService.setLongestORF(mrna,false)

I get the same result.  However, if I set the SCRT to true:

             featureService.setLongestORF(mrna,true)

it doesn't remove the stop codon read through relationship on the CDS.

**Comment by nathandunn** [comment]
This code still breaks:

```
diff --git a/grails-app/services/org/bbop/apollo/FeatureRelationshipService.groovy b/grails-app/services/org/bbop/apollo/FeatureRelationshipService.groovy
index 6eb855f..7529f52 100644
--- a/grails-app/services/org/bbop/apollo/FeatureRelationshipService.groovy
+++ b/grails-app/services/org/bbop/apollo/FeatureRelationshipService.groovy
@@ -195,6 +195,8 @@ class FeatureRelationshipService {
     @Transactional
     def deleteFeatureAndChildren(Feature feature) {
 
+        println "Deleting of type: " + feature.cvTerm + " with name: ${feature.name}"
+
         // if grandchildren then delete those
         for (FeatureRelationship featureRelationship in feature.parentFeatureRelationships) {
             if (featureRelationship.childFeature?.parentFeatureRelationships) {
@@ -205,20 +207,26 @@ class FeatureRelationshipService {
         // create a list of relationships to remove (assume we have no grandchildren here)
         List<FeatureRelationship> relationshipsToRemove = []
         for (FeatureRelationship featureRelationship in feature.parentFeatureRelationships) {
+            println "adding relationships to remove ${featureRelationship.parentFeature.cvTerm} ${featureRelationship.parentFeature.name} -  ${featureRelationship.childFeature.cvTerm} ${featureRelationship.childFeature.name}"
             relationshipsToRemove << featureRelationship
         }
 
         // actually delete those
         relationshipsToRemove.each {
+            println "removing: ${it.childFeature.cvTerm}  ${it.childFeature.name}"
             it.childFeature.delete()
             feature.removeFromParentFeatureRelationships(it)
+//            println "removing relationshp: ${it.value} from ${it.parentFeature.name} ${it.parentFeature.cvTerm}"
+            println "removing relationshp: ${it.value} "
             it.delete()
         }
 
         // last, delete self or save updated relationships
         if (!feature.parentFeatureRelationships && !feature.childFeatureRelationships) {
+            println "removing parent feature: ${feature.cvTerm}"
             feature.delete(flush: true)
         } else {
+            println "saving parent feature as not pruned: ${feature.cvTerm}"
             feature.save(flush: true)
         }
 
diff --git a/grails-app/services/org/bbop/apollo/FeatureService.groovy b/grails-app/services/org/bbop/apollo/FeatureService.groovy
index 41fbb90..f1b294a 100644
--- a/grails-app/services/org/bbop/apollo/FeatureService.groovy
+++ b/grails-app/services/org/bbop/apollo/FeatureService.groovy
@@ -1540,7 +1540,7 @@ public void setTranslationEnd(Transcript transcript, int translationEnd) {
     }
 
 
-    int convertSourceCoordinateToLocalCoordinateForCDS(Feature feature, int sourceCoordinate) {
+    int convertSourceCoordinateToLocalCoordinateForCDS(CDS feature, int sourceCoordinate) {
         List<Exon> exons = exonService.getSortedExons(feature, true)
         CDS cds = transcriptService.getCDS(feature)
         int localCoordinate = 0
@@ -2512,7 +2512,7 @@ public void setTranslationEnd(Transcript transcript, int translationEnd) {
         int deletionOffset = 0
         for (SequenceAlterationInContext alteration : alterations) {
             int alterationResidueLength = alteration.alterationResidue.length()
-            if (!sequenceAlterationInContextOverlapper(feature, alteration)) {
+            if (feature instanceof Transcript && !sequenceAlterationInContextOverlapper(feature, alteration)) {
                 // sequenceAlterationInContextOverlapper method verifies if the alteration is within any of the given exons of the transcript
                 continue;
             }
diff --git a/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy b/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
index 7e24ce4..3e51c01 100644
--- a/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
+++ b/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy
@@ -1274,7 +1274,7 @@ class RequestHandlingService {
             for (Feature feature : featureService.getOverlappingFeatures(sequenceAlteration.getFeatureLocation(), false)) {
                 if (feature instanceof Gene) {
                     for (Transcript transcript : transcriptService.getTranscripts((Gene) feature)) {
-                        featureService.setLongestORF(transcript)
+                        featureService.setLongestORF(transcript,true)
                         nonCanonicalSplitSiteService.findNonCanonicalAcceptorDonorSpliceSites(transcript)
                         updateFeatureContainer.getJSONArray(FeatureStringEnum.FEATURES.value).put(featureService.convertFeatureToJSON(transcript, false));
                     }
diff --git a/test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy b/test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy
index 50d5354..5b88d62 100644
--- a/test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy
+++ b/test/integration/org/bbop/apollo/RequestHandlingServiceIntegrationSpec.groovy
@@ -3477,11 +3477,16 @@ class RequestHandlingServiceIntegrationSpec extends AbstractIntegrationSpec{
         MRNA mrna = MRNA.findByName("GB40819-RA-00001")
         requestHandlingService.setReadthroughStopCodon(JSON.parse(setReadthroughStopCodonString.replace("@UNIQUENAME@", mrna.uniqueName)) as JSONObject)
         CDS cds = transcriptService.getCDS(mrna)
+        println "CDS A: ${cds.uniqueName} ${cds.parentFeatureRelationships.size()}"
         StopCodonReadThrough scrt = cdsService.getStopCodonReadThrough(cds).first()
         // here, the CDS -> SCRT relationship exists
         assert scrt != null
 
         requestHandlingService.addSequenceAlteration(JSON.parse(addInsertionString) as JSONObject)
+        println "CDS B: ${cds.uniqueName} ${cds.parentFeatureRelationships.size()}"
+        scrt = cdsService.getStopCodonReadThrough(cds).first()
+        assert scrt!=null
+
         requestHandlingService.addSequenceAlteration(JSON.parse(addDeletionString) as JSONObject)
         requestHandlingService.addSequenceAlteration(JSON.parse(addSubstitutionString) as JSONObject)
 
@@ -3496,6 +3501,8 @@ class RequestHandlingServiceIntegrationSpec extends AbstractIntegrationSpec{
         String filePath = tempFile.absolutePath
         tempFile.deleteOnExit()
 
+
+
         def featuresToWrite = []
         Feature.all.each {
             if (it.cvTerm in [Gene.cvTerm, Pseudogene.cvTerm, TransposableElement.cvTerm, RepeatRegion.cvTerm, Insertion.cvTerm, Deletion.cvTerm, Substitution.cvTerm]) {
```

**Comment by deepakunni3** [comment]
@nathandunn Ready for test and review.

**Comment by deepakunni3** [comment]
@nathandunn Docs updated.

**Pull request merged**
