### PR TITLE
Cmdcolin fix travis database tests

### PR DESCRIPTION
**Pull request by nathandunn**
Making a small change relative to #983.

### CODE REVIEW

**Comment by cmdcolin** [comment]
This PR is probably wrong. The PR that I use is rebased or something so everything here is included twice. I can just give you access to my branches

**Comment by cmdcolin** [comment]
You can push to cmdcolin/Apollo if you wish

**Comment by nathandunn** [comment]
I can just refork off of your branch and do the pull request again.  Though I think there is a “merge and squash commit” command in GitHub now. 

Nathan

**Comment by nathandunn** [comment]
Won't rebase this time.

**Pull request closed without merging**
