### PR TITLE
#201 converted html to jsp

### PR DESCRIPTION
**Pull request by nathandunn**
For issue #201. 

@cmdcolin   @erasche 

I think that this will fix issue #201.  Let me know if this works.  You can just checkout the jspforlogin201 branch for now.

### CODE REVIEW

**Comment by erasche** [comment]
`HTTP Status 404 - /apollo/WEB-INF/jsp/user_interfaces/encryptedlocaldb/login.jsp` the login.html pages weren't renamed in their move to WEB-INF.

After attaching to the container and manually renaming the .html files to .jsp, it works perfectly and fixes #201 completely!

**Comment by nathandunn** [comment]
@erasche   Apologies, I made the change and then forgot to push.    Try doing another pull.

**Comment by nathandunn** [comment]
FYI: @spficklin    This is in mainline (post 1.0.4 and pre 1.0.5).  Not sure if you guys have the same issues.   If not, 1.0.4 should be fine for now.  We'll do another round of testing whenever we get to 1.0.5.

**Comment by erasche** [comment]
@nathandunn Ah, I think I see part of the problem, looking at https://github.com/GMOD/Apollo/commit/5765a17879308239c71f07934ea3c8ed9c4726b0
at the bottom you can see

`...ebapp/user_interfaces/encryptedlocaldb/login.html → ...app/WEB-INF/jsp/user_interfaces/localdb/login.jsp`

encryptedlocaldb is now missing the login.jsp file it needs because it went into localdb. 

```console
root@ad5a9046cffe:/usr/local/tomcat# mv webapps/apollo/WEB-INF/jsp/user_interfaces/encryptedlocaldb/login.html webapps/apollo/WEB-INF/jsp/user_interfaces/encryptedlocaldb/login.jsp 
```

fixes it for me. (Alternatively since those are html pages and not jsp, you could probably change the URL wherever it's constructed?)

**Comment by nathandunn** [comment]
Apologies.  I switched laptops and somehow these change got lost.    What I have pushed should be correct (tested it again and it looks clean).

**Comment by erasche** [comment]
Not a problem at all! I rebuilt my container and it looks great!

**Comment by nathandunn** [comment]
@erasche   Let us know what your timeline is having this "officially" released in 1.0.5.   Our next release would probably be June but I'm sure that @monicacecilia  can do a mini-test to do a mini-release.

**Comment by erasche** [comment]
@nathandunn my timeline is pretty flexible.

Currently the docker images I'm building aren't tagged to any specific release, they're just built from the HEAD of this repository. Whenever this gets merged I'll switch to building from master (instead of this branch) and publish/announce/add a GMOD wiki page/etc.

In june whenever 1.0.5 gets released, I'll probably start tagging images and associating them with specific Apollo releases.

**Comment by nathandunn** [comment]
That sounds good then.   Thanks.  Excited to see this.  I think we should make sure to do this before the summer-school (in August?).  

Nathan

**Comment by monicacecilia** [comment]
@nathandunn I'll moni-test.

**Comment by monicacecilia** [comment]
tested. :heavy_check_mark:

**Pull request merged**
