### PR TITLE
Update docs for 2.0

### PR DESCRIPTION
**Pull request by cmdcolin**
The documentation was sorely in need of some updates

Changes

* removed a lot of out of date information, especially from Configuration.md
* made the Apollo2Build.md the sort of main page for quick setup and removed old quick-start guide
* removed database setup guide as the Apollo2Build pretty much covers it (we need less handholding on the database setup now since it is so easy!)
 * added a couple screenshots for the "initial setup" on the Apollo2Build page
* some other general cleanups

View this version live here http://webapollo.readthedocs.org/en/update_docs_2.0/

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   Are you ready for me to merge this in?   I have some stuff to update on this as well, but was just going to put it in grails1 as it is mostly correct.

**Comment by nathandunn** [comment]
@cmdcolin   Specifically I'm editing Configure.md and Readme.md . . but if you are still in the middle of it let me know.

**Comment by cmdcolin** [comment]
I am pretty much done with the major changes. Note that I did major changes to configure.md since most of the xml based configuration is gone. This is mine: http://webapollo.readthedocs.org/en/update_docs_2.0/Configure/

If you want to override it then that's ok too, either after merging to grails1 or before.

**Comment by nathandunn** [comment]
Okay . . . I merged in your changes into grails1 . . . I’m sure there will be more. 

Nathan

**Comment by cmdcolin** [comment]
Thanks, definitely feel free to edit it as you see fit too

**Pull request merged**
