### PR TITLE
Fix genomic export from highlighted region 1152

### PR DESCRIPTION
**Pull request by nathandunn**
Handles case 1152.

@deepakunni3  Can you take a look at this and verify that it seems to solve at least [these two cases](https://github.com/GMOD/Apollo/issues/1152#issuecomment-235900703)?

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn It addresses the two cases in question:
1. FASTA def line present upon export of highlighted region
2. FASTA sequence is formatted with 60 characters per line

What is missing:
3. `User-created annotations -> Save track data -> FASTA -> Peptide` gives the raw genomic sequence instead of peptide sequences of features within the highlighted region
4. `User-created annotations -> Save track data -> FASTA -> CDS` gives raw genomic sequence instead of CDS sequences of features within the highlighted region

**Comment by nathandunn** [comment]
@deepakunni3  Ah thanks.  I think I see why.

**Comment by monicacecilia** [comment]
Exactly. I was explaining the same error in #1152

**Comment by nathandunn** [comment]
@deepakunni3  This is ready to retest.

**Comment by deepakunni3** [comment]
@nathandunn export cDNA, CDS, Peptide, and highlighted region all work as expected.

**Comment by monicacecilia** [comment]
👍 great! Please let me know when this has been pushed to staging.

**Pull request merged**
