### PR TITLE
#73 transcript merge overlap fix

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes case #73  . . . .

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  Probably should be tested a bit more for other cases, but it seems to work for this one and a few of the other ones.  The only issue is that I had change some of the comparison functions as it compares transcripts with no (read stripped) exons.

**Comment by nathandunn** [comment]
@deepakunni3   I checked it both locally and remotely and it looks good.  Not sure why the "remote" tests are failing on travis.  They all work locally.

**Comment by deepakunni3** [comment]
@nathandunn Yes, this is bizarre. I did several test runs before making the commits.

**Comment by nathandunn** [comment]
Sometimes the cache gets screwed up . . I’ll fix it.  Thanks.

**Comment by deepakunni3** [comment]
:+1:

**Pull request merged**
