### PR TITLE
Fix bug where generateTranscript was trying to access 'name' from JSONObject when it wasn't there to begin with

### PR DESCRIPTION
**Pull request by deepakunni3**
@nathandunn FYI

### CODE REVIEW

**Comment by nathandunn** [comment]
Looks good.  They definitely don't all have a name.

**Comment by deepakunni3** [comment]
@nathandunn Is this ready to be merged?

**Comment by nathandunn** [comment]
@deepakunni3  Yeah, sorry. I very much remember hitting the "merge" button, but it was only in my head.

**Comment by deepakunni3** [comment]
no worries :)

**Pull request merged**
