### PR TITLE
bigwig projection fixes for volvox

### LINKED ISSUE #1702: bigwig tracks don't show up for Volvox
- [ ] BigWig's don't show up in Volvox (though this works for Honeybee)

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1702 

- [x] test with limit chromosome read range for performance
- [x] fix reverse again
- [x] turn Caching back on 
- [x] clean out code 

Note that this related to 1710 as you have to copy the *.conf over.

The bigwig include files are as follows:

```
{
   "names" : {
      "type" : "Hash",
      "url" : "names/"
   },
   "alwaysOnTracks" : "DNA,Annotations",
   "tracks" : [
      {
         "storeClass" : "JBrowse/Store/Sequence/StaticChunked",
         "type" : "SequenceTrack",
         "chunkSize" : 20000,
         "label" : "DNA",
         "key" : "Reference sequence",
         "urlTemplate" : "seq/{refseq_dirpath}/{refseq}-",
         "category" : "Reference sequence"
      },
      {
         "urlTemplate" : "tracks/ExampleFeatures/{refseq}/trackData.json",
         "track" : "ExampleFeatures",
         "style" : {
            "className" : "feature2"
         },
         "category" : "Miscellaneous",
         "label" : "ExampleFeatures",
         "key" : "HTMLFeatures - Example Features",
         "compress" : 0,
         "type" : "FeatureTrack",
         "autocomplete" : "all",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "feature" : [
            "remark"
         ]
      },
      {
         "key" : "HTMLFeatures - Name test track has a really long track label",
         "compress" : 0,
         "label" : "NameTest",
         "category" : "Miscellaneous",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "feature" : [
            "protein_coding_primary_transcript",
            "polypeptide"
         ],
         "autocomplete" : "all",
         "type" : "FeatureTrack",
         "urlTemplate" : "tracks/NameTest/{refseq}/trackData.json",
         "track" : "NameTest",
         "style" : {
            "className" : "feature2"
         }
      },
      {
         "style" : {
            "className" : "triangle hgred"
         },
         "track" : "snps",
         "urlTemplate" : "tracks/snps/{refseq}/trackData.json",
         "feature" : [
            "SNP"
         ],
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "type" : "FeatureTrack",
         "autocomplete" : "all",
         "key" : "HTMLFeatures - SNPs",
         "compress" : 0,
         "label" : "snps",
         "category" : "Miscellaneous"
      },
	  {
		"track": "volvox_microarray_bw_density",
		"key": "volvox_microarray_bw_density",
		"label": "volvox_microarray_bw_density",
		"storeClass" : "JBrowse/Store/BigWig",
		"urlTemplate" : "raw/volvox/volvox_microarray.bw",
		"type" : "JBrowse/View/Track/Wiggle/Density",
		"metadata.category" : "Quantitative / Density",
		"metadata.Description" : "Wiggle/Density view of volvox_microarray.bw.  Also demonstrates use of a user-configurable callback to set the value of neg_color to green when the score is below 150."
	  },
   {
		"track": "volvox_microarray_bw_xyplot",
		"key": "volvox_microarray_bw_xyplot",
		"label": "volvox_microarray_bw_xyplot",
		"style.pos_color" : "function(feature) { return feature.get('score') > 300 ? 'red' : 'blue'; }",
		"variance_band" : "true",
		"key" : "BigWig XY - volvox_microarray",
		"label" : "BigWig XY - volvox_microarray",
		"storeClass" : "JBrowse/Store/BigWig",
		"urlTemplate" : "raw/volvox/volvox_microarray.bw",
		"type" : "JBrowse/View/Track/Wiggle/XYPlot",
		"metadata.category" : "Quantitative / XY Plot",
		"metadata.description" : "Wiggle/XYPlot view of volvox_microarray.bw.  Demonstrates use of a user-configured callback to set the bar color to red when the score is above 300."
   },
   {
		"track": "volvox_sine_density",
		"key": "volvox_sine_density",
		"label": "volvox_sine_density",
		"storeClass" : "JBrowse/Store/BigWig",
		"urlTemplate" : "raw/volvox/volvox_sine.bw",
		"category" : "Quantitative / Density",
		"type" : "JBrowse/View/Track/Wiggle/Density",
		"bicolor_pivot" : "mean",
		"key" : "BigWig Density - volvox_sine"
   },
   {
		"track": "volvox_sine_xyplot",
		"key": "volvox_sine_xyplot",
		"label": "volvox_sine_xyplot",
		"storeClass" : "JBrowse/Store/BigWig",
		"urlTemplate" : "raw/volvox/volvox_sine.bw",
		"style.bg_color" : "#ccc",
		"category" : "Quantitative / XY Plot",
		"type" : "JBrowse/View/Track/Wiggle/XYPlot",
		"key" : "BigWig XY - volvox_sine"
   },
      {
         "track" : "Motifs",
         "urlTemplate" : "tracks/Motifs/{refseq}/trackData.json",
         "description" : 1,
         "style" : {
            "className" : "feature3",
            "label" : "function(feature) { return feature.get('Name')+' (via JS callback)' }",
            "description" : "function(feature) { return feature.get('Name')+': '+feature.get('Note'); }"
         },
         "category" : "Miscellaneous",
         "compress" : 0,
         "key" : "HTMLFeatures - Example motifs",
         "label" : "Motifs",
         "type" : "FeatureTrack",
         "autocomplete" : "all",
         "feature" : [
            "polypeptide_domain"
         ],
         "storeClass" : "JBrowse/Store/SeqFeature/NCList"
      },
      {
         "feature" : [
            "match"
         ],
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "autocomplete" : "all",
         "type" : "FeatureTrack",
         "key" : "HTMLFeatures - Features with right-click menus",
         "label" : "malformed_alignments",
         "compress" : 0,
         "menuTemplate" : [
            {
               "children" : [
                  {
                     "label" : "Check gene on databases",
                     "children" : [
                        {
                           "label" : "Query trin for {name}",
                           "url" : "http://wiki.trin.org.au/{name}-{start}-{end}",
                           "action" : "newWindow",
                           "iconClass" : "dijitIconBookmark"
                        },
                        {
                           "url" : "http://example.com/{name}-{start}-{end}",
                           "label" : "Query example.com for {name}",
                           "iconClass" : "dijitIconSearch"
                        }
                     ]
                  },
                  {
                     "label" : "2nd child of demo"
                  },
                  {
                     "label" : "3rd child: this is a track"
                  }
               ],
               "label" : "Item with submenu"
            },
            {
               "iconClass" : "dijitIconDatabase",
               "title" : "The magnificent example.com (feature {name})",
               "action" : "iframeDialog",
               "label" : "Open example.com in an iframe popup",
               "url" : "http://www.example.com?featurename={name}"
            },
            {
               "action" : "xhrDialog",
               "title" : "function(track,feature,div) { return 'Random XHR HTML '+Math.random()+' title!'; }",
               "label" : "Open popup with XHR HTML snippet (btw this is feature {name})",
               "url" : "sample_data/test_snippet.html?featurename={name}:{start}-{end}",
               "iconClass" : "dijitIconDatabase"
            },
            {
               "title" : "function(track,feature,div) { return 'Random content snippet '+Math.random()+' title!'; }",
               "action" : "contentDialog",
               "label" : "Popup with content snippet from a function (feature {name})",
               "content" : "function(track,feature,div) { return '<h2>'+feature.get('name')+'</h2><p>This is some test content!</p><p>This message brought to you by the number <span style=\"font-size: 300%\">'+Math.round(Math.random()*100)+'</span>.</p>';} ",
               "iconClass" : "dijitIconDatabase"
            },
            {
               "title" : "{randomNumberTitle}",
               "action" : "contentDialog",
               "content" : "<h2>{name}</h2><p>This is some test content about {name}, which goes from {start} to {end} on the {strand} strand.</p>",
               "label" : "Popup with content snippet from string (feature {name})",
               "iconClass" : "dijitIconDatabase"
            },
            {
               "label" : "{randomNumberLabel}",
               "action" : "{exampleFeatureClick}",
               "iconClass" : "dijitIconDatabase"
            }
         ],
         "hooks" : {
            "modify" : "function( track, feature, div ) { div.style.backgroundColor = ['green','blue','red','orange','purple'][Math.round(Math.random()*5)];}"
         },
         "style" : {
            "className" : "feature4"
         },
         "metadata" : {
            "category" : "Miscellaneous",
            "Description" : "Features with extensively customized right-click menus, and with their colors set at random by a JavaScript callback."
         },
         "track" : "malformed_alignments",
         "urlTemplate" : "tracks/malformed_alignments/{refseq}/trackData.json"
      },
      {
         "trackType" : "JBrowse/View/Track/CanvasFeatures",
         "feature" : [
            "gene"
         ],
         "key" : "CanvasFeatures - Protein-coding genes",
         "style" : {
            "className" : "feature5"
         },
         "fmtDetailValue_Name" : "function(name,feature) { if(feature.get('type')=='gene') { return name + ' <a href=http://www.ncbi.nlm.nih.gov/gquery/?term='+name+'>[NCBI custom link]</a>'; } else { return name; } }",
         "urlTemplate" : "tracks/Genes/{refseq}/trackData.json",
         "track" : "Genes",
         "type" : "JBrowse/View/Track/CanvasFeatures",
         "autocomplete" : "all",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "fmtMetaValue_Name" : "function(name) { return name+' [Track with custom callbacks for About track popup]'; }",
         "category" : "Transcripts",
         "fmtMetaField_Name" : "function(name) { return 'Track Name'; }",
         "menuTemplate" : [
            {
               "label" : "View details"
            },
            {
               "label" : "Zoom this gene"
            },
            {
               "label" : "Highlight this gene"
            },
            {
               "action" : "contentDialog",
               "title" : "{randomNumberTitle}",
               "label" : "Popup with content snippet from string (feature {name})",
               "content" : "<h2>{name}</h2>This is some test content about {type} {name}, which goes from {start} to {end} on the {strand} strand.",
               "iconClass" : "dijitIconDatabase"
            }
         ],
         "fmtDetailField_Load_id" : "function(name,feature) { /* remove field from dialog box */ return null; }",
         "compress" : 0,
         "label" : "Genes",
         "fmtDetailField_Name" : "function(name,feature) { if(feature.get('type')=='gene') { return 'Gene Name'; } else { return name; } }",
         "onClick" : {
            "label" : "<div style='font:normal 12px Univers,Helvetica,Arial,sans-serif'><div style='font-weight:bold'>Custom tooltip</div><div style='color:blue;'>Feature name: {name}<br />Feature start: {start}<br />Feature end: {end}</div></div>",
            "action" : "defaultDialog",
            "title" : "{type} {name}"
         },
         "fmtMetaDescription_Name" : "function(name) { return '[Custom description]'; }"
      },
      {
         "type" : "FeatureTrack",
         "autocomplete" : "all",
         "feature" : [
            "mRNA"
         ],
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "phase" : 1,
         "category" : "Transcripts",
         "label" : "ReadingFrame",
         "compress" : 0,
         "key" : "HTMLFeatures - mRNAs",
         "onClick" : {
            "title" : "NCBI search box",
            "url" : "http://www.ncbi.nlm.nih.gov/gquery/?term={name}",
            "label" : "Search for {name} at NCBI\nFeature start {start}\nFeature end {end}"
         },
         "style" : {
            "className" : "cds"
         },
         "track" : "ReadingFrame",
         "urlTemplate" : "tracks/ReadingFrame/{refseq}/trackData.json"
      },
      {
         "type" : "CanvasFeatures",
         "autocomplete" : "all",
         "feature" : [
            "CDS:bare_predicted",
            "mRNA:exonerate",
            "mRNA:predicted"
         ],
         "trackType" : "CanvasFeatures",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "category" : "Transcripts",
         "key" : "CanvasFeatures - mixed mRNAs and CDSs",
         "compress" : 0,
         "label" : "CDS",
         "style" : {
            "linkTemplate" : "http://www.ncbi.nlm.nih.gov/gquery/?term={name}-{start}-{end}",
            "className" : "cds"
         },
         "track" : "CDS",
         "urlTemplate" : "tracks/CDS/{refseq}/trackData.json"
      },
      {
         "subfeatures" : true,
         "autocomplete" : "all",
         "type" : "JBrowse/View/Track/CanvasFeatures",
         "feature" : [
            "mRNA:exonerate"
         ],
         "trackType" : "JBrowse/View/Track/CanvasFeatures",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "category" : "Transcripts",
         "compress" : 0,
         "key" : "CanvasFeatures - transcripts",
         "label" : "Transcript",
         "onClick" : "{exampleFeatureClick}",
         "style" : {
            "className" : "feature",
            "color" : "#E32A3A"
         },
         "track" : "Transcript",
         "urlTemplate" : "tracks/Transcript/{refseq}/trackData.json",
         "description" : 1
      },
      {
         "category" : "Miscellaneous",
         "compress" : 0,
         "key" : "HTMLFeatures - Fingerprinted BACs",
         "label" : "Clones",
         "type" : "FeatureTrack",
         "autocomplete" : "all",
         "feature" : [
            "BAC"
         ],
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "track" : "Clones",
         "urlTemplate" : "tracks/Clones/{refseq}/trackData.json",
         "description" : 1,
         "style" : {
            "className" : "exon"
         }
      },
      {
         "track" : "EST",
         "urlTemplate" : "tracks/EST/{refseq}/trackData.json",
         "style" : {
            "className" : "est"
         },
         "category" : "Miscellaneous",
         "label" : "EST",
         "compress" : 0,
         "key" : "HTMLFeatures - ESTs",
         "type" : "FeatureTrack",
         "autocomplete" : "all",
         "feature" : [
            "EST_match:est"
         ],
         "storeClass" : "JBrowse/Store/SeqFeature/NCList"
      },
      {
         "style" : {
            "className" : "image"
         },
         "type" : "ImageTrack.Wiggle",
         "compress" : 0,
         "label" : "volvox_microarray.wig",
         "key" : "Image - volvox_microarray.wig",
         "urlTemplate" : "tracks/volvox_microarray.wig/{refseq}/trackData.json",
         "metadata" : {
            "category" : "Pre-generated images"
         }
      },
      {
         "urlTemplate" : "tracks/bam_simulated/{refseq}/trackData.json",
         "metadata" : {
            "category" : "BAM"
         },
         "style" : {
            "featureCss" : "background-color: #66F; height: 8px",
            "histScale" : 2,
            "histCss" : "background-color: #88F",
            "className" : "basic"
         },
         "compress" : 0,
         "label" : "bam_simulated",
         "key" : "Legacy BAM - volvox-sorted.bam",
         "type" : "FeatureTrack",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList"
      },
      {
         "disableJBrowseMode" : false,
         "autocomplete" : "none",
         "subfeatures" : 1,
         "type" : "WebApollo/View/Track/AnnotTrack",
         "storeClass" : "WebApollo/Store/SeqFeature/ScratchPad",
         "phase" : 0,
         "label" : "Annotations",
         "key" : "User-created Annotations",
         "compress" : 0,
         "style" : {
            "subfeatureClasses" : {
               "non_canonical_five_prime_splice_site" : "noncanonical-splice-site",
               "UTR" : "annot-UTR",
               "non_canonical_three_prime_splice_site" : "noncanonical-splice-site",
               "wholeCDS" : null,
               "CDS" : "annot-CDS",
               "exon" : "container-100pct"
            },
            "arrowheadClass" : "annot-arrowhead",
            "uniqueIdField" : "id",
            "centerSubFeature" : {
               "non_canonical_five_prime_splice_site" : false,
               "non_canonical_three_prime_splice_site" : false
            },
            "renderClassName" : "annot-render",
            "className" : "annot",
            "alternateClasses" : {
               "repeat_region" : {
                  "className" : "magenta-80pct"
               },
               "snoRNA" : {
                  "className" : "brightgreen-80pct",
                  "renderClassName" : "gray-center-30pct"
               },
               "transposable_element" : {
                  "renderClassName" : "blue-ibeam-render",
                  "className" : "blue-ibeam"
               },
               "snRNA" : {
                  "className" : "brightgreen-80pct",
                  "renderClassName" : "gray-center-30pct"
               },
               "pseudogene" : {
                  "renderClassName" : "gray-center-30pct",
                  "className" : "light-purple-80pct"
               },
               "ncRNA" : {
                  "renderClassName" : "gray-center-30pct",
                  "className" : "brightgreen-80pct"
               },
               "rRNA" : {
                  "className" : "brightgreen-80pct",
                  "renderClassName" : "gray-center-30pct"
               },
               "miRNA" : {
                  "renderClassName" : "gray-center-30pct",
                  "className" : "brightgreen-80pct"
               },
               "tRNA" : {
                  "className" : "brightgreen-80pct",
                  "renderClassName" : "gray-center-30pct"
               }
            }
         }
      }

   ],
   "formatVersion" : 1,
   "dataset_id" : "volvox",
   "include" : [
      "../../raw/volvox/functions.conf"
   ],
   "plugins" : [
      {
         "location" : "./plugins/WebApollo",
         "name" : "WebApollo"
      }
   ],
   "favicon" : "./plugins/WebApollo/img/webapollo_favicon.ico",
   "share_link" : 0
}
```

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  This is ready for review.

**Comment by deepakunni3** [comment]
Ran into an issue where the wrong values are being shown for regions.

For example,
screen shot 2017-07-21 at 4 37 17 pm

Notice how the region 473500 - 474500 in Apollo has a major peak but in JBrowse that region doesn't display the same peak.

**Comment by nathandunn** [comment]
Is this before the BigWig merge?    I fixed a few things there related to bigwig (it was unnecessarily filtering some values).  I would close this and look at it there and report the same bug if its still there.  

Also, would help to show the EXACT same region.

**Comment by deepakunni3** [comment]
Region in Apollo:
screen shot 2017-07-21 at 5 02 37 pm

Same region in JBrowse:
screen shot 2017-07-21 at 5 05 53 pm

**Comment by nathandunn** [comment]
Okay, that clearly broke more than it fixed.  PR at the top, then JBrowse and then current 2.1.0.  

screen shot 2017-07-21 at 4 47 07 pm

**Comment by nathandunn** [comment]
Location string: Group1.10:474486..474734 (250 b)

**Comment by nathandunn** [comment]
This fixes the bigwig for Honeybee and the microarray, but the resolution isn't good enough for the sine wave:

```
  def calculateFeatureArray(JSONArray featuresArray, int actualStart, int actualStop, int stepSize, BigWigFileReader bigWigFileReader, MultiSequenceProjection projection, ProjectionSequence projectionSequence) {
-        Integer chrStart = bigWigFileReader.getChrStart(projectionSequence.name)
-        Integer chrStop = bigWigFileReader.getChrStop(projectionSequence.name)
-        double min = bigWigFileReader.min()
-        double max = bigWigFileReader.max()
-        Interval interval = new Interval(projectionSequence.name, chrStart,chrStop)
-        edu.unc.genomics.Contig innerContig = bigWigFileReader.query(interval)
-        float[] values = innerContig.values
         for (Integer i = actualStart; i < actualStop; i += stepSize) {
             JSONObject globalFeature = new JSONObject()
-            globalFeature.put(FeatureStringEnum.START.value, i + projectionSequence.projectedOffset)
             Integer endStep = i + stepSize
+            globalFeature.put(FeatureStringEnum.START.value, i + projectionSequence.projectedOffset)
             globalFeature.put(FeatureStringEnum.END.value, endStep + projectionSequence.projectedOffset)
-            Integer projectedIncrement = projection.unProjectValue(i)
+            Integer originalStart = projection.unProjectValue(i)
+            Integer originalEnd = projection.unProjectValue(endStep)
+            edu.unc.genomics.Contig innerContig = bigWigFileReader.query(projectionSequence.name, originalStart, originalEnd)
+            Integer value = innerContig.mean()
 
-            // filter out NaN or unexpected values values
-            if (projectedIncrement < values.length && values[projectedIncrement] <= max && values[projectedIncrement] >= min) {
-                globalFeature.put(FeatureStringEnum.SCORE.value, values[projectedIncrement])
-                featuresArray.add(globalFeature)
-            }
+            globalFeature.put("score", value >= 1 ? value : 1)
+            featuresArray.add(globalFeature)
         }
```

**Comment by nathandunn** [comment]
I think it is working now.  

screen shot 2017-07-21 at 5 43 31 pm
screen shot 2017-07-21 at 5 43 26 pm
screen shot 2017-07-21 at 5 43 21 pm
screen shot 2017-07-21 at 5 43 13 pm
screen shot 2017-07-21 at 5 41 19 pm
screen shot 2017-07-21 at 5 40 20 pm

**Comment by nathandunn** [comment]
Works in reverse the same.  Works on honeybee and volvox data.

**Comment by nathandunn** [comment]
@deepakunni3  Ready for re-review.

**Comment by nathandunn** [comment]
On Monday.

**Comment by nathandunn** [comment]
The end is off-by-one when looking at this region of Honeybee (thanks to @deepakunni3  for initially pointing this out): Group1.10:475538..475686 (150 b)

I checked the wiggle and it confirms that it is off (though just on the tail end, not on the start).  

On the end (one extra):

screen shot 2017-07-22 at 7 47 15 pm

and the corresponding wiggle file:

```
Group1.10	475607	475608	988
Group1.10	475608	475609	540
Group1.10	475609	475610	516
Group1.10	475610	475615	21
Group1.10	475615	475627	22
Group1.10	475627	475635	21
Group1.10	475635	475636	19
```

On the start (exact match):

screen shot 2017-07-22 at 7 49 34 pm

and the corresponding wiggle file:

```
Group1.10	474602	474603	86
Group1.10	474603	474605	87
Group1.10	474605	474610	88
Group1.10	474610	474613	106
Group1.10	474613	474614	108
Group1.10	474614	474615	116
Group1.10	474615	474616	117
```

**Comment by nathandunn** [comment]
The off-by-one error is fixed now.

**Comment by deepakunni3** [comment]
@nathandunn The end is still off by one when comparing to JBrowse

**Comment by nathandunn** [comment]
So, the difference is this for this region (ctgA:38912..39119 (209 b)):

Grabbing the min of a region gives the same as JBrowse:

screen shot 2017-07-24 at 1 57 56 pm
screen shot 2017-07-24 at 1 57 36 pm


Whereas the mean returns the intermediate value:

screen shot 2017-07-24 at 1 56 41 pm

**Pull request merged**
