### PR TITLE
added apollo run-app

### PR DESCRIPTION
**Pull request by nathandunn**
just added an additional target "run-app" so that we don't have to compile gwtc each time

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   Can you take a look at this and let me know if it works for you and is clear enough?   thanks.

**Comment by cmdcolin** [comment]
This requires ant devmode in a separate tab correct? Just wondering if there's a way that this fits in with other commands. It does seem good to start using gradle but just want to reduce the amount of subcommands available

**Comment by cmdcolin** [comment]
Could also consider http://www.gwtproject.org/doc/latest/FAQ_DebuggingAndCompiling.html

Section "Can_I_speed_up_the_GWT_compiler?"

**Comment by nathandunn** [comment]
Yeah, dev-mod is far better than the compiling version unless you're getting much different versions.

**Pull request merged**
