### PR TITLE
Fix 1900 variant annotation count

### LINKED ISSUE #1900: variant annotations not shown in annotator panel
When you create a variant annotation, it does not appear on the Sequence Panel annotation count.  Unlike an alteration, I *feel* like this is the correct decision.

Will issue a PR for review and can back-out if need be.

### PR DESCRIPTION
**Pull request by nathandunn**
fixed #1900

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn Is the goal to count **only** variants and not assembly error corrections? Which seems to be the right expectation.

**Comment by deepakunni3** [comment]
@nathandunn I had to revert a commit because that approach was a little overcomplicated.

The most recent commit should fix the bug

**Comment by deepakunni3** [comment]
@nathandunn This is read to test

**Comment by nathandunn** [comment]
tested and works . thanks

**Pull request merged**
