### PR TITLE
Update to 2 5 4

### PR DESCRIPTION
**Pull request by nathandunn**
upgrade to 2.5.4

### CODE REVIEW

**Comment by cmdcolin** [comment]
Travis build gives this error

```
Downloading http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.5.4.zip to /home/travis/.grails/wrapper/grails-2.5.4-download.zip
Exception in thread "main" java.io.FileNotFoundException: http://dist.springframework.org.s3.amazonaws.com/release/GRAILS/grails-2.5.4.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at org.grails.wrapper.RemoteFileHelper.retrieve(RemoteFileHelper.java:49)
	at org.grails.wrapper.GrailsWrapper.configureGrailsInstallation(GrailsWrapper.java:137)
	at org.grails.wrapper.GrailsWrapper.main(GrailsWrapper.java:57)
```

**Comment by nathandunn** [comment]
Weird.  Thanks.  There are few things wrong with it.   I'll check it before I push it through .  . if I ever get it working.

**Comment by nathandunn** [comment]
@deepakunni3   Can you test this when you have a minute.   @cmdcolin  If you would like to do the same.    The biggest "deal" here is again changes to hibernate (have to be pretty explicit about calling flush).

**Comment by deepakunni3** [comment]
@nathandunn I got the following error while trying to do `./apollo deploy`:

````
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deepak.unni3/GIT/apollo-nathandunn/build.gradle' line: 359

* What went wrong:
Execution failed for task ':npmBin'.
> A problem occurred starting process 'command 'npm''


````

**Comment by nathandunn** [comment]
That is because node must not be installed (I didn't change that part).  It is a bad error though and I should fix it. 

That being said, you can ignore these:

```
null
| Warning The [$tt__getSequences] action in [org.bbop.apollo.SequenceController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.

null
```

It is a known non-issue.

**Comment by deepakunni3** [comment]
I installed both NPM and Bower. Trying again.

**Comment by nathandunn** [comment]
K.  Let me know.

**Comment by nathandunn** [comment]
@deepakunni3  Something else is up with as far as the build.  Not really sure what, though it looks like JBrowse isn't quite building correctly.  I'll try to get the green light first.

**Comment by deepakunni3** [comment]
@nathandunn When I run `apollo deploy`, the command checks out the master branch and then does a deploy instead of sticking to the current branch.

**Comment by nathandunn** [comment]
Weird . . . okay I'll take a look.

**Comment by nathandunn** [comment]
@deepakunni3   I'm going to close this for now.  It was a nice to have for me, but its not essential.

**Comment by nathandunn** [comment]
@deepakunni3   I lied.   It was caching the jbrowse-download directory.   I would suggest doing a separate git clone:

```
git clone --single-branch -b update_to_2_5 https://github.com/nathandunn/Apollo ApolloTest
```

And then seeing if you can get it to deploy, tests-run, etc.    Also, you can see from my changes, I changed the way it was copying the apollo-config.groovy.

**Comment by nathandunn** [comment]
copying the apollo-config.groovy . . . . in .travis.yml

**Comment by cmdcolin** [comment]
Why was it changed to "cp config/mysql.travis ../apollo-config.groovy; "? Was it not placing in the right place?

**Comment by nathandunn** [comment]
@cmdcolin  Right.  It runs it runs the copy from the test directory as far as I can tell.   mysql.travis is in test/config/mysql.travis and apollo-config.groovy needs to be at the root level.  I could be wrong about this, though.

**Comment by nathandunn** [comment]
It did *seem* to work before, though it seems odd that it did.  Perhaps I could add some information in the bootstrap to double-check.

**Comment by cmdcolin** [comment]
I think those commands have been silently failing for awhile. I thought the file was in "config/mysql.travis" but obviously it's in "test/config/mysql.travis"

We should change it to instead of cp to ../ to "cp test/config/mysql.travis apollo-config.groovy" I believe

Since this was in the before_install section I think it was just ignoring failed commands

**Comment by cmdcolin** [comment]
Here is a link to the failed part for example https://travis-ci.org/GMOD/Apollo/jobs/122562090#L214

**Comment by nathandunn** [comment]
I bet the config is somehow stuck on 1.12.1 or using a cached jbrowse 

Nathan

**Comment by nathandunn** [comment]
@deepakunni3  I think its ready to review again.

**Comment by deepakunni3** [comment]
```
Warning The [$tt__delete] action in [org.bbop.apollo.ProxyController] accepts a parameter of type [org.springframework.transaction.TransactionStatus].  Interface types and abstract class types are not supported as command objects.  This parameter will be ignored.
```

While running `apollo deploy`, for any controller that has methods annotated with `@Transactional` this warning is displayed. Not a big deal though since its just a warning.

**Comment by deepakunni3** [comment]
Here is the summary on the ecache issue:

1. If I run apollo with the default H2 database, there is no issue.
2. If I remove Chado data source from the apollo-config.groovy and then run apollo, there is no issue.
3. If I keep both the data sources in apollo-config.groovy and then run apollo, I get the following stack trace: https://gist.github.com/deepakunni3/f34fded4addc2d504658ba2e05fc52d4

**Comment by nathandunn** [comment]
Yeah, that is a known issue solved in 2.5.5:  https://github.com/grails/grails-core/issues/9770

I'll take a look at that stack trace.

**Comment by nathandunn** [comment]
The static check is working, but I am getting this error twice . . . somehow the chado feature does not exist I think:

```
| Error 2016-04-14 11:24:41,713 [main] ERROR hbm2ddl.SchemaUpdate  - ERROR: column "cvterm_id" referenced in foreign key constraint does not exist
| Running 13 integration tests... 2 of 13
| Failure:  test CHADO export for standard annotations(org.bbop.apollo.ChadoHandlerServiceIntegrationSpec)
|  grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'org.gmod.chado.FeatureRelationship' on field 'object': rejected value [null]; codes [org.gmod.chado.FeatureRelationship.object.nullable.error.org.gmod.chado.FeatureRelationship.object,org.gmod.chado.FeatureRelationship.object.nullable.error.object,org.gmod.chado.FeatureRelationship.object.nullable.error.org.gmod.chado.Feature,org.gmod.chado.FeatureRelationship.object.nullable.error,featureRelationship.object.nullable.error.org.gmod.chado.FeatureRelationship.object,featureRelationship.object.nullable.error.object,featureRelationship.object.nullable.error.org.gmod.chado.Feature,featureRelationship.object.nullable.error,org.gmod.chado.FeatureRelationship.object.nullable.org.gmod.chado.FeatureRelationship.object,org.gmod.chado.FeatureRelationship.object.nullable.object,org.gmod.chado.FeatureRelationship.object.nullable.org.gmod.chado.Feature,org.gmod.chado.FeatureRelationship.object.nullable,featureRelationship.object.nullable.org.gmod.chado.FeatureRelationship.object,featureRelationship.object.nullable.object,featureRelationship.object.nullable.org.gmod.chado.Feature,featureRelationship.object.nullable,nullable.org.gmod.chado.FeatureRelationship.object,nullable.object,nullable.org.gmod.chado.Feature,nullable]; arguments [object,class org.gmod.chado.FeatureRelationship]; default message [Property [{0}] of class [{1}] cannot be null]

	at org.bbop.apollo.ChadoHandlerService.$tt__createChadoFeatureRelationship(ChadoHandlerService.groovy:485)
	at org.bbop.apollo.ChadoHandlerService._tt__createChadoFeaturesForAnnotation_closure52$_closure72(ChadoHandlerService.groovy:147)
	at org.bbop.apollo.ChadoHandlerService._tt__createChadoFeaturesForAnnotation_closure52(ChadoHandlerService.groovy:146)
	at org.bbop.apollo.ChadoHandlerService.$tt__createChadoFeaturesForAnnotation(ChadoHandlerService.groovy:144)
	at org.bbop.apollo.ChadoHandlerService._tt__writeFeaturesToChado_closure51(ChadoHandlerService.groovy:114)
	at org.bbop.apollo.ChadoHandlerService.$tt__writeFeaturesToChado(ChadoHandlerService.groovy:112)
	at org.bbop.apollo.ChadoHandlerService.$tt__writeFeatures(ChadoHandlerService.groovy:69)
	at org.bbop.apollo.ChadoHandlerServiceIntegrationSpec.test CHADO export for standard annotations(ChadoHandlerServiceIntegrationSpec.groovy:112)
| Running 13 integration tests... 3 of 13
| Failure:  test CHADO export for annotations with additional information(org.bbop.apollo.ChadoHandlerServiceIntegrationSpec)
```

I added some flushes in #f35766 and I think it is working.

**Comment by nathandunn** [comment]
@deepakunni3   So I think it is ready to test again, but if you want to wait until it completes (now that it is actually using PostgreSQL)

**Comment by nathandunn** [comment]
@deepakunni3   It is ready to test.   I ran it with Chado and it was all fine (tests and locally).

**Comment by deepakunni3** [comment]
@nathandunn Yes, it works fine in all three cases. 👍 

I am surprised to see those issues with not having `flush: true`.

**Comment by nathandunn** [comment]
@deepakunni3   Yeah, its part of the hibernate upgrade.

**Pull request merged**
