### PR TITLE
Add filters parameter to the recent changes page. See #824

### PR DESCRIPTION
**Pull request by cmdcolin**
This applies a fix to keep track of the filter parameters during sorting so that it remembers the filters after applying a sort on the columns of the table

### CODE REVIEW

**Comment by nathandunn** [comment]
Related to #824.

**Comment by cmdcolin** [comment]
Added another small patch to make it so that when submitting a filter it remembers sort order

The first commit was so that when doing a sort it remembers the filter

Should solve the "mutually exclusive" aspect of #824

**Comment by nathandunn** [comment]
I like this more generic solution.  I made a few other minor cosmetic changes, as well, but overall looked good.

**Comment by cmdcolin** [comment]
cool. bootstrap looks good

**Pull request merged**
