### PR TITLE
Group search box testing

### PR DESCRIPTION
**Pull request by childers**
This PR is for the addition of search in the group panel.  This should be attributed to our new intern Tony Wu

### CODE REVIEW

**Comment by tony006469** [comment]
Compared with the console log of original project, I think the problem may be in the permission section of the GroupPanel Code. (uncheck and unsafe operations)
Because I am not sure if my permission part  is correct.
I have used the Web Service API to confirm that there are user, group and organism on my local host.
Besides, I added a new GroupInfoConverter. GroupRestService also has some modifications.
I will continue to find ways to debug, if there is any better way, please let me know. 
Thank you so much.

**Comment by nathandunn** [comment]
@tony006469  I use the devmode, but I'll take a look  Permisisons could very well be possible

**Comment by nathandunn** [comment]
I have a couple of ideas for this:  ""The specified display has already been added to this adapter.""  having it in master, is helpful though .

**Comment by nathandunn** [comment]
The problem so far as I can tell is that you are adding the display twice for the dataProvider

**Comment by nathandunn** [comment]
I removed some of the errant code (you had stuff specified twice in certain circumstances).  

You're going to have to update the API on the GroupController (loadGroups) or create a separate route to support the sorting.   You can see the "UserController -> loadUsers()" for clarity.  

Note that the server routes specfied in grails are:  user/loadUsers  call the UserController.groovy  class's loadUser() method.

**Comment by tony006469** [comment]
Ok, I will try it as you mentioned. Thank you so much.

**Comment by nathandunn** [comment]
And you saw this, right? 

https://genomearchitect.readthedocs.io/en/latest/Apollo2Build.html?highlight=devmode#running-the-code-for-gwt-changes

**Comment by tony006469** [comment]
Yes, but I am not sure if I use it correctly.

**Comment by nathandunn** [comment]
Closing this for now.  This is the right approach overall.  Please let me know if this large of groups is causing a problem.

**Pull request closed without merging**
