### PR TITLE
Fix build 1756

### LINKED ISSUE #1756: 2.0.7 build issues
Some ways of installing 2.0.7 have issues as a result of dropping bower (we think).   We should test for different versions of node (or just enforce node 8). 

- [ ] when installing a RegexSequenceSearch plugin in the apollo-config.groovy RegexSequenceSearch may not be properly installed (or vice versa) 
- [ ] in some instances, setup.sh is run before fully installing
- [ ] issue #1752 (and see below)
- [ ] we should make 6 active it looks like: https://nodejs.org/en/blog/release/v8.0.0/
- [x] default should be "#master" branch
- [x] should allow for git@abcd.com

- [ ] test node6, node7, node8

```
argv "/usr/bin/node" "/usr/bin/npm" "install" "NAL-i5K/NAL_CSS#master" "--ignore-scripts"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read
 
npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.
 ```

Also, EISDIR is "error is directory"  https://stackoverflow.com/a/42677294/1739366 , which is odd and maybe there is a renaming error in there.   Using package.json at the top level is a good idea, as well, but may over-complicate things, as well.  

FYI @childers  / @luke-c-sargent

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1756 and #1752

### CODE REVIEW

**Comment by deepakunni3** [comment]
### Build with default plugins included with JBrowse

Default plugins are NeatHTMLFeatures, NeatCanvasFeatures, RegexSequenceSearch, HideTrackLabels.

I get the following on the first `./apollo deploy`:
```
Node Version: 8
Npm Version: 5
javac 1.8.0_101 found
javac installed
JDK 1.8 found: javac 1.8.0_101
...
...
...
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deepak.unni3/GIT/apollo-nathandunn-too/build.gradle' line: 305

* What went wrong:
Execution failed for task ':installJBrowseNpm'.
> A problem occurred starting process 'command './setup.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

If I run `./apollo deploy` again without changing anything then the build completes successfully ✅

### Build with default plugins included with JBrowse + plugins from GitHub

Additional plugins: SashimiPlot
```
SashimiPlot {
    git = 'https://github.com/cmdcolin/sashimiplot'
    branch = 'master'
    alwaysPull = "true"
}
```

When I run `./apollo deploy` I get the following:
```
Node Version: 8
Npm Version: 5
javac 1.8.0_101 found
javac installed
JDK 1.8 found: javac 1.8.0_101
...
...
...
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deepak.unni3/GIT/apollo-nathandunn-too/build.gradle' line: 305

* What went wrong:
Execution failed for task ':installJBrowseNpm'.
> A problem occurred starting process 'command './setup.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I run `./apollo deploy` again without changing anything then the build completes successfully ✅

### Build with default plugins included with JBrowse + plugins from GitHub

Additional plugins: SashimiPlot, "G-OnRamp_plugin"
```
"G-OnRamp_plugin"{
    git = "https://github.com/Yating-L/JBrowse_plugins"
    branch = "master"
}

SashimiPlot {
    git = 'https://github.com/cmdcolin/sashimiplot'
    branch = 'master'
    alwaysPull = "true"
}
```

When I run `./apollo deploy` I get the following:
```
Node Version: 8
Npm Version: 5
javac 1.8.0_101 found
javac installed
JDK 1.8 found: javac 1.8.0_101
...
...
...
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deepak.unni3/GIT/apollo-nathandunn-too/build.gradle' line: 305

* What went wrong:
Execution failed for task ':installJBrowseNpm'.
> A problem occurred starting process 'command './setup.sh''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I run `./apollo deploy` again without changing anything,
```
Node Version: 8
Npm Version: 5
javac 1.8.0_101 found
javac installed
JDK 1.8 found: javac 1.8.0_101
...
...
...
Evaluating plugin G-OnRamp_plugin=[git:https://github.com/Yating-L/JBrowse_plugins, branch:master]
Plugin is supplied by git
Cloning 'https://github.com/Yating-L/JBrowse_plugins' into 'jbrowse-download/plugins/G-OnRamp_plugin'
Cloning repo with https://github.com/Yating-L/JBrowse_plugins,jbrowse-download/plugins/G-OnRamp_plugin,master
final github url: Yating-L/JBrowse_plugins#master
using npm to install: Yating-L/JBrowse_plugins#master
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: github:Yating-L/JBrowse_plugins#master.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/deepak.unni3/.npm/_logs/2017-09-21T20_02_52_424Z-debug.log
:installJBrowsePlugins FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deepak.unni3/GIT/apollo-nathandunn-too/build.gradle' line: 296

* What went wrong:
Execution failed for task ':installJBrowsePlugins'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```



If I do the same with Node 7.10.1 and npm 4.2, I get the following:
```
Node Version: 7
Npm Version: 4
javac 1.8.0_101 found
javac installed
JDK 1.8 found: javac 1.8.0_101
...
...
...
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/deepak.unni3/.npm/_git-remotes/_templates --mirror git@github.com:yating-l/JBrowse_plugins.git /Users/deepak.unni3/.npm/_git-remotes/git-github-com-yating-l-JBrowse-plugins-git-master-2ad594a1
npm ERR! Cloning into bare repository '/Users/deepak.unni3/.npm/_git-remotes/git-github-com-yating-l-JBrowse-plugins-git-master-2ad594a1'...
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deepak.unni3/.npm/_logs/2017-09-21T20_07_55_605Z-debug.log
:installJBrowsePlugins FAILED

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/deepak.unni3/GIT/apollo-nathandunn-too/build.gradle' line: 296

* What went wrong:
Execution failed for task ':installJBrowsePlugins'.
> Process 'command 'npm'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

While adding a plugin from GitHub fails, Node 8 reports a different error from Node 7.

**Comment by deepakunni3** [comment]
@nathandunn Now the build works (after merging in master).

Tested with Node v7.10.1 and Node v8.4.0.
Tested with plugins that have git@github.com and https://github.com type URLs.

But I still run into the issue where `./setup.sh` runs before jbrowse is downloaded (or copied).

**Comment by deepakunni3** [comment]
Interestingly enough, now the `setup.sh` error happens only when the repository is freshly cloned.

After that repeated tries don't show this error anymore.

**Comment by nathandunn** [comment]
Using no plugins and: 
  		url= "https://github.com/gmod/jbrowse"

- [x] Works with node version 8.5 on initial load 
   - [ ] works on repeated load version 8.5
- [ ] Works with node version 6?
  - [ ] and repeated loads
- [ ] Works with node version 7?
  - [ ] and repeated loads
- [ ] Works with node version 5?
  - [ ] and repeated loads

With the plugin:

```
       WebApollo{
           included = true
       }
//       NeatHTMLFeatures{
//           included = true
//       }
//       NeatCanvasFeatures{
//           included = true
//       }
       RegexSequenceSearch{
           included = true
       }
       HideTrackLabels{
           included = true
       }
//       MyVariantInfo {
//           git = 'https://github.com/GMOD/myvariantviewer'
//           branch = 'master'
//           alwaysRecheck = "true"
//           alwaysPull = "true"
//       }
//       NAL_CSS {
//                 git = 'https://github.com/NAL-i5K/NAL_CSS'
//                 branch = 'master'
//           alwaysPull = true
//         alwaysRecheck = true
//       }
//       GCContent {
//           git = 'https://github.com/elsiklab/gccontent'
//         branch = 'master'
//           alwaysPull = true
//         alwaysRecheck = true
//       }
```

- [x] Works with node version 8.5 on initial load 
   - [ ] works on repeated load version 8.5
- [ ] Works with node version 6?
  - [ ] and repeated loads
- [ ] Works with node version 7?
  - [ ] and repeated loads
- [ ] Works with node version 5?
  - [ ] and repeated loads

**Comment by nathandunn** [comment]
Merging to simplify novel clone testing

**Pull request merged**
