### PR TITLE
Pluggable jbrowse build

### PR DESCRIPTION
**Pull request by nathandunn**
Uses gradle to wrap shell and ant for #926

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3   Can you take a look at this?  Basically needs to be tested for deploy, run-local and test (by someone other than me).    I left ```apollo release``` the same, but maybe Colin can take a look, as I'm a little hazy on how that should go together.

**Comment by deepakunni3** [comment]
@nathandunn `apollo deploy` and `apollo run-local` builds successfully*. 

But, during the build, there seems to be a problem while handling NeatHTMLFeatures:

```
Evaluating plugin NeatHTMLFeatures=[included:true]
ERROR: There is a problem with the plugin at jbrowse-download/plugins/NeatHTMLFeatures!
```

This error doesn't break the build and the outcome is that in the webapp I cannot see the Jbrowse view.

**Comment by nathandunn** [comment]
Ah . .  sometimes the git clone operation stops inappropriately.  I changed the exception so that it stops the entire build.

**Comment by nathandunn** [comment]
I'll push it when I have a chance to do look at the release code a bit later.

**Comment by nathandunn** [comment]
@deepakunni3   This is ready to review again.  If it fails the clone it should die completely and you can restart it.

**Comment by deepakunni3** [comment]
@nathandunn `apollo deploy` still fails, but for a different reason.

The full stack trace: https://gist.github.com/deepakunni3/00764bde80fa80b5eaa0

**Comment by nathandunn** [comment]
Thanks.  I’ll try some more denovo builds before I have you try it again. 

Nathan

**Comment by deepakunni3** [comment]
@nathandunn Looks good! :+1:

**Comment by nathandunn** [comment]
Hmm . . its still ignoring some of the plugins . . or I configured incorrectly . . . I'll take another look at that.

**Pull request merged**
