### PR TITLE
Fix error in remote org update

### PR DESCRIPTION
**Pull request by abretaud**
So I've tested the last commit of #2245, and there was an error, so here's a fix

### CODE REVIEW

**Comment by abretaud** [comment]
There's also a PR in python-apollo to implement it there too: https://github.com/galaxy-genome-annotation/python-apollo/pull/16

**Comment by nathandunn** [comment]
Cheers.  I noticed that bug as well and was on my way to fix it today in #2249 / #2248 . . I'll test this.

**Comment by nathandunn** [comment]
@abretaud  This fix one case.   However, in the case of a regular admin user, the `request.getFile` method doesn't exist because the request context is different than through the API.  

I'll merge this in and then fix that.

**Comment by nathandunn** [comment]
(to reproduce #2248, you basically can't make a change through the interface).  I'll fix that today and hopefully that fix won't break anything further.

**Pull request merged**
