### PR TITLE
Fix issues with sequence alterations in reverse complement view

### PR DESCRIPTION
**Pull request by deepakunni3**
Related to #1228

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn Ready for test and review.

**Comment by monicacecilia** [comment]
@nathandunn @deepakunni3 Please take a break on reviewing / merging this one for a moment. I'm reviewing a few things on the reverse complement products. I'm using 2.1.0-SNAPSHOT on icebox (I hope this is up-to-date).

**Comment by nathandunn** [comment]
@monicacecilia  Let's do a final review when we get to the end.   We're still kind of in the middle of these changes and I think we should keep going until we have something that is roughly correct.

**Comment by nathandunn** [comment]
@deepakunni3  These changes look and and are consistent with the other feature changes.

**Comment by monicacecilia** [comment]
@nathandunn I don't agree. If it is 'roughly' and not 'completely' correct, then it is simply wrong.

**Pull request merged**
