### PR TITLE
able to colorize start / stop codons

### PR DESCRIPTION
**Pull request by nathandunn**
- [x] colorize stop codons
- [x] colorize start codons
- [x] assess performance
- [x] use start / stop codons the translation table that the sequence track has access to already
   - [x] add method (in addition to get_translation_table) to also get start and stop codons, maybe as part of the same response
- [x] implement CSS class colors

### CODE REVIEW

**Comment by nathandunn** [comment]
screen shot 2018-01-19 at 1 47 35 pm

**Comment by nathandunn** [comment]
Start / stop codons not included when pulling the translation table out.  Will need to add a request for that, as well.

**Comment by nathandunn** [comment]
screen shot 2018-01-23 at 10 34 54 am

**Comment by nathandunn** [comment]
@deepakunni3  Would you mind reviewing and testing it when you get a moment?  If any of my naming seems funny let me know.  Ended up being embarrassingly easy.

Thanks!

**Comment by deepakunni3** [comment]
@nathandunn Tested and looks good.  👍 

I made some changes to the CSS.

**Pull request merged**
