### PR TITLE
Fix improper interpretation of dot notation from URL

### PR DESCRIPTION
**Pull request by deepakunni3**
@nathandunn Hopefully this should fix the issue we were seeing with dot notation.

Ready for test and review.

### CODE REVIEW

**Comment by nathandunn** [comment]
Fixes #1839

**Comment by nathandunn** [comment]
I don't see anything fundamentally wrong, but redirects are a problem when authenticating, though I don't see anything in your code that would affect that behavior.  By this I mean:
 
    http://localhost:8080/apollo/annotator/loadLink?loc=scf7180000302113:425429..426136&organism=volvox&tracks=DNA,genes&addStore.store1.type=JBrowse/Store/SeqFeature/GFF3&addStore.store1.urlTemplate=http://localhost/volvox.gff3&addTracks.store1.label=genes&addTracks.store1.type=JBrowse/View/Track/HTMLFeatures&highlight=&addBookmarks.bookmark1.start=3000&addBookmarks.bookmark1.end=4000&addBookmarks.bookmark1.ref=ctgA

Becomes:

    http://localhost:8080/annotator/index?clientToken=2238341278342115451875126135&tracks=DNA,genes&addStore.store1.type=JBrowse/Store/SeqFeature/GFF3&addStore.store1.urlTemplate=http://localhost/volvox.gff3&addTracks.store1.label=genes&addTracks.store1.type=JBrowse/View/Track/HTMLFeatures&highlight=&addBookmarks.bookmark1.start=3000&addBookmarks.bookmark1.end=4000&addBookmarks.bookmark1.ref=ctgA

ie., it drops the **/apollo/** during the redirect.  I'll recheck tomorrow as it may be something else I'm doing wrong.

Do you have any sample test URLs? 

The test-cases I have are:
- [x] "public genome view" / jbrowse
- [ ] loadLink when logged in
- [ ] loadLink when logged out

**Comment by deepakunni3** [comment]
Scenarios to test:

1A. URL with urlTemplate as a http link (logged in) - browser fails
1B. URL with urlTemplate as a http link (logged out) - works

```
http://localhost:8090/apollo/volvox/jbrowse/index.html?&loc=ctgA%3A1..37601&addStore.mystore.type=JBrowse/Store/SeqFeature/GFF3&addStore.mystore.baseUrl=.&addStore.mystore.urlTemplate=http://localhost/volvox.gff3&addTracks.mystore.label=volvox_genes_gff&addTracks.mystore.key="Volvox test!"&addTracks.mystore.type=JBrowse/View/Track/CanvasFeatures
```

2A. URL with urlTemplate as {dataRoot}/raw/volvox/volvox.gf3 (logged in) - works
2B. URL with urlTemplate as {dataRoot}/raw/volvox/volvox.gf3 (logged out) - works

```
http://localhost:8090/apollo/volvox/jbrowse/index.html?&loc=ctgA%3A1..37601&addStore.mystore.type=JBrowse/Store/SeqFeature/GFF3&addStore.mystore.baseUrl=.&addStore.mystore.urlTemplate={dataRoot}/raw/volvox/volvox.gff3&addTracks.mystore.label=volvox_genes_gff&addTracks.mystore.key="Volvox test!"&addTracks.mystore.type=JBrowse/View/Track/CanvasFeatures
```

2C. URL with urlTemplate as data/raw/volvox/volvox.gff3 (logged in) - works
2D. URL with urlTemplate as data/raw/volvox/volvox.gff3 (logged out) - works

```
http://localhost:8090/apollo/volvox/jbrowse/index.html?&loc=ctgA%3A1..37601&addStore.mystore.type=JBrowse/Store/SeqFeature/GFF3&addStore.mystore.baseUrl=.&addStore.mystore.urlTemplate=data/raw/volvox/volvox.gff3&addTracks.mystore.label=volvox_genes_gff&addTracks.mystore.key="Volvox test!"&addTracks.mystore.type=JBrowse/View/Track/CanvasFeatures
```

3A. URL with loadLink with urlTemplate as a http link (logged in) - browser fails 
3B. URL with loadLink with urlTemplate as a http link (logged out) - browser fails

```
http://localhost:8090/apollo/annotator/loadLink?loc=scf7180000302113:425429..426136&organism=Volvox&tracks=DNA,genes&addStore.store1.type=JBrowse/Store/SeqFeature/GFF3&addStore.store1.urlTemplate=http://localhost/volvox.gff3&addTracks.store1.label=genes&addTracks.store1.type=JBrowse/View/Track/HTMLFeatures&highlight=&addBookmarks.bookmark1.start=3000&addBookmarks.bookmark1.end=4000&addBookmarks.bookmark1.ref=ctgA
```

3C. URL with loadLink with urlTemplate as {dataRoot}/raw/volvox/volvox.gff3 (logged in) - browser shows but track fails due to improper parsing of urlTemplate
3D. URL with loadLink with urlTemplate as {dataRoot}/raw/volvox/volvox.gff3 (logged out) - browser shows but track fails due to improper parsing of urlTemplate

```
http://localhost:8090/apollo/annotator/loadLink?loc=scf7180000302113:425429..426136&organism=Volvox&tracks=DNA,genes&addStore.store1.type=JBrowse/Store/SeqFeature/GFF3&addStore.store1.urlTemplate={dataRoot}/raw/volvox/volvox.gff3&addTracks.store1.label=genes&addTracks.store1.type=JBrowse/View/Track/HTMLFeatures&highlight=&addBookmarks.bookmark1.start=3000&addBookmarks.bookmark1.end=4000&addBookmarks.bookmark1.ref=ctgA
```

3E. URL with loadLink with urlTemplate as data/raw/volvox/volvox.gff3 (logged in) - browser shows but track fails due to improper parsing of urlTemplate
3F. URL with loadLink with urlTemplate as data/raw/volvox/volvox.gff3 (logged out) - browser shows but track fails due to improper parsing of urlTemplate

```
http://localhost:8090/apollo/annotator/loadLink?loc=scf7180000302113:425429..426136&organism=Volvox&tracks=DNA,genes&addStore.store1.type=JBrowse/Store/SeqFeature/GFF3&addStore.store1.urlTemplate=data/raw/volvox/volvox.gff3&addTracks.store1.label=genes&addTracks.store1.type=JBrowse/View/Track/HTMLFeatures&highlight=&addBookmarks.bookmark1.start=3000&addBookmarks.bookmark1.end=4000&addBookmarks.bookmark1.ref=ctgA
```

**Comment by nathandunn** [comment]
This version worked by pre-pending:

    http://localhost:8080/apollo/annotator/index?clientToken=8888569771070242566860413218&addStore.store1.type=JBrowse%2FStore%2FSeqFeature%2FGFF3&addStore.store1.urlTemplate=apollo%2FJBrowse%2Fraw%2Fvolvox%2Fvolvox.gff3&addTracks.store1.label=genes&addTracks.store1.type=JBrowse%2FView%2FTrack%2FHTMLFeatures&highlight=&addBookmarks.bookmark1.start=3000&addBookmarks.bookmark1.end=4000&addBookmarks.bookmark1.ref=ctgA+View+changes

**Comment by nathandunn** [comment]
so if it detect this urlTemplate:

   &addStore.store1.urlTemplate=raw%2Fvolvox%2Fvolvox.gff3

it should make it into this one, but prepending the contextPath:

    &addStore.store1.urlTemplate=%2Fapollo%2FJBrowse%2Fraw%2Fvolvox%2Fvolvox.gff3

**Comment by deepakunni3** [comment]
http://localhost:8090/apollo/volvox/jbrowse/index.html?&loc=ctgA%3A1..37601&addStore.mystore.type=JBrowse/Store/SeqFeature/GFF3&addStore.mystore.baseUrl=.&addStore.mystore.urlTemplate=data/raw/volvox/volvox.gff3&addTracks.mystore.label=volvox_genes_gff&addTracks.mystore.key="Volvox test!"&addTracks.mystore.type=JBrowse/View/Track/CanvasFeatures

**Comment by deepakunni3** [comment]
@nathandunn The docs have been updated but feel free to add more information if needed.

**Pull request merged**
