### PR TITLE
(2h) Delete all features for organism

### PR DESCRIPTION
**Pull request by nathandunn**
Please review and merge.  

Needed for #539  #547 and and #562 . . . 

SQL is executed like this:

session.createSQLQuery("delete from feature_grails_user where EXISTS (select 'x' from feature_grails_user fgu JOIN feature f ON fgu.feature_owners_id=f.id join feature_location fl on fl.feature_id=f.id join sequence s on s.id = fl.sequence_id join organism o ON o.id = s.organism_id where o.id = ${organism.id})").executeUpdate()

Also FYI @deepakunni3  for future reference.

### CODE REVIEW

**Comment by cmdcolin** [comment]
So, dumb question, is there really not a more hibernatey way of doing this?

**Comment by cmdcolin** [comment]
And also, if i recall correctly, this whole issue with problems deleting features was caused be changing the "fetchType : join" in Feature.groovy (see #539 )

Do we consider this fetchType optimization important enough to cause these problems?

I personally considered using critera queries in specific locations to optimize queries in specific locations rather than changing the fetchType globally.

**Comment by nathandunn** [comment]
Not a dumb question at all.  A lot of folks hate on hibernate because it doesn't do this part well (bulk updates of sql tables ignoring the running server) . . 

Yes.  You could iterate through each feature.   In general, hibernate is great at maintaining proper object relationships, managing transactions, caching, etc. while respecting multiple threads and levels of transactions.    I've done batch loading with it, as well, but it is not what its good at and it would take a lot longer since its checking the keys and relationships in memory.    

As an aside, I also wanted to avoid using in() notation as much as possible, as it can be very slow for very large groups.

**Comment by nathandunn** [comment]
You have be able to do something with HQL . . but its still trying to manage memory / relationships in the VM, which is complexity we don't really need.

**Comment by nathandunn** [comment]
> Do we consider this fetchType optimization important enough to cause these problems?

I don't think that this would have caused enough problems / benefits either way.

**Comment by nathandunn** [comment]
@cmdcolin   Can we merge this yet?

**Comment by cmdcolin** [comment]
Is this just a web service that will be called from some script?

I mean, I guess you have a test confirming expected behavior, so we can interatively improve code techniques.

**Comment by nathandunn** [comment]
Yep and yep.

**Pull request merged**
