### PR TITLE
Redo group user ui

### PR DESCRIPTION
**Pull request by nathandunn**
This is for #592  . . 

@deepakunni3   Can you merge this in if it looks good.   There are a few places I used the "alerts", so you might need to fix those (I wasn't sure what your final solution was for it).

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn The UI for manipulating groups looks good. 

But there are couple of issues:
1. If a group has existing user memberships, it can't be deleted. The server doesn't throw any exception and neither is there any alert raised to the user.
2. When I try to delete an existing group (a group that was created before testing this branch), the server throws an exception:

```
| Error 2015-10-15 20:02:54,488 [http-bio-8090-exec-3] ERROR spi.SqlExceptionHelper  - ERROR: update or delete on table "user_group" violates foreign key constraint "fk_hycx5el5itt1lqidt532shkpj" on table "permission"
  Detail: Key (id)=(14401) is still referenced from table "permission".
| Error 2015-10-15 20:02:54,495 [http-bio-8090-exec-3] ERROR errors.GrailsExceptionResolver  - PSQLException occurred when processing request: [POST] /apollo/group/deleteGroup/ - parameters:
data: {"id":14401, "name":"group2", "numberOfUsers":0, "users":[], "organismPermissions":[{"Amel":{"organism":"Amel", "ADMINISTRATE":false, "WRITE":false, "EXPORT":true, "READ":false, "groupId":14401, "id":14405}}]}
ERROR: update or delete on table "user_group" violates foreign key constraint "fk_hycx5el5itt1lqidt532shkpj" on table "permission"
  Detail: Key (id)=(14401) is still referenced from table "permission".. Stacktrace follows:
Message: ERROR: update or delete on table "user_group" violates foreign key constraint "fk_hycx5el5itt1lqidt532shkpj" on table "permission"
  Detail: Key (id)=(14401) is still referenced from table "permission".
    Line | Method
->> 2161 | receiveErrorResponse in org.postgresql.core.v3.QueryExecutorImpl
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1890 | processResults       in     ''
|    255 | execute . . . . . .  in     ''
|    559 | execute              in org.postgresql.jdbc2.AbstractJdbc2Statement
|    417 | executeWithFlags . . in     ''
|    363 | executeUpdate        in     ''
|    195 | $tt__deleteGroup . . in org.bbop.apollo.GroupController
|    198 | doFilter             in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain         in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call . . . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall               in org.apache.shiro.subject.support.SubjectCallable
|     83 | call . . . . . . . . in     ''
|    383 | execute              in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal . . in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter             in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1142 | runWorker . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    617 | run                  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . .  in java.lang.Thread
```

3. When I rename a group, it doesn't persist in the database. Upon refresh of the page or switching tabs, the group name will remain unchanged.

**Comment by nathandunn** [comment]
Thanks for finding this.  I’ll try go get it fixed tomorrow. 

Thanks,

Nathan

**Comment by nathandunn** [comment]
@deepakunni3   Thanks . . I fixed both of these.

**Comment by cmdcolin** [comment]
Update changelog with change?

**Comment by nathandunn** [comment]
I think I'm going to add the changelog last as part of this bug (but feel free to do it as you go): https://github.com/GMOD/Apollo/issues/586

**Comment by cmdcolin** [comment]
I think updating changelog as things are fixed is good. I can add the updates if you want

**Comment by nathandunn** [comment]
Sure.

Nathan

**Pull request merged**
