### PR TITLE
Fix database migration for 2.0.1

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds a precondition to the migration script to make sure that some changesets are only applied if upgrading from 2.0.0

See

#616

### CODE REVIEW

**Comment by cmdcolin** [comment]
@nathandunn this appears to fix the problem

**Comment by nathandunn** [comment]
Thanks . . I’ll take a look . . I Was hoping to do one at the very top, but that didn’t quite work out the way I planned. 

Nathan

**Comment by cmdcolin** [comment]
It's possible to combine the changesets, so really the whole file could have the precondition at the top. Probably not really required though

**Comment by nathandunn** [comment]
works great!

**Pull request merged**
