### PR TITLE
Fix for history merges and splits

### PR DESCRIPTION
**Pull request by nathandunn**
Fix for #792 and #795.

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3   Can you review and test this.   This is to fix #792 and #795 .  

Thanks.

**Comment by deepakunni3** [comment]
Couple of issues observed as illustrated by the attached pdf.
[issues_on_pull_request_842.pdf](https://github.com/GMOD/Apollo/files/115009/issues_on_pull_request_842.pdf)

**Comment by nathandunn** [comment]
Bugs identified by Deepak:
- [ ] **Bug 1**: add A1 B1, A2 B2,  merge AB, undo AB (A2 B2), undo B2 (A2 B1), undo A2 (A1 B1 expected, but something is VERY wrong with A1 model)
   - [ ] generate test
   - [ ] fix 
- [ ] **Bug 2** (similar to above . . I think that the "second" undo in a uniform tree causes problems) add A1 B1, A2 B2,  merge AB, undo AB (A2 B2), undo at Aa (A1 B2), undo at B2 (A1 B1 expected, but something is VERY wrong with the B2 model)
   - [ ] generate test
   - [ ] fix 
- [ ] **Bug 3**: add A1 B1, modify B1 (delete exon A1 B2), modify A1 (Set readthrough stop codon = A2 B2), merge (expected AB, but fails) . .  might be a separate bug
- [ ] **Bug 4**: add A1 B1, modify A1 (SEB = A2 B1), delete exon in A2 (A3 B1), SEB B1 (A3 B2), merge (AB), undo (A3 B2), show history shows the history for the wrong value
   - [ ] generate test
   - [ ] fix

**Comment by nathandunn** [comment]
@deepakunni3   I think that this is ready to review.

**Comment by nathandunn** [comment]
From @deepakunni3  : 
The issue always comes up on the 3' transcript and not the 5' transcript.
[issues_on_pull_request_842_v2.pdf](https://github.com/GMOD/Apollo/files/119693/issues_on_pull_request_842_v2.pdf)

**Comment by nathandunn** [comment]
This bug is reproduced by this, where it is grabbing the other index:

```
 assert uniqueNames.remove(uniqueName)
        uniqueNames.each {
            currentIndex = Math.max(getCurrentFeatureEventIndex(it), currentIndex)
        }
        int count = currentIndex + countForward
```

**Comment by nathandunn** [comment]
The problem is that it calculates the currentEventIndex incorrectly.  I think its picking up both indices and taking the max.

**Comment by nathandunn** [comment]
@deepakunni3   I fixed this.   I'm going to go ahead and merge it and we can re-open a new issue if it still fails.   Thanks for the detailed checking.

**Comment by deepakunni3** [comment]
@nathandunn Looks good :+1:

**Pull request merged**
