### PR TITLE
Cleanup Changelog

### PR DESCRIPTION
**Pull request by cmdcolin**
I just wanted to update the changelog a little bit to...

- make formatting consistent
- add missing things
- divide features from RC1,RC2,RC3

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   I think the changes you added are fine, but I think you didn't merge in the changes that were there.

**Comment by nathandunn** [comment]
If you did merge the changes (and I am just sense) let me know and I'll take another look.

**Comment by nathandunn** [comment]
@cmdcolin  "dense" not "sense", I just didn't see that you moved these to RC1.

**Comment by cmdcolin** [comment]
Oh I sorry. accidentally pushed this branch into 2.0.0 so it got "automerged" but i meant for it to still be a pull request. didn't mean to bypass the pull request process.

I think I included all the changes you made on the 2.0.0 but I reformatted them a bit (I tried to use more action words like "fixed" in the bug fixes section and "added" in the features section, instead of just using the raw issue titles, since I think it sort of makes what was done clearer.)

Anyways, I can make a new pull request or just re-add the changes to 2.0.0

**Comment by nathandunn** [comment]
Just re-add the changes to 2.0.0.  .. . I think that all of the fixes were good.  I had just started a draft in the hopes that other folks would continue to fix it.

**Comment by cmdcolin** [comment]
Sounds good. That's basically what I would do too :) continuous improvement of the release notes/changelog is pretty much fine with me up until the version is released

**Comment by cmdcolin** [comment]
So ya, I re-added it. pull request closed

**Pull request merged**
