### PR TITLE
Delete features from organism

### PR DESCRIPTION
**Pull request by cmdcolin**
See #636

This commit takes a different approach towards deleting features from an organism

It selects features from an organism using criteria queries, and then simply uses hibernate functions instead of raw SQL, which I think is much more elegant.

It also does away with the fetchMode join in Feature.groovy. We have talked about fetchMode fairly frequently but I think it breaks the Feature objects stability

### CODE REVIEW

**Comment by cmdcolin** [comment]
Woop. Still fails unit tests. Will check to see if it is salvageable

**Comment by nathandunn** [comment]
Let me know if / when you can fix this and I’ll take look.  

Nathan

**Comment by cmdcolin** [comment]
@nathandunn I think it is fixed now! 34eab9b fixed the integration tests

**Comment by nathandunn** [comment]
Looks to be working.  Much more elegant! :+1:

**Pull request merged**
