### PR TITLE
Add ability to force assignment of a transcript to a gene

### PR DESCRIPTION
**Pull request by deepakunni3**
PR Addresses feature requests made in #1816 

The ability to,
- assign/associate a transcript to a selected gene
- remove/dissociate a transcript from its own gene

can be performed from the right-click menu.

For configuring an exon overlapper, instead of the default CDS overlapper, add the following to your Apollo config:

```
apollo {
    transcript_overlapper = "exon"
}
```

### CODE REVIEW

**Comment by nathandunn** [comment]
screen shot 2018-01-19 at 3 12 19 pm


screen shot 2018-01-19 at 3 09 43 pm
screen shot 2018-01-19 at 3 09 23 pm
screen shot 2018-01-19 at 3 09 16 pm
screen shot 2018-01-19 at 3 08 52 pm

**Comment by nathandunn** [comment]
@deepakunni3  This causes an error here: 

screen shot 2018-01-19 at 3 13 46 pm

```
 Conditions met
2018-01-19 15:14:23,271 [Actor Thread 9] DEBUG apollo.FeatureService  - all sorted transcripts: []
| Error 2018-01-19 15:14:23,271 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - CAUGHT ERROR through websocket call: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
| Error 2018-01-19 15:14:23,271 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - exception java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
| Error 2018-01-19 15:14:23,271 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - exception message Index: 0, Size: 0
| Error 2018-01-19 15:14:23,271 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - username ndunn@me.com
| Error 2018-01-19 15:14:23,272 [Actor Thread 9] ERROR apollo.AnnotationEditorController  - error destination message: /topic/AnnotationNotification/user/ndunn@me.com
```

But I think if you fix the gene association, it should fix the rest.  Still testing the other association code.

**Comment by nathandunn** [comment]
Actually I get that index 0 error quite abit.   To reproduce:

- create two overlapping isoforms (with the default overlapping strategy)
- disassociate both from genes (as opposed to one)
- try to move exon boundaries
- expect it to move, get the out of bounds error instead (with stracktrace log given, as well)

**Comment by deepakunni3** [comment]
@nathandunn Thanks for testing. I'll see whats going on

**Comment by nathandunn** [comment]
Nice!  

screen shot 2018-01-22 at 2 59 09 pm

Tested unforcing and forcing.   All worked great.  Just pushed a few minor changes to the docs.

**Comment by nathandunn** [comment]
CDS case (was the exon case above): 

screen shot 2018-01-22 at 3 02 31 pm
screen shot 2018-01-22 at 3 02 20 pm

**Pull request merged**
