### PR TITLE
Translation table support - fix for #757

### PR DESCRIPTION
**Pull request by nathandunn**
Fix for #757  . . 

@erasche   You should be able to pull this in and confirm that it works. 

@cmdcolin   if you could review this sometime this week, that would be great.  Thanks.

### CODE REVIEW

**Comment by erasche** [comment]
Confirmed working for me. Still throws the little warnings but that's fine. That can be a small bug for me to whet my teeth on. 

selection_520

**Comment by nathandunn** [comment]
I see . . . you mean the indication of the "non-canonical splice sites” even though you’ve updated the translations? 

Do you think that is new in Web Apollo 2? 

Nathan

**Comment by erasche** [comment]
Ah, wasn't quite sure what those were (since we'd never used them and they don't have any hover text explaining what they are). I doubt that this is new to WA2.

Is there something different I should be doing with our gene model or a setting I should be changing since those aren't so appropriate to our use case? 

(Background: Our lab is still somewhat new to the world of gff3, we're still trying to sort out what portions of the full gene model we need to be using or not using to capture the information we wish to capture. Between all the different things I've seen "in the wild", trying to have things display nicely for our users in JBrowse, and trying to decide what is a problem with our gene model and what's a problem with upstream not expecting phage/viral data ... it's all a bit confusing)

**Comment by cmdcolin** [comment]
Do your genes have any bona-fide splice sites? If I remember from your other post, I think you had your GFF containing sub-features for a shine-dalgerno sequence. Perhaps Apollo is converting those to an exon or something similar, which is confusing it. It has actually always been kind of confusing how to present promoters and such things in gff and in this case perhaps it should not be included as a subfeature of your gene (maybe you can confirm if this is the case)

**Comment by erasche** [comment]
- Nope, no splice sites whatsoever. 
- Yes, we'd been trying to store promoter information with a `Shine_Dalgarno_sequence` child of the gene object. We'd like to track that information, but definitely aren't sure what to do with it

**Comment by cmdcolin** [comment]
Gotcha. Maybe we can start a new thread for experimenting with maintaining that extra info in the annotation. I don't recall if it's been done before.

If so I think this looks good @nathandunn

**Comment by nathandunn** [comment]
I think the problem is that the it is using the alternate codes correctly on the server, but on the client they are still unrecognized (and using the older version).  However, it looks mostly like (if you are using 11) that it is adding start codons only . . which is odd, but possibly correct.

https://github.com/nathandunn/Apollo/blob/translation_table_support/web-app/translation_tables/ncbi_11_translation_table.txt

I agree.  Was thinking of creating a separate issue for this.

**Pull request merged**
