### PR TITLE
Add instructor permission level

### LINKED ISSUE #1178: add user/organism-admin permission level
Related to #771 and related to [this thread](http://comments.gmane.org/gmane.science.biology.gmod.apollo/1920).  

I think that the proposal would be to add another permission level between organism-admin (when you select a user as an admin for a single organism) and "write".  A super-admin would remain the same and be required to add users to groups (so super-admin,organism-admin,**user-admin**,write,export,read).  user-admin would be the new one.

Requirements for the new permission level:
- create users that are automatically assigned to an organism
- user tab would show up, but only those that share the organism that hey are a user-admin on 
- group tab would show up, but only those of the same group would be visible
- only the organisms available would show up, and would have minimal editable fields (if any)
- no global system permissions would be available
- reports would be available, but only for related organisms and users (this might be VERY messy, however)

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1178

FYI @Yating-L

### CODE REVIEW

**Comment by nathandunn** [comment]
FYI @Yating-L

**Comment by nathandunn** [comment]
FYI, this might be of interest to @childers , @abretaud , @erasche  , @loraine-gueguen

**Comment by nathandunn** [comment]
@deepakunni3  I think this is ready for review as you have time.

**Comment by Yating-L** [comment]
There're some issues when login with an instructor role, who does not have an organism: 
* tabs not show: users, organisms
* forced log out after a few sec
I am working on this and will push the code later

**Comment by nathandunn** [comment]
Nice catch.

**Comment by nathandunn** [comment]
@Yating-L  Was that the only change needed or are you still working on it?

**Comment by erasche** [comment]
Doesn't look like something we'd use but still, cool!

**Comment by Yating-L** [comment]
@nathandunn There's an issue/bug on update membership. I am working on it.

**Comment by nathandunn** [comment]
Alright.  Just let me know when it’s ready to test / review. 

Nathan

**Comment by Yating-L** [comment]
@nathandunn The issues are fixed. However, I got some feedback from someone who has experience in teaching classes: 
* can we (as instructors) create an instructor who can manage the same group of users, userGroups, and organisms? The use case is that when a class has two or more instructors. 
* transfer ownership to another instructor when faculty leaves the institution.
I am not sure if this is a general use case that you want to have? If so, shall we use a new branch to implement this feature?

**Comment by nathandunn** [comment]
> can we (as instructors) create an instructor who can manage the same group of users, userGroups, and organisms? The use case is that when a class has two or more instructors.

I would use the userGroups for this.  ie., create two users with global admin “instructor” and then add them to a “Clade A Instructors” group and give members of that group Organism Admin instructor privileges. 

> transfer ownership to another instructor when faculty leaves the institution.
> I am not sure if this is a general use case that you want to have? If so, shall we use a new branch to implement this feature?

You can just create an instructor with the same permissions, or change the current instructors user credentials.   The super-admin can change all of that stuff.

**Comment by Yating-L** [comment]
@nathandunn The current stage works in general use cases. Feel free to merge it. 
I am still working on some advanced use cases, such as 
* let multiple instructors manage the students in a userGroup. 
I will send a pull request when this is done.

**Comment by Yating-L** [comment]
@nathandunn Now a userGroup can have multiple group admins.
I modified a couple things: added "admin" field to userGroup table, added a new tab for userGroup UI to update the userGroup admin, and add some functions for a userGroup admin to manage users within the group.

**Comment by Yating-L** [comment]
@nathandunn I am wondering if you're going to merge this branch into the next release? If so, do you have an approximate time for the next release? Thank you!

**Comment by nathandunn** [comment]
@Yating-L If its ready for review, I'll merge it as soon as I have time to review it (next week at the very latest).    

Releases happen when they happen, so it would definitely be rolled into the next release, but not sure when that will be.

**Comment by nathandunn** [comment]
@Yating-L  is it ready for review?

**Comment by Yating-L** [comment]
@nathandunn Not yet. I still found a few bugs just now. Sorry that it took longer than I expect.

**Comment by nathandunn** [comment]
No problem.  Its always a pleasant surprise when it is somehow quicker than I expected ;)

**Comment by Yating-L** [comment]
@nathandunn Okay, now is ready for review.

**Comment by nathandunn** [comment]
Excellent.  I’m booked up this week, but I’ve added it to the top of my list to take a look at next week.

**Comment by nathandunn** [comment]
@Yating-L   Looks good. I made a small fix here, disallowing all but the Global Admin from creating  Canned Comments and Statuses.  

https://github.com/GMOD/Apollo/pull/1841/commits/9837f5912a800c4a670d489f3fd32c142d2bcb95

If that is not accurate, we should change the permissions to INSTRUCTOR instead and getOrganismsForUser when calling.   Its a quick fix from my end, but you can probably fix it as well.

**Comment by Yating-L** [comment]
@nathandunn Looks good to me. Thank you for the review!

**Pull request merged**
