### PR TITLE
Remote organism update fix

### PR DESCRIPTION
**Pull request by abretaud**
I'm finally testing #2227 to update organism by uploading an archive
Just a typo in a variable name, + a (probably?) missing line in the archive handling

For some reason, the upload seems to fail even with these changes, I get this error:

```
{
    "error": "problem saving organism: java.lang.RuntimeException: org.codehaus.groovy.grails.web.converters.exceptions.ConverterException: Error converting Bean with class java.io.File"
}
```

I'm trying to get more details, any idea?

### CODE REVIEW

**Comment by nathandunn** [comment]
Could you send me the archive file? 

Nathan

**Comment by abretaud** [comment]
Bug found :) fixed in 3faebfa1b22a13cc552c25ee2d1c5c16a3d25dcc
I'm making a few more tests, I'll tell you when it's ok

**Comment by abretaud** [comment]
Latest commit is not yet tested, apart from that it should be good now, thanks for working on it!

**Comment by nathandunn** [comment]
@abretaud  Excellent.  Thanks for doing the final fix.

**Pull request merged**
