### PR TITLE
added better coloring for strand matches

### LINKED ISSUE #412: BAM (draggableAlignments) don't support color by strand or some other configuration
From this conversation with @mpoelchau (and a few others) :

http://gmod.827538.n3.nabble.com/bam-track-display-configuration-td4040828.html

We should have a way to display the strand in the BAM track.  Making Canvas tracks draggable would be one way.  Conversely, just coloring the BAM tracks appropriately as a default would probably also work.

### PR DESCRIPTION
**Pull request by nathandunn**
Fixes #412 

@childers  If you have a chance to look at this and let us know if similar matches for .cigarE / .cigar? would be helpful. 

This is a pretty simple fix.  You can also issue a separate PR / patch. 

@deepakunni3  I think this is ready for review.   Not sure what the history of why this wasn't done in the first place (in WA1) as it was pretty easy.

### CODE REVIEW

**Comment by nathandunn** [comment]
BWT, does this fix #1044 as well?   

I wanted this fix for #1619 (to check errors).

**Comment by nathandunn** [comment]
screen shot 2017-07-28 at 9 47 10 am
screen shot 2017-07-28 at 9 42 52 am

**Comment by deepakunni3** [comment]
@nathandunn It would be awesome if the color of the reads matched JBrowse/Alignment track.

Here is an image that shows the comparison of WebApollo/DraggableAlignments vs JBrowse/Alignment:
screen shot 2017-07-28 at 1 20 35 pm

color for forward strand aligned reads - `#EC8B8B`
color reverse strand aligned reads - `#898FD8`

Also, the span between two paired end reads should be a lighter shade,
screen shot 2017-07-28 at 1 46 17 pm

**Comment by nathandunn** [comment]
Okay.  I added a better coloring scheme.  Though the colors listed I believe were for non-matches:

JBrowse:
screen shot 2017-07-28 at 1 30 49 pm

New Apollo color schemas:
screen shot 2017-07-28 at 1 30 46 pm

**Pull request merged**
