### PR TITLE
Apollo readthedocs2

### PR DESCRIPTION
**Pull request by nathandunn**
@cmdcolin  can you merge this when you have a minute . . my earlier pull request was a fail as you can not actually change the base url (but you can change the rest). 

This are some additional changes for #640  .

### CODE REVIEW

**Comment by nathandunn** [comment]
The docs are here:  http://webapollo.readthedocs.org/en/apollo_readthedocs2/

**Comment by cmdcolin** [comment]
This is probably fine but I don't agree with editing past ChangeLog text. Those are supposed to just remain the same

**Comment by nathandunn** [comment]
good point . .  I'll revert that one

**Comment by nathandunn** [comment]
k . . . I reverted the changelog change . . . go ahead and merge it if it looks good

**Pull request merged**
