### PR TITLE
Annotator controller and REST services and check security  - #649

### PR DESCRIPTION
**Pull request by nathandunn**
@cmdcolin   Could you review this on Monday and pull it in.    Thanks!

### CODE REVIEW

**Comment by cmdcolin** [comment]
I have been generally opposed to code like this


    Feature parentFeature = feature.childFeatureRelationships*.parentFeature.first()


Because I think it indicates flaws in our object model. We should make it much more easy to access a parent feature.


Other things look ok, but I would like evidence of the use cases before and after the fix that I can validate

**Comment by nathandunn** [comment]
So, reading your comments and re-reading my code a couple of quick thoughts:

1 - ```Because I think it indicates flaws in our object model. We should make it much more easy to access a parent feature.```  I'd be curious any thoughts to improving this as this is a [pretty standard model close to GMOD](http://gmod.org/wiki/Chado_Sequence_Module#Names_of_Features).  Its more formalized here (and the call we should be using): https://github.com/GMOD/Apollo/blob/master/grails-app/services/org/bbop/apollo/FeatureRelationshipService.groovy#L37

Again, not opposed to changing it, but any improvement to this model that still allows us to annotate relationships separately would be good.   The one thought I have is that you could hide feature relationship as a many-many table between features.   We don't use rank or value and we only the "part_of" relationships.  If we use more relationships in the ontology, we could sub-class it, but I think that is unlikely.
  
2 - Validate-able use-cases . . this controller supports the annotator panel:  A) editing a feature name / description / symbol in the annotator panel.  B) editing the location of an exon in the annotator panel.

**Comment by cmdcolin** [comment]
The thing I'm getting at is why do we not have an API for getting the parent feature here?

An API flaw perhaps.

But it is an object model concern because you are inducing extra queries to get the parent feature when we should be able to get that info directly from the object

**Comment by cmdcolin** [comment]
> Validate-able use-cases . . this controller supports the annotator panel: A) editing a feature name / description / symbol in the annotator panel. B) editing the location of an exon in the annotator panel.

Why are these things going through annotatorcontroller instead of annotationeditorcontroller?

**Comment by nathandunn** [comment]
AnnotatorEditorController . . . everything in the JBrowse frame. 

AnnotatorController . . .. everything on the GWT AnnotatorPanel that is not in UserController, OrganismController, GroupController.   

1 - I need to annotate this in each
2 - we should probably move things around a bit.  Things like RequestHandlingService and AnnotatorEditorController are huge . .  possibly there is no avoiding it.   These were things moved directly out of AnnotationEdtiorService, so you can see the annotation mapping is as such in URL mapper.  Otherwise I would probably have split them up more:

  "/AnnotationEditorService"(controller:"annotationEditor",action: "handleOperation",params:params)

For the purposes of this code review, I think I can do 1 as I think that the explanation would be useful (even to someone who wrote it), but we can look at 2 at another time with a comprehensive refactor proposal as it is a fairly non-trivial refactor.

Nathan

**Comment by nathandunn** [comment]
I see.    We do have an API for doing this, but its on the service class because I moved it there.    I moved it there because you should only have direct relationships on the feature class itself, with few exceptions.  GORM objects should be dumb.    That part is correct.

The bigger question (please see the links) is whether it makes sense at all to use a feature relationship to bridge two features, since we really aren't actually annotating that information.  I've thought about this before, but I can't remember why I thought to leave it for now .  other than the large amount of work involved in doing it (esp. WRT to data migrations) . . and the even larger amount of work if we are wrong.

I can ask for clarification today, but that change won't come until at least 2.1 or 2.2 as it requires a significant rewrite and data migration.   However, I think it would also help performance, not just simplify the API.

**Comment by cmdcolin** [comment]
Ok I'll try and check out this out

**Comment by nathandunn** [comment]
I asked around about the necessity of FeatureRelationships . . . I opened an issue for discussion in #652.  We won't look at it until 2.2 (its an important schema change), but its definitely worth looking at again.

I'll push some documentation and service method changes.

**Comment by nathandunn** [comment]
@cmdcolin  I updated the doc and a method to use the service call instead.

**Comment by cmdcolin** [comment]
Thanks the service call looks much better

**Comment by nathandunn** [comment]
Should I merge it . . or did you want to test and merge it a bit later?

**Comment by cmdcolin** [comment]
This might have been a bug that existed for awhile but I don't think the code for modifying exon boundaries updates the longest ORF

That's why I was protesting against the existence of these methods in both AnnotatorController and AnnotationEditorController since this "pipeline" for doing essentailly the same things is duplicated

**Comment by cmdcolin** [comment]
I mean modifying the exon boundaries from the annotator panel.

The dragging exon boundaries code in the browser is ok

**Comment by cmdcolin** [comment]
In any case, this is not blocking so I'll just get in and merge this !

**Comment by nathandunn** [comment]
Good point.   Alternate pathways to the SAME functionality are not a bad thing, but the functionality should be identical. 

Let me refactor it so that they use the exact same method in RHS.   I’ll let you know hone I’m done. 

Nathan

**Comment by nathandunn** [comment]
Sounds good . .I'll do the (small) refactor on mainline.

**Pull request merged**
