### PR TITLE
initial fix #1468

### LINKED ISSUE #1468: Remote_user not catched everywhere
I have a small problem with remote_user auth. On a freshly opened browser (no cache), if I go first to 
apollo homepage (http://fqdn/apollo/), I get logged in correctly.

If I go first to other pages like this:
http://fqdn/apollo/annotator/loadLink?loc=scaffold2%3A172393..195794
http://fqdn/apollo/annotator/loadLink?organism=xxx
I get redirected to http://fqdn/apollo/auth/login, even though I entered my login/password in the browser login box

The workaround is to go first to the homepage before going to other pages.
In the apollo log I get only this when redirected to auth page:

```
2017-02-01 16:54:02,196 [http-apr-8080-exec-2] WARN  apollo.SecurityFilters  - Authentication failed
```

Do you have an idea why?

### PR DESCRIPTION
**Pull request by nathandunn**
initial fix #1468

@abretaud  This PR should fix it.  Let me know if not.  

@deepakunni3  If you could take a look and let me know if I didn't destroy anything.  Thanks!

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  If you could just check that it works like normal in normal authentication circumstances.  

@abretaud  can check the remote_user authentication case. 

I've done both a bit already and it seemed to be working.   Note the use-cases [checked here](https://github.com/GMOD/Apollo/issues/1468#issuecomment-276819317). 

Thanks.

**Comment by abretaud** [comment]
Thanks a lot! It looks ok for me, I included the patch in our apollo docker image

**Comment by deepakunni3** [comment]
@nathandunn Looks good for normal circumstances, as well.

**Comment by monicacecilia** [comment]
@nathandunn let's update staging with this for last bit of testing after merge. almost there.

**Comment by nathandunn** [comment]
@abretaud  @deepakunni3  Thanks.  

@monicacecilia   Will do.  I'm just testing web services, but everything looks good so far.

**Pull request merged**
