### PR TITLE
Release 2 0 4 ready

### PR DESCRIPTION
**Pull request by nathandunn**

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3   I'm going to go ahead and merge this, but I thought it might be easier to check this to make sure its correct it here, esp. the ChangeLog.

**Comment by deepakunni3** [comment]
@nathandunn Looks good.

**Comment by nathandunn** [comment]
👍

**Comment by monicacecilia** [comment]
Having done this merge is causing 'Master' to read that 2.0.4 has been released - not true- and that it can be downloaded - not true either. (I think that's the cause, in any case - from what I can see in the history of the Readme file. We have RCs, not 'latest' production release. Also the URL offered for download is incorrect, of course, because this tag does not yet exist: https://github.com/GMOD/Apollo/releases/tag/2.0.4

**Comment by nathandunn** [comment]
Yeah, maybe I’ll branch the release next time so it doesn’t do this.

**Comment by monicacecilia** [comment]
Yes, please.

**Pull request merged**
