### PR TITLE
updated documentation a bit

### PR DESCRIPTION
**Pull request by nathandunn**
I added an example build and a link to the JBrowse FAQ.   Let me know what you think or if you have any additions / suggestions.  I don't want to much doc to maintain, but I think that providing something like this might be helpful, esp. for folks not used to sysadmining their own systems.  If you think its overkill, let me know.

FYI @cmdcolin  @deepakunni3  @monicacecilia

### CODE REVIEW

**Comment by cmdcolin** [comment]
Maybe it might be worth making an Apollo FAQ ? :)

**Comment by nathandunn** [comment]
True . . not sure what would go in there.

**Comment by cmdcolin** [comment]
The FAQ can just answer questions about the setup, customization etc. Imagine yourself in the users shoes and look back over the mailing list :)

I can try and do it but it is honestly better if I have more free reign to edit docs. If I have to make a PR to make every tiny change, it becomes pretty annoying.

**Comment by nathandunn** [comment]
The tricky part is integrating the FAQ into the rest of the doc.   I think that readthedocs does a good job of providing search for the doc, but if we ever have a list of questions, we can always point back into the doc.

**Pull request merged**
