### PR TITLE
Updated text Info Editor Tooltips and labels.

### PR DESCRIPTION
**Pull request by monicacecilia**
- Updated text for Tooltips for "Name", "DBXRefs", "PubMed IDs" fields. 
- Also updated label for "PubMed IDs" table.

### CODE REVIEW

**Comment by monicacecilia** [comment]
Don @nathandunn could you please check that I didn't break anything? -- whenever you're ready. gracias!

**Comment by nathandunn** [comment]
Looked good, though I would recommend not putting links in. 

screen shot 2016-06-01 at 8 13 37 pm

**Comment by monicacecilia** [comment]
Links were already in before - I was hesitant to leave them in as well...
Let's remove them. Thanks!

On Wednesday, June 1, 2016, Nathan Dunn <notifications@github.com> wrote:

> Looked good, though I would recommend not putting links in.
>
> [image: screen shot 2016-06-01 at 8 13 37 pm]
> <https://cloud.githubusercontent.com/assets/751274/15732864/6dae7312-2835-11e6-8c67-b3ecd74ce5c9.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GMOD/Apollo/pull/1088#issuecomment-223185033>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABopvUhvMPN1DNv-qUfPWpCLK7YKzNyOks5qHkqRgaJpZM4IsHgZ>
> .
>


-- 
Mentorship Matters!
--
Monica Munoz-Torres, PhD.
Berkeley Bioinformatics Open-source Projects (BBOP)
Environmental Genomics and Systems Biology Division
Lawrence Berkeley National Laboratory

Mailing Address:
Lawrence Berkeley National Laboratory
1 Cyclotron Road Mailstop 977
Berkeley, CA 94720

**Comment by nathandunn** [comment]
Alright . . I'll do that in mainline though RC1 will have them.

**Comment by monicacecilia** [comment]
copy that.

On Wednesday, June 1, 2016, Nathan Dunn <notifications@github.com> wrote:

> Alright . . I'll do that in mainline though RC1 will have them.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GMOD/Apollo/pull/1088#issuecomment-223188847>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABopvd5FRH_jwsvBDNoDPo2oyiNfDPlZks5qHlMBgaJpZM4IsHgZ>
> .
>


-- 
Mentorship Matters!
--
Monica Munoz-Torres, PhD.
Berkeley Bioinformatics Open-source Projects (BBOP)
Environmental Genomics and Systems Biology Division
Lawrence Berkeley National Laboratory

Mailing Address:
Lawrence Berkeley National Laboratory
1 Cyclotron Road Mailstop 977
Berkeley, CA 94720

**Pull request merged**
