### PR TITLE
fixed removal of DbXrefs

### PR DESCRIPTION
**Pull request by nathandunn**
@deepakunni3  Can you review this when you have a chance?   Should handle #1163.

### CODE REVIEW

**Comment by deepakunni3** [comment]
@nathandunn verified that I can delete a DBXref entry from the information editor without any errors.

But one issue is that even if a DBXref is removed from the information editor, it is not deleted from the database. i.e. the entry in `feature_dbxref` table is removed but the dbxref itself is not deleted from the `dbxref` table.

**Comment by loraine-gueguen** [comment]
@nathandunn  Hi !
Do you plan to release 2.0.4 soon ?
This issue is a major limit for our apollo instance because the annotators are reviewing annotations directly loaded in the annotation track and need to remove bad dbxref when needed.
Thanks for the fix!
Loraine

**Comment by nathandunn** [comment]
@loraine-gueguen  We have started testing (we are on release candidate 2), so it could be this week or in a few weeks, depending on how this works.   Feel free to test as well.

**Comment by loraine-gueguen** [comment]
ok. Thanks !

**Pull request merged**
