### PR TITLE
fixes #1742

### LINKED ISSUE #1742: Apollo client being initialized twice
I see the following on the Apollo 2.0.7 demo:

screen shot 2017-08-31 at 2 28 50 pm

Note how there are redundant options in the View menu.

The console gives the following error:
```
Browser.js:1981 Error: Tried to register widget with id==menubar_powered_by_jbrowse but that id is already registered Error: Tried to register widget with id==menubar_powered_by_jbrowse but that id is already registered
    at Object.add (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dijit/registry.js:26:11)
    at Object.create (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dijit/_WidgetBase.js:428:13)
    at Object.postscript (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dijit/_WidgetBase.js:366:9)
    at new <anonymous> (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/_base/declare.js:406:7)
    at Object.postCreateMenus (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/plugins/WebApollo/js/main.js:718:33)
    at http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/plugins/WebApollo/js/main.js:222:23
    at http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/JBrowse/Browser.js:1979:29
    at signalListener (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/Deferred.js:37:21)
    at signalWaiting (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/Deferred.js:28:4)
    at Deferred.resolve (http://demo.genomearchitect.org/Apollo-staging/4126658216003575441700795384/jbrowse/src/dojo/Deferred.js:192:5) Error: Tried to register widget with id==menubar_powered_by_jbrowse but that id is already registered
    at Object.add (registry.js:26)
    at Object.create (_WidgetBase.js:428)
    at Object.postscript (_WidgetBase.js:366)
    at new <anonymous> (declare.js:406)
    at Object.postCreateMenus (main.js:718)
    at main.js:222
    at Browser.js:1979
    at signalListener (Deferred.js:37)
    at signalWaiting (Deferred.js:28)
    at Deferred.resolve (Deferred.js:192)
```

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1742

Fixes the case where the Apollo plugin is specified in the `apollo-config.groovy`

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  This is ready for review.  I can just merge it in to test it as well, but it basically removes the plugin after the fact if it was included anywhere.

**Comment by nathandunn** [comment]
thanks for mentioning the include.  Had forgotten that its not parsed with the rest of the JSON.

**Comment by deepakunni3** [comment]
@nathandunn Looks good. 👍 

It would be good to have this on staging and test it against Volvox to make sure we don't see the errors we saw earlier.

**Comment by nathandunn** [comment]
@deepakunni3  Yeah, I can move it there and we can retest.

**Comment by nathandunn** [comment]
I'll put it there when you finish testing #1740

**Pull request merged**
