### PR TITLE
Adding comments to sequence alterations

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR allows users to add comments while creating sequence alteration.
Thanks to @NehaVC for her inputs, ideas and feedback.

See #781 for more details on this feature request.

### CODE REVIEW

**Comment by nathandunn** [comment]
Implementation looks good.  NonReserved Property makes sense.  I was thinking comment earlier, but this should be fine, as well.     @deepakunni3  were these exported in GFF3 and SequenceAlteration?

**Comment by nathandunn** [comment]
Sorry . . . you can't test until #748 is fixed.  I'll put it in the test comment.

**Comment by deepakunni3** [comment]
Export of sequence alterations and its comments in GFF3 happens from the server side (using Gff3Service) as well as from the client side (reference track -> save track data).

I got the server to output sequence alterations in GFF3 export by a minor hack. But I am sure @cmdcolin  has an optimized way of handling the export. 

I can test again once #748 is done.

**Comment by nathandunn** [comment]
:+1:

**Pull request merged**
