### PR TITLE
added directories for sample data

### PR DESCRIPTION
**Pull request by nathandunn**
Feel free to push / update link data and merge if it looks correct.

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  This is ready to review.  Still re-uploading the amel-demo file, but the no-BAM one should work.

**Comment by nathandunn** [comment]
- [x] removed human
- [x] fixed yeast: https://s3.amazonaws.com/apollo-data/yeast.tgz 
- [x] fixed volvox: https://s3.amazonaws.com/apollo-data/volvox.tgz
- [ ] fixed and upload honeybee-nobam: https://s3.amazonaws.com/apollo-data/data-amel-demo-nobam.tgz
- [ ] fixed and upload honeybee: https://s3.amazonaws.com/apollo-data/data-amel-demo.tgz

**Comment by nathandunn** [comment]
@deepakunni3  Ready to re-review.  I've re-added all versions.

**Comment by deepakunni3** [comment]
@nathandunn Looks good and ready to merge 👍

**Pull request merged**
