### PR TITLE
update client plugin for JBrowse 1.13

### PR DESCRIPTION
**Pull request by rbuels**
refactor to install jquery and jqueryui from npm, rely on webpack for importing them via commonJS.

I haven't tested this functionality, just gotten it to build under webpack.

To test it out, check out the `dojo-webpack-plugin` branch of JBrowse, check out this branch, and then install the client plugin in the dev checkout of your JBrowse like:

```
cd jbrowse;
npm install path/to/your/Apollo/client/apollo
```

which should create node_modules/@gmod/apollo-jbrowse-plugin, which should be discovered by JBrowse when you run `./setup.sh` or (more directly) `npm run build`

### CODE REVIEW

**Comment by nathandunn** [comment]
@rbuels  this is great.  I 'll need to test it, etc.  

We loved JBrowse so much, we even had it when we didn't use it! 

I think there is an error in some of the code here, but I can fix that, as well.  https://travis-ci.org/GMOD/Apollo/jobs/350654153#L1603

**Comment by nathandunn** [comment]
@rbuels  I take that back.  It looks like I need to convert jshint to use es6 as you're babelly, webpacky goodness will backport stuff.  

This will be fun.  I'll fix that and test.

**Comment by nathandunn** [comment]
Running into issues with loading the bundle:

screen shot 2018-03-09 at 9 43 21 am

For some reason RegexSequenceSearch does not have a "location" entry:

            p.location = configEntry.location

I think its an apollo problem.  Will keep poking around, or will directly fix the entry.

**Comment by nathandunn** [comment]
Forgot to integrate the npm install.  

- [ ] fix code install for deploy
- [ ] fix code install for dev
- [ ] fix .jshint for tests
- [ ] update doc? 
- [ ] submit npmjs?

**Comment by nathandunn** [comment]
@rbuels I'm running into this problem. 

Apollo comes in with properly identified `plugins`:


```
Array(8)
0
:
{name: "RegexSequenceSearch"}
1
:
{name: "WebApollo", location: "./plugins/WebApollo/js", included: true, pluginsDir: "./plugins/WebApollo"}
2
:
{name: "HideTrackLabels", location: "./plugins/HideTrackLabels", included: true}
3
:
{git: "https://github.com/awilkey/fullscreen-jbrowse", alwaysPull: "false", name: "FullscreenJBrowse", location: "./plugins/FullscreenJBrowse", branch: "master"}
4
:
{name: "NeatHTMLFeatures", location: "./plugins/NeatHTMLFeatures", included: true}
5
:
{name: "NeatCanvasFeatures", location: "./plugins/NeatCanvasFeatures", included: true}
6
:
{alwaysRecheck: true, git: "https://github.com/NAL-i5K/NAL_CSS", alwaysPull: true, name: "NAL_CSS", location: "./plugins/NAL_CSS", …}
7
:
{alwaysRecheck: true, git: "https://github.com/elsiklab/gccontent", alwaysPull: true, name: "GCContent", location: "./plugins/GCContent", …}
length
:
8
```

For plugins we get:

```
Array(18)
0
:
{name: "dojo", location: "./dist/dojo"}
1
:
{name: "dijit", location: "./dist/dijit"}
2
:
{name: "dojox", location: "./dist/dojox"}
3
:
{name: "JBrowse", location: "src/JBrowse", lib: "."}
4
:
{name: "dgrid", location: "./dist/dgrid", lib: "."}
5
:
{name: "dstore", location: "./dist/dojo-dstore", lib: "."}
6
:
{name: "jszlib", location: "./dist/jszlib", lib: "."}
7
:
{name: "FileSaver", location: "./dist/filesaver.js", lib: "."}
8
:
{name: "CategoryUrl", pluginDir: "plugins/CategoryUrl/", location: "plugins/CategoryUrl/js"}
9
:
{name: "DebugEvents", pluginDir: "plugins/DebugEvents/", location: "plugins/DebugEvents/js"}
10
:
{name: "FullscreenJBrowse", pluginDir: "plugins/FullscreenJBrowse/", location: "plugins/FullscreenJBrowse/js"}
11
:
{name: "HideTrackLabels", pluginDir: "plugins/HideTrackLabels/", location: "plugins/HideTrackLabels/js"}
12
:
{name: "NAL_CSS", pluginDir: "plugins/NAL_CSS/", location: "plugins/NAL_CSS/js"}
13
:
{name: "NeatCanvasFeatures", pluginDir: "plugins/NeatCanvasFeatures/", location: "plugins/NeatCanvasFeatures/js"}
14
:
{name: "NeatHTMLFeatures", pluginDir: "plugins/NeatHTMLFeatures/", location: "plugins/NeatHTMLFeatures/js"}
15
:
{name: "RegexSequenceSearch", pluginDir: "plugins/RegexSequenceSearch/", location: "plugins/RegexSequenceSearch/js"}
16
:
{name: "WebApollo", pluginDir: "plugins/WebApollo/", location: "plugins/WebApollo/js"}
17
:
{name: "WebApollo", pluginDir: "node_modules/@gmod/apollo-jbrowse-plugin/", location: "node_modules/@gmod/apollo-jbrowse-plugin/js"}
```


I the configEntry for some reason, WebApollo is not found:

```
      plugins.forEach( p => {
            // find the entry in the dojoConfig for this plugin
            let configEntry = dojoConfig.packages.find(c => c.name === p.name)
            if( ! configEntry )
                this.fatalError(`plugin ${p.name} not found, please ensure the plugin was included in this JBrowse build`)

            p.location = configEntry.location
            p.css = configEntry.pluginDir+'css'
            p.js = configEntry.location
        });
```

I actually get the error configEntry that undefined is not found.  Of course, I can push through this, but I'm guessing you designed it so that the configEntry has to be there?!?   

Would actually be super-helpful if you had docs on how to do the plugin installs.

**Comment by nathandunn** [comment]
Hmm . .  your recent change seems to explain some things.   I'll give it a try

**Comment by rbuels** [comment]
On your dev machine, install the client plugin like:

```
   cd jbrowse
   npm install ../path/to/Apollo/client/apollo
```

It will make node_modules/@gmod/apollo-jbrowse-plugin a symlink to ../path/top/Apollo/client/apollo

**Comment by rbuels** [comment]
And you need to `cd jbrowse; npm run build` whenever you add or change plugins.  Basically, with webpack now, the plugin needs to be built in to be loadable.

The JBrowse build looks in three places for plugins to include in the build: `jbrowse/node_modules/@*/*-jbrowse-plugin`, `jbrowse/node_modules/*-jbrowse-plugin`, and `jbrowse/plugins/*`

**Comment by nathandunn** [comment]
I’ll have to take a look at it a bit later this week.   But what I actually think it means is that I can drastically simplify my install process.  Well, that’s what I hope it means.

**Comment by rbuels** [comment]
I dunno, looking around your codebase a little bit, it might be better not to publish the apollo plugin on npm, but instead install it by symlinking it into jbrowse/plugins/WebApollo or similar.

**Comment by nathandunn** [comment]
Agreed.

**Comment by nathandunn** [comment]
Don’t install the Apollo client plugin from npm. 


- install jbrowse using npm still
- symlink to the Apollo client into the plugins directory 
- run setup.sh or npm run build


=====

- git clone —single-branch jbrowse  (or download from .zip)
- cd jbrowse
- cp client/apollo into the plugins directory as before
- npm run build  (or setup.sh to install)
(Everything else is the same)

**Comment by nathandunn** [comment]
Instructions for me to follow:
- npm install gmod/jbrowse
- cd node_modules/@gmod/jbrowse
- cp -r ../../../client/apollo plugins
- npm run build

Gets me:

```
npm run build 

> @gmod/jbrowse@1.13.1-alpha.0 build /Users/nathandunn/repositories/nathanApolloMaster/node_modules/@gmod/jbrowse
> node node_modules/webpack/bin/webpack.js --config webpack.config.js

module.js:540
    throw err;
    ^

Error: Cannot find module '/Users/nathandunn/repositories/nathanApolloMaster/node_modules/@gmod/jbrowse/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @gmod/jbrowse@1.13.1-alpha.0 build: `node node_modules/webpack/bin/webpack.js --config webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @gmod/jbrowse@1.13.1-alpha.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathandunn/.npm/_logs/2018-03-14T22_27_22_564Z-debug.log
```

**Comment by nathandunn** [comment]
just gives node_modules/* with depdencies and jbrowse.   Same result for: npm install https://github.com/GMOD/jbrowse

For npm install https://github.com/GMOD/jbrowse/archive/2f52e30a72ff1f823f671926f52d65f26cf6fb9f.zip  (or dev.zip) gives:

```
npm install https://github.com/GMOD/jbrowse/archive/2f52e30a72ff1f823f671926f52d65f26cf6fb9f.zip 
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://github.com/GMOD/jbrowse/archive/2f52e30a72ff1f823f671926f52d65f26cf6fb9f.zip.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathandunn/.npm/_logs/2018-03-14T22_33_59_882Z-debug.log
```

with nothing much added.

**Comment by nathandunn** [comment]
Using: 

    npm install @gmod/jbrowse
    cd node_modules
    mv * @gmod/jbrowse/src/
    cd @gmod/jbrowse 
    cp -r ../../../client/apollo plugins/WebApollo
    npm install 
    npm run build 
    cd ../../../
    mv node_modules/@gmod/jbrowse web-app/jbrowse

Apollo specific stuff:
   
    gradle gwtc
    grails run-app 

That appeared kind of work, but the directory loading is causing problems. 

Redeployed (maybe thew new gradle copyResourcesDev) and I get this again: https://github.com/GMOD/Apollo/pull/1870#issuecomment-371891137

            domConstruct.place(toolsMenu.domNode,helpMenu.domNode,'before');

This seems to affect the track registration, but it come be somewhere else:

screen shot 2018-03-14 at 3 54 15 pm

**Comment by nathandunn** [comment]
Tools are undefined. 

screen shot 2018-03-14 at 3 55 53 pm

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/main.js#L394

**Comment by nathandunn** [comment]
Getting 404s here, so probably a JBrowseController error:

http://localhost:8080/apollo/19557127641827556458/jbrowse/dist/main.bundle.js

**Comment by nathandunn** [comment]
https://github.com/GMOD/Apollo/pull/1870#issuecomment-373214341

**Comment by rbuels** [comment]
This looks to me like too much change.

If you have a build that already works with previous versions of JBrowse, I'd advise just sticking with it, with the only change being: add a `npm install; npm run build` shell command somewhere to run the JBrowse build after installing the Apollo plugin.

**Comment by nathandunn** [comment]
Thanks to @rbuels  we realized that client/apollo was pulling from dijit 1.9 instead of the now current 1.12 and may have introduced async issues.

**Comment by nathandunn** [comment]
To update in web-mode from within web-app/jbrowse:

    rm -rf plugins/WebApollo && cp -r ../../client/apollo plugins/WebApollo && npm run build

**Comment by nathandunn** [comment]
Fixed this probably in a sort of ugly manner by allow for asynchronicity.    It seems like render should  be in the add callback and this "move" function should be in a further callback, but this works for now.

```
DraggableHTMLFeatures.js:1043 Uncaught TypeError: Cannot read property '_mouseDown' of undefined
    at Object.handleFeatureDragSetup (DraggableHTMLFeatures.js:1043)
    at Object.onFeatureMouseDown (DraggableHTMLFeatures.js:797)
    at HTMLDivElement.<anonymous> (lang.js:383)
    at HTMLDivElement.dispatch (jquery.js:5183)
    at HTMLDivElement.elemData.handle (jquery.js:4991)
```

**Comment by nathandunn** [comment]
@rbuels  Do you see an problems with this https://github.com/GMOD/Apollo/pull/1870/commits/226b1f70ff78d60b45e37e215ee1bd0ba8c2f261

Could not tell what it was supposed to do, but I can drag up, stretch, etc. etc.  Seems to work fine, though.

**Comment by nathandunn** [comment]
@rbuels   For next week.  The short and the sweet is that: 

https://github.com/GMOD/Apollo/pull/1870/commits/1a0dba64197ec96fcec56642cf695db99a91bb9e#diff-64bd5f23104820ad497fe0145c85ead0R1043

this re-click trigger fails because .data("draggable") from https://github.com/GMOD/Apollo/pull/1870#issuecomment-373851409 is null. 

Have tried every which way.  I'm sure it has to do with the way that jquery / jquery-ui work and have likely been updated.     Argh.

**Comment by nathandunn** [comment]
-     commandLine 'npm','install','GMOD/jbrowse'
-    // cp -r node_modules/@gmod/jbrowse .
-    // cd jbrowse
-    // npm install
-    // copy any remaining plugins in
-    // copy in webapollo plugin
-  //    commandLine 'npm','run','build'

```
 [594] ./plugins/DebugEvents/js/main.js 6.21 kB {3} [built]
 [595] ./plugins/CategoryUrl/js/main.js 4.48 kB {3} [built]
    + 1294 hidden modules

ERROR in ./plugins/WebApollo/js/Store/SeqFeature/ApolloGFF3.js
Module not found: Error: Can't resolve 'JBrowse/Store/SeqFeature/GFF3/Parser' in '/Users/nathandunn/repositories/nathanApolloMaster/jbrowse/plugins/WebApollo/js/Store/SeqFeature'
 @ ./plugins/WebApollo/js/Store/SeqFeature/ApolloGFF3.js 1:0-99:2
 @ ./src/JBrowse/main.js

ERROR in ./plugins/WebApollo/js/View/Track/DraggableHTMLVariants.js
Module not found: Error: Can't resolve 'jqueryui/draggable' in '/Users/nathandunn/repositories/nathanApolloMaster/jbrowse/plugins/WebApollo/js/View/Track'
 @ ./plugins/WebApollo/js/View/Track/DraggableHTMLVariants.js 1:0-613:2
 @ ./src/JBrowse/main.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @gmod/jbrowse@1.15.0-alpha.0 build: `webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @gmod/jbrowse@1.15.0-alpha.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nathandunn/.npm/_logs/2018-06-29T18_58_39_247Z-debug.log**
```

**Comment by nathandunn** [comment]
Note to self:  

- git clone or wget
- yarn 
- copy any additional plugins
- npm run build
- copyResourcesDev

**Comment by nathandunn** [comment]
- [ ] dependency detection (if file exists, don't do)
- [ ] consume JBrowse dependency correctly (branch, tag, etc.)
   - [ ] allow for git pulls 
- [ ] move provideLocalJBrowse to install

**Comment by nathandunn** [comment]
I think this is ready for review.  Yes, you do have to double-click the values to bring them up, but I think that's not an unusual user interaction. 

Also note.  These will work perfectly for volvox, etc.   To make the work properly for the honeybee case @deepakunni3  you need to prepend the .css with .jbrowse

**Comment by nathandunn** [comment]
I fixed honeybee on staging (just fixed the amel.css file). 

http://demo.genomearchitect.org/Apollo-staging/6727916261183724611246769118/jbrowse/data/amel.css

**Comment by nathandunn** [comment]
The dojo panels don't seem to be working with Apollo, so I'll have to fix those first.

**Comment by nathandunn** [comment]
- [ ] fix dialogs
- [ ] use npm versions of bbop?  (https://www.npmjs.com/package/bbop-widget-set)
- [ ] use npm versions of spring-websocket? (https://www.npmjs.com/package/sockjs-client , https://www.npmjs.com/package/@stomp/stompjs)

**Comment by nathandunn** [comment]
Spent a fair bit of time trying to fix the GOLR lookup.  Things I did:
- attempt to upgrade to use the more modern GOLR (lots of jquery dependency issues)
- attempt to do as a simple jquery ui lookup using var url = "https://api.monarchinitiative.org/api/search/entity/autocomplete/blood?prefix=GO&rows=20&start=0";
- the same API, but using dojo directly
- just removing the GOLR lookup 

Doing this, I started to notice a weird feature selection error.  "Fixing" it seemed to break other things.  This is evident in 2.1.0 though: https://github.com/GMOD/Apollo/issues/1918 so, not sure we need to fix here.

**Comment by nathandunn** [comment]
- [ ] add watch instrcutions / update watchman script?
     -  rm -rf web-app/jbrowse/plugins/WebApollo && cp -r client/apollo web-app/jbrowse/plugins/WebApollo
    - rpm run watch

**Comment by nathandunn** [comment]
@deepakunni3  Are you able to take a look at this when you have a moment? 

Thanks.

**Comment by nathandunn** [comment]
I removed the GO lookup, but may add that back later or do a simple validation.  Mostly I want to know if it is working, roughly for you.

**Comment by nathandunn** [comment]
Next week is fine, as well.

**Comment by deepakunni3** [comment]
@nathandunn sure thing!

**Comment by deepakunni3** [comment]
Ran into compilation issues:
```
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] /Users/deepak.unni3/GIT/Apollo-master/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy: 674: expecting '}', found 'automatically' @ line 674, column 23.
  [groovyc]                // should automatically write to history
  [groovyc]                          ^
  [groovyc] 
| Compiling 360 source files.
| Error Compilation error: startup failed:
/Users/deepak.unni3/GIT/Apollo-master/grails-app/services/org/bbop/apollo/RequestHandlingService.groovy: 674: expecting '}', found 'automatically' @ line 674, column 23.
               // should automatically write to history
                         ^

```

**Comment by nathandunn** [comment]
closing in favor of #1919

**Pull request closed without merging**
