### PR TITLE
Carson's color scheme implemented using a custom CSS file 

### PR DESCRIPTION
**Pull request by deepakunni3**

### CODE REVIEW

**Comment by nathandunn** [comment]
@monicacecilia   Not sure if we regressed on this one or not.

**Comment by cmdcolin** [comment]
The easiest way to solve these issues is to just do a "git merge master". It will just pull in the changes from 1.0 that we have done.

**Comment by nathandunn** [comment]
I thought you’d already done that.    If you did, do you know when you did it last?  If not, I’ll go ahead and try doing a merge.  

Nathan

**Comment by cmdcolin** [comment]
Should be ready after the merge of #248

**Comment by nathandunn** [comment]
@deepakunni3  @cmdcolin  @monicacecilia   Pretty sure that this has been done for awhile . . closing.

**Comment by monicacecilia** [comment]
:+1:

**Pull request closed without merging**
