### PR TITLE
Ability to sort annotations by their 'last updated' in Annotator Panel

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR extends the way we query the server and populate dataGrid in AnnotatorPanel to include 'Date of Last Updated' and let users sort annotations by date.

See #770

### CODE REVIEW

**Comment by cmdcolin** [comment]
This makes the annotator panel pretty wide. Need to be conscious of horizontal space

t6

Don't have specific recommendations but I would consider that before merge

**Comment by nathandunn** [comment]
@deepakunni3  I removed the extra date formatting that should have helped some of the wide-ness.  You have to fix it in the "buildTableRow" code.    A bit annoying, but it worked well with the rest of your code.  

@cmdcolin   Yeah, what goes on report pages vs this panel is going to be an interesting issue to straddle. 

screen shot 2016-01-19 at 1 32 24 pm

**Comment by deepakunni3** [comment]
Okay, I'll look into it. :+1

**Comment by nathandunn** [comment]
I already fixed and merged it.  See my commit above.

**Comment by deepakunni3** [comment]
ah, yes! I see the changes. :+1:

**Pull request merged**
