### PR TITLE
Add last page button

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds a "last page" button on the annotator panel. It also adjusts the fast forward size to be smaller on the user/group panels (50 instead of 1000) making it a "+5" pages instead of "+100" pages. The fast forward button size is still 1000 on the refseq panel

See #700

### CODE REVIEW

**Comment by cmdcolin** [comment]
Here's a screenshot. Fast forward+last page available


t8

**Comment by nathandunn** [comment]
If probably better to just remove the fast forward in favor of last page unless there is a good use case for it. 

Nathan

**Comment by cmdcolin** [comment]
That's a pretty easy change too. I don't really see the need for the fast forward. I'll push that forward

**Comment by nathandunn** [comment]
Great thanks. 

Nathan

**Comment by cmdcolin** [comment]
No fast forward button now! The search field is also very pretty responsive so with 1000 fake users for me so maybe need to find other scenarios

**Comment by nathandunn** [comment]
Perect . . thanks for looking into that for me.

**Pull request merged**
