### PR TITLE
#626 - login from public genomes . . added to annotation view

### PR DESCRIPTION
**Pull request by nathandunn**
This is a pretty simple fix.  My "idea" would be to replace the "full-screen" view with an annotator view.  In the interim I think that this is good.  @cmdcolin If you want to review / fix this, that would be great. 

Thanks.

### CODE REVIEW

**Comment by cmdcolin** [comment]
I don't think this should be a checkbox. I personally don't like it in the View column either. The Tools menu actually seems like a good place because you can access the "annotator tools"

**Comment by nathandunn** [comment]
I think that makes sense . . are you able to make that change or should I do it?

**Comment by cmdcolin** [comment]
Not to be a bug here, but I don't think we should merge our own pull requests.

In any case, this looks good so I don't mind here

**Comment by nathandunn** [comment]
In general I agree . . . in this case it was a small change and I'd already gotten feedback.

**Comment by cmdcolin** [comment]
No worry. Good solution to the problem here :)

**Pull request merged**
