### PR TITLE
Issue 1297

### PR DESCRIPTION
**Pull request by deepakunni3**
Fixes bug reported in  #1297 

Also added a simple integration test to check the CDS when a transcript, with an incomplete CDS, is added.

@nathandunn Ready for testing and review.

### CODE REVIEW

**Comment by nathandunn** [comment]
Taking a look now.

**Comment by nathandunn** [comment]
@deepakunni3  Was that entry redundant?   Why is @enuggetry  adding labels for us ;) ?

**Comment by deepakunni3** [comment]
@nathandunn Yes, it was redundant since `FeatureService::generateTranscript()` does the job of handling the CDS and there are proper checks for `useCDS`. 

My bad. It might have been introduced while working on the isoform overlap code.

Not sure why @enuggetry is adding the labels 😋

**Comment by nathandunn** [comment]
Works as designed.   When I changed the flag it worked as expected, recalculating the CDS every time.

**Pull request merged**
