### PR TITLE
fixes #1260

### LINKED ISSUE #1260: Only allow the model creator to delete a model (or an admin)
Related to #1257: We've occasionally had problems where one curator has deleted a model that another curator has created, without informing them about it. If the original curator wants to retrieve the deleted model, we have to restore it from backups. A curator suggested to us to only allow the model creator to delete a model (or an admin). This seems like a reasonable precaution to me, although it might not be desirable for all the use cases Apollo has to cover. Would it be possible to make this an option that could be configured by the global admin? Has anyone else encountered similar problems?

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1260

### CODE REVIEW

**Comment by nathandunn** [comment]
Ready for testing / review

**Comment by deepakunni3** [comment]
Now the problem is that if I am another user, and create an annotation - I am not able to delete the annotation even if I am the owner. I still can revert the annotation to an earlier state (as intended).

**Comment by nathandunn** [comment]
Okay.  I'll take a look.  I thought I'd tested that exact scenario, but maybe not.

**Comment by nathandunn** [comment]
@deepakunni3  I retested and I was able to delete my own (as a non-admin user), but not as another non-admin user.   Maybe I am missing the scenario.

**Comment by deepakunni3** [comment]
@nathandunn What happens when you assign READ, EXPORT and WRITE permissions to a non-admin user. And then add a transcript and try to delete it.

**Comment by nathandunn** [comment]
Talking with @deepakunni3  and we need cover the other delete methods (feature and exon?).

**Comment by deepakunni3** [comment]
Yes, `deleteFeature`, `deleteExon` in RHS.

**Comment by nathandunn** [comment]
@deepakunni3  It is ready now.     Exon's don't have the "owners" set.  So, now we search the parent.

**Comment by deepakunni3** [comment]
@nathandunn This issue needs more thought.

If I (a non-admin user) perform 'Change Annotation Type' operation on another user's annotation then I am able to take ownership of the altered annotation.

**Comment by deepakunni3** [comment]
@nathandunn The check for owner should apply to all structural edits. 

Not sure about edits to metadata. If we restrict to ownership then that can go against the collaborative effort of manual annotation.

**Comment by monicacecilia** [comment]
@deepakunni3 precisely - which is one of the reasons why I have been vocal against not allowing curators to remove annotations done by others in the first place. 
Also, #1260 is most definitely not a priority at the moment.

**Comment by nathandunn** [comment]
I think the core of this issue is that users would be prevented from deleting others annotations.  If I just need to add a line to prevent users for changing others annotation types, that is probably sufficient (this is default off, anyway).     I think that this was driven by i5K (@mpoelchau / @childers ) as well as other groups. 

The problem was when folks ignore the instructions.   So, I think the options are:

1 - leave as-is and there is a workaround by changing annotation types (just merge what is there)
2 - fix bug where changing annotation types changes owner (if that is a bug, not sure)
3 - prevent changing annotation types (for now) if deletion protection is in place (one line of code)

As this is non-default, I would be in favor of 1 or 3 if it is useful to anyone in the curation community.

**Comment by deepakunni3** [comment]
Option 1 - definitely no.
Option 2 - yes, this is a place to start
Option 3 - this is much better since only the owner can change annotation type. And changing annotation type is a destructive operation.

**Comment by nathandunn** [comment]
Okay.  I opted for option 3.

**Comment by childers** [comment]
@nathandunn Just confirming, this only covers deletion or changing of the feature type, right? Does this include additional modifications to an existing model, or adjusting of the features metadata?

**Comment by nathandunn** [comment]
You are correct.  Changing in deletions, changes in feature type, and history revision are the only modifications not allowed when this is enabled.

**Comment by childers** [comment]
So that includes partial deletions, like removing exons form someones model?  I'm trying to build this commit now (see #1707  )

**Comment by nathandunn** [comment]
Yes, this includes partial deletions (removing exons).    I just saw #1707. I'll take a look.

**Comment by childers** [comment]
It appears to work, (I made an annotation and logged in as another user and was unable to delete it). There is no pop up or explanation as to why the model is not deleted, you simply click yes on the confirmation dialog, then nothing happens. If deletion of other peoples models is enabled, could there be a pop up to let users know why their attempt to delete is failing?

**Comment by childers** [comment]
I might be having some other type of issue. @mpoelchau and I are testing..

**Comment by nathandunn** [comment]
There should be a notification that pops up.  I'll try testing it for when its deployed. I know we'd run into this earlier (e.g., trying to write to a track with read-only permissions), but I can't remember the end result.

**Comment by mpoelchau** [comment]
I think we had some caching problems, or needed to clear the preferences table, or both. At any rate, I can see the pop-up now ("Only feature owner or admin may delete, change type, or revert annotation to an earlier state").

**Comment by mpoelchau** [comment]
I have some misgivings about not being able to delete exons in a model created by another owner. I think there is a legitimate use-case for a collaborator to remove an exon from a model. Also, if an exon is removed, the owner can still retrieve the former state of the model via the history - however, if the entire model is removed, then it cannot be retrieved (which is why we requested this feature). 

I still think this is a great update - thanks for working on it!

**Comment by monicacecilia** [comment]
>I have some misgivings about not being able to delete exons in a model created by another owner. 

@mpoelchau I hear you. I have a lot of misgivings about all these changes. But no one is paying much attention to what I have to say here ... ;)

**Pull request merged**
