### PR TITLE
Install npm package

### PR DESCRIPTION
**Pull request by nathandunn**
The current method always pulled master instead of a tag or a branch, which is less than ideal.  

The main reason for ignoring npm was that it complained about not having a top-level package.json.  This should fix that.

### CODE REVIEW

**Comment by nathandunn** [comment]
- [ ] tested node 8
- [ ] test de novo node 8 (with apollo-config.groovy)

- [x] tested node 7
- [ ] test de novo node 7 (with apollo-config.groovy)

- [ ] test de novo node 6 (with apollo-config.groovy)

- [ ] tested node 5
- [ ] test de novo node 5 (with apollo-config.groovy)

**Comment by nathandunn** [comment]
So, testing with node 5 fails if already installed: 

```
Moving JBrowse into position gmod/jbrowse#17111e6da6677085f1aeed41216fb558b63ed7ad
Legacy scripts wig-to-json.pl and bam-to-json.pl have removed from setup. Their functionality has been superseded by add-bam-track.pl and add-bw-track.pl. If you require the old versions, run 'setup.sh legacy'.
Installing javascript dependencies ...Dojo does not exist, installing
npm WARN jbrowse@1.12.4-SNAPSHOT No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/nathandunn/.nvm/versions/node/v5.12.0/bin/node" "/Users/nathandunn/.nvm/versions/node/v5.12.0/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path /Users/nathandunn/repositories/nathanApolloMaster/jbrowse-download/node_modules/.staging/jbrowse-4e9067e2
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/nathandunn/repositories/nathanApolloMaster/jbrowse-download/node_modules/.staging/jbrowse-4e9067e2' -> '/Users/nathandunn/repositories/nathanApolloMaster/jbrowse-download'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/nathandunn/repositories/nathanApolloMaster/jbrowse-download/node_modules/.staging/jbrowse-4e9067e2' -> '/Users/nathandunn/repositories/nathanApolloMaster/jbrowse-download'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/nathandunn/.nvm/versions/node/v5.12.0/bin/node" "/Users/nathandunn/.nvm/versions/node/v5.12.0/bin/npm" "install"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! path npm-debug.log.1896703852
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.1896703852'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.1896703852'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nathandunn/repositories/nathanApolloMaster/jbrowse-download/npm-debug.log
done
Gathering system information ..../setup.sh: line 57: setup.log: No such file or directory
done
Installing Perl prerequisites ..../setup.sh: line 70: setup.log: No such file or directory
 failed.  See setup.log file for error messages. As a first troubleshooting step, make sure development libraries and header files for GD, Zlib, and libpng are installed and try again.

Formatting Volvox example data ..../setup.sh: line 111: setup.log: No such file or directory
 failed.  See setup.log file for error messages.

Formatting Yeast example data ..../setup.sh: line 127: setup.log: No such file or directory
 failed.  See setup.log file for error messages.
Legacy scripts wig-to-json.pl and bam-to-json.pl have removed from setup. Their functionality 
```

**Comment by nathandunn** [comment]
@luke-c-sargent  Just an FYI.  I added NPM back (though the default for plugins is still a shell git clone).    I added a root-level package.json, which seems to fix most of the problems.  The only remaining issue AFAIK is that node 5 sort of half-works.    Let me know if it works. 

@childers  I think this might fix the build issues.  Hopefully @deepakunni3  can verify this, as well.

**Comment by nathandunn** [comment]
@deepakunni3  / @enuggetry   Not sure if I should ignore or add these:
```
	jb_run.js
	jb_setup.js
	package-lock.json
```

Thoughts?

**Comment by deepakunni3** [comment]
@nathandunn It would be better to simply use `shell` to install plugins.

The option of `npm` is giving problems.

**Comment by nathandunn** [comment]
@deepakunni3  Is this what you were suggesting? 
https://github.com/GMOD/Apollo/pull/1773/commits/a64b1553d9ea06b489404fe55308f3aadf9b361d

- npm is only allowed only for JBrowse
- shell is only allowed for JBrowse plugins

Also, it sounds like you tested this?   Is it ready to merge with those changes (I retested with plugins and my changes and it still worked). 

Thanks.

**Comment by deepakunni3** [comment]
@nathandunn Yes, now the build works without any problems.
Ready to merge 👍

**Pull request merged**
