### PR TITLE
Trackpanel native

### PR DESCRIPTION
**Pull request by cmdcolin**
This adds a checkbox to the track panel to enable the native track list view

The page is then refreshed and it will render the native jbrowse track selector

The toggle is stored in the UserOrganismPreference table

See #597

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   . .. are you ready for me to take a look at this?   No worries if not . . I have a couple of other things to fix.

**Comment by cmdcolin** [comment]
Should be ok to test

**Comment by cmdcolin** [comment]
Pushing an update shortly

**Comment by cmdcolin** [comment]
Should respond better now

**Comment by nathandunn** [comment]
Thanks . . will take a look shortly. . .

**Comment by nathandunn** [comment]
looks . . going to run through a quick test and then merge it in

**Comment by nathandunn** [comment]
looks good  I mean

**Comment by nathandunn** [comment]
@cmdcolin   I think it works well enough . . somehow the preference is acting as a "global" preference, which I don't think is what you intended.

**Comment by nathandunn** [comment]
@cmdcolin   Was also curious what you thought about this as a toggle switch?:

https://gwtbootstrap3.github.io/gwtbootstrap3-demo/#toggleswitch

A little extra sugar .. but I'm not sure if it will be more or less confusing to the user.   The checkbox is pretty clear.   I think a toggle button would be confusing.

**Pull request merged**
