### PR TITLE
Optimize GFF3 exports

### PR DESCRIPTION
**Pull request by cmdcolin**
I experimented with a couple more optimizations for GFF3 export, I'll describe two main things used here:

First I used a query that, in one go, grabs gene, mRNA, and exon/cds and their feature locations in HQL. I also experimented with joining other tables, such as feature properties, owners, dbxrefs, etc in this single query, under the assumption that it would reduce lazy fetching and make things faster, but it actually made things several times slower (although I did have it where it queries everything in one single query, that query would be very slow. now it does a bunch of queries, but presumably the cache handles it. this article explains the tradeoffs and mentions this too http://www.javalobby.org/articles/hibernate-query-101/)

That leads to the 2nd optimization which is that the gff3 export was also checking for dbxrefs, properties, owners, synonyms, etc on exons/CDS, and since all this info is in separate sql tables, and there are vastly more exons/cds than there are individual genes and transcript, this took a long time. I made exporting these types of things go away for the exon/CDS subfeatures, but added an optional config variable to turn it back on if it is really needed!

Tests on time with OSX SSD postgres 9.5 "apollo run local"

Benchmarks:
After (several trials):
Exporting 6093 features from honeybee 1m12.369s,1m7.573s,1m8.189s
Exporting 341 features on pythium 0m11.593s,0m8.000s,0m7.149s,0m8.947s

Before (several trials):
Exporting 6093 features from honeybee: 13m54.005s,13m36.862s,13m32.043s
Exporting 341 features on pythium: 0m51.545s,0m47.980s,0m44.955s,0m44.303s

So, you can see pretty good speedups across the board

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin   I think that this is the right solution overall.  Sucks to go back into HQL with crazy joins, but this is typically the solution.   Still testing. .

**Comment by nathandunn** [comment]
I'm getting this error:

```
 Error 2016-01-29 11:16:04,795 [http-bio-8080-exec-4] ERROR ast.ErrorCounter  - line 1:537: unexpected token: where
| Error 2016-01-29 11:16:04,796 [http-bio-8080-exec-4] ERROR ast.ErrorCounter  - line 1:537: unexpected token: where
Message: unexpected token: where
    Line | Method
->>   87 | _do_write        in org.bbop.apollo.IOServiceController
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    198 | doFilter         in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter . . . . in grails.plugin.cache.web.filter.AbstractFilter
|    449 | executeChain     in org.apache.shiro.web.servlet.AbstractShiroFilter
|    365 | call . . . . . . in org.apache.shiro.web.servlet.AbstractShiroFilter$1
|     90 | doCall           in org.apache.shiro.subject.support.SubjectCallable
|     83 | call . . . . . . in     ''
|    383 | execute          in org.apache.shiro.subject.support.DelegatingSubject
|    362 | doFilterInternal in org.apache.shiro.web.servlet.AbstractShiroFilter
|    125 | doFilter         in org.apache.shiro.web.servlet.OncePerRequestFilter
|   1145 | runWorker . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run              in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . .  in java.lang.Thread
| Error org.springframework.orm.hibernate4.HibernateQueryException: unexpected token: where near line 1, column 537 [select distinct f from org.bbop.apollo.Gene f join fetch f.featureLocations fl join fetch f.parentFeatureRelationships pr join fetch pr.childFeature child join fetch child.featureLocations join fetch child.childFeatureRelationships join fetch child.parentFeatureRelationships cpr join fetch cpr.childFeature subchild join fetch subchild.featureLocations join fetch subchild.childFeatureRelationships left join fetch subchild.parentFeatureRelationships where fl.sequence.organism = :organism and f.class in (:viewableAnnotationList) and where fl.sequence.name in (:sequences)]; nested exception is org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: where near line 1, column 537 [select distinct f from org.bbop.apollo.Gene f join fetch f.featureLocations fl join fetch f.parentFeatureRelationships pr join fetch pr.childFeature child join fetch child.featureLocations join fetch child.childFeatureRelationships join fetch child.parentFeatureRelationships cpr join fetch cpr.childFeature subchild join fetch subchild.featureLocations join fetch subchild.childFeatureRelationships left join fetch subchild.parentFeatureRelationships where fl.sequence.organism = :organism and f.class in (:viewableAnnotationList) and where fl.sequence.name in (:sequences)]
| Error 	at org.springframework.orm.hibernate4.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:173)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.convertHibernateAccessException(GrailsHibernateTemplate.java:593)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.doExecute(GrailsHibernateTemplate.java:183)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.GrailsHibernateTemplate.executeFind(GrailsHibernateTemplate.java:127)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.ExecuteQueryPersistentMethod.doInvokeInternal(ExecuteQueryPersistentMethod.java:89)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:79)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.metaclass.AbstractStaticPersistentMethod.invoke(AbstractStaticPersistentMethod.java:72)
| Error 	at org.codehaus.groovy.grails.orm.hibernate.HibernateGormStaticApi.executeQuery(HibernateGormStaticApi.groovy:545)
| Error 	at org.bbop.apollo.Gene.executeQuery(Gene.groovy)
| Error 	at org.bbop.apollo.Gene$executeQuery.call(Unknown Source)
| Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
| Error 	at org.bbop.apollo.IOServiceController._do_write(IOServiceController.groovy:87)
| Error 	at org.bbop.apollo.IOServiceController.this$3$_do_write(IOServiceController.groovy)
| Error 	at org.bbop.apollo.IOServiceController$this$3$_do_write.callCurrent(Unknown Source)
| Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:137)
| Error 	at org.bbop.apollo.IOServiceController.write(IOServiceController.groovy)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.MixedGrailsControllerHelper.invoke(MixedGrailsControllerHelper.java:154)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleAction(AbstractGrailsControllerHelper.java:375)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.executeAction(AbstractGrailsControllerHelper.java:252)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:205)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.AbstractGrailsControllerHelper.handleURI(AbstractGrailsControllerHelper.java:126)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.SimpleGrailsController.handleRequest(SimpleGrailsController.java:72)
| Error 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
| Error 	at org.codehaus.groovy.grails.web.servlet.GrailsDispatcherServlet.doDispatch(GrailsDispatcherServlet.java:347)
| Error 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
| Error 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
| Error 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:863)
| Error 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
| Error 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
| Error 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
| Error 	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
| Error 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
| Error 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
| Error 	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
| Error 	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
| Error 	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
| Error 	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:178)
| Error 	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:144)
| Error 	at org.codehaus.groovy.grails.web.mapping.UrlMappingUtils.forwardRequestForUrlMappingInfo(UrlMappingUtils.java:135)
| Error 	at org.codehaus.groovy.grails.web.mapping.filter.UrlMappingsFilter.doFilterInternal(UrlMappingsFilter.java:216)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.codehaus.groovy.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:69)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.codehaus.groovy.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
| Error 	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
| Error 	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
| Error 	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
| Error 	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
| Error 	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
| Error 	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
| Error 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
| Error 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
| Error 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
| Error 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
| Error 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
| Error 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
| Error 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
| Error 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
| Error 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
| Error 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
| Error 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
| Error 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
| Error 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
| Error 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
| Error 	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
| Error 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
| Error 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nathandunn** [comment]
viewableAnnotationList) **and where** fl.sequence.name

**Comment by cmdcolin** [comment]
Good catch... I think I fixed that error you mentioned here 7f9ad5b

**Comment by cmdcolin** [comment]
IOServiceController could probably use a test suite too. Not sure

**Comment by nathandunn** [comment]
I'm retesting with a cleaner build. . . give me a minute

**Comment by nathandunn** [comment]
Related to #274.

**Comment by nathandunn** [comment]
I am getting this error when I have a pseudogene, otherwise seems to work fine:

```
016-01-29 11:59:09,415 [http-bio-8080-exec-9] WARN  apollo.JbrowseController  - File not found: /opt/apollo/honeybee/data//tracks.conf
| Error java.lang.NullPointerException: Cannot get property 'uniqueName' on null object
| Error 	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:57)
| Error 	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:168)
| Error 	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:44)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
| Error 	at org.bbop.apollo.Gff3HandlerService._do_extractAttributes(Gff3HandlerService.groovy:298)
| Error 	at org.bbop.apollo.Gff3HandlerService.this$2$_do_extractAttributes(Gff3HandlerService.groovy)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
| Error 	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:207)
```

**Pull request merged**
