### PR TITLE
Allow default type 1861, fixes #1861

### LINKED ISSUE #1861: creating annotations should preserve track type
From: http://gmod.827538.n3.nabble.com/trackable-tracks-conversion-td4059136.html

In theory, we could adapt this code:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L1008

to pick out and render types according to:

https://github.com/GMOD/Apollo/blob/master/client/apollo/js/View/Track/AnnotTrack.js#L1401

Any thoughts @selewis  / @deepakunni3 ?

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #1861

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  Do you have a second to take a look at this?

**Comment by epaule** [comment]
in the configure.md is a quotation mark missing in front of the default_biotype

**Comment by epaule** [comment]
hm ... the type seems to still show up as column 2 rather than the one from the config.
I used that as tracklist config (it is just consecutive blocks marked up as features/tokens):
      {
         "compress" : 0,
         "key" : "Tokens_full_genome",
         "label" : "tokens2",
         "storeClass" : "JBrowse/Store/SeqFeature/NCList",
         "style" : {
            "className" : "feature"
         },
         "trackType" : "CanvasFeatures",
         "type" : "CanvasFeatures",
         "urlTemplate" : "tracks/tokens2/{refseq}/trackData.json",
         "default_biotype" : "ncRNA"
      },

**Comment by epaule** [comment]
let me quote my colleague: 
It seems to work nicely with biotypes rRNA and miRNA. But with repeat_region and transposable_element the annotation never appears in the scratch area.

**Comment by nathandunn** [comment]
@epaule  I fixed both issues (doc and handling repeat_region).  Sorry, should have tested the single-level better, as well.

> the type seems to still show up as column 2 rather than the one from the config.

Not sure what you mean by this exactly.

**Comment by epaule** [comment]
I meant the type that is shown under details, but admittedly that was also when i used CanvasFeatures and as long as the track does behave properly, I don't mind what is shown as "type" in the details.

thanks for the quick fixes :-)

**Comment by nathandunn** [comment]
Ah.  Okay.    Well, let us know if this works for you and we can get it merged in.

**Comment by deepakunni3** [comment]
@nathandunn Looks good except for this bug:

When I define a track's `default_biotype` as `rRNA` and if I drag and drop the annotation - I get a rRNA on the annotations track.
But if I right click and select 'Create a new annotation' -> 'gene', I still end up with an rRNA when it should be a protein coding gene since that selection is an explicit action of saying 'Create an mRNA from this feature'.

**Comment by nathandunn** [comment]
@deepakunni3  I think I fixed it.   Let me know if you feel like there is a better design.  Otherwise, just needs a test and a merge.

**Comment by deepakunni3** [comment]
@nathandunn Tested and looks good. 👍

**Comment by epaule** [comment]
looking good from this side of the pond too :+1:

**Pull request merged**
