### PR TITLE
initial attempt neat html features

### LINKED ISSUE #2004: neat features fails to install correctly
Seems to be its looking up the CSS wrong.  This would be related to the 1.15 release and probably not properly the correct css.

### PR DESCRIPTION
**Pull request by nathandunn**
fixes #2004 by making neat features the default for AnnotTrack.js

Unresolved issues:
- [ ] if transcript exceeds last exceed not always visible, is kind of hidden (smaller bug)
- [ ] history not properly rendering
- [ ] After a 'set read through stop codon' operation on a transcript, the intron hats creep into the exon region.

- ~~untranslated exons not always given a black box around them~~ unable to reproduce

- [x] make work with HTMLFeatures
- [x] make work with CanvasFeatures
- [x] make the default for FeatureTrack 
- [x] refactor to use mixins:
  - [x] canvasneatfeatures
  - [x] htmlneatfeatures
- [x] make a non-default

### CODE REVIEW

**Comment by nathandunn** [comment]
Not sure what is up with the HTML stuff.  I get this:

image

which is great for a local honeybee track, but for everything else I get this:

image

**Comment by nathandunn** [comment]
Weirdly . . it works because of the line `plugins`:

```
{
   "share_link" : 0,
   "plugins": [ "HideTrackLabel"], 
   "tracks" : [
```

Weirdly . . anything in there seems to work just fine:

screen shot 2019-01-22 at 1 34 44 pm
screen shot 2019-01-22 at 1 33 51 pm
screen shot 2019-01-22 at 1 32 05 pm

**Comment by nathandunn** [comment]
Results here.   Let me know what you think (or if there is a way to make it more configurable):

http://demo.genomearchitect.org/Apollo-staging/annotator/index 


Cheers,

Nathan

**Comment by nathandunn** [comment]
- [ ] UTRs not always visible (attached)
- [ ] untranslated exons not always given a black box around them

**Comment by nathandunn** [comment]
screen shot 2019-01-22 at 6 30 19 pm

screen shot 2019-01-22 at 6 28 35 pm

**Comment by deepakunni3** [comment]
screen shot 2019-01-22 at 8 32 38 pm

Two issues spotted:
1. Missing 3'UTR on NeatCanvasFeatures
2. Intron hats are not in the proper orientation for reverse stranded features

**Comment by deepakunni3** [comment]
screen shot 2019-01-23 at 11 12 22 am

Another issue:
- After a 'set read through stop codon' operation on a transcript, the intron hats creep into the exon region.

**Comment by nathandunn** [comment]
Note this read through stop codon error ONLY occurs on the negative strand.

**Comment by deepakunni3** [comment]
@nathandunn Not always. This also affects features on positive strand (refer to the image posted earlier)

**Comment by nathandunn** [comment]
oh @deepakunni3  good catch . . must have been the examples I was looking at.

**Pull request merged**
